// High quality expansion for all 20 categories to reach 2,000+ total concepts
export const categoryExpansions = {
  animals: [
    { w: 'CHACAL', f: ['Desierto', 'Lobo', 'Aullar', 'Carroña'] },
    { w: 'DROMEDARIO', f: ['Joroba', 'Una', 'Desierto', 'Camello'] },
    { w: 'ÑU', f: ['Sabana', 'Cruzar río', 'Manada', 'África'] },
    { w: 'GAZELA', f: ['Saltar', 'Rápida', 'Sabana', 'Depredador'] },
    { w: 'IMPALA', f: ['Cuernos', 'Salto alto', 'África', 'Antílope'] },
    { w: 'FACÓQUERO / PUMBA', f: ['Colmillos', 'Sabana', 'Jabalí verrugoso', 'Hakuna Matata'] },
    { w: 'MANDRIL', f: ['Cara azul y roja', 'Mono', 'Rafiki', 'Colores'] },
    { w: 'BABUINO', f: ['Mono', 'Hocico largo', 'Manada', 'África'] },
    { w: 'GIBÓN', f: ['Brazos largos', 'Árboles', 'Mono', 'Asia'] },
    { w: 'TITÍ', f: ['Mono enano', 'Pequeño', 'Árbol', 'Selva'] },
    { w: 'ALCE', f: ['Cuernos planos', 'Canadá', 'Nieve', 'Grande'] },
    { w: 'RENO', f: ['Rodolfo', 'Trineo', 'Cuernos', 'Nieve'] },
    { w: 'CORZO', f: ['Ciervo pequeño', 'Bosque', 'Cuernitos', 'Saltar'] },
    { w: 'BISONTE', f: ['Búfalo americano', 'Joroba', 'Pelo espeso', 'Pradera'] },
    { w: 'BÚFALO', f: ['Cuernos curvos', 'Agua', 'Manada', 'África'] },
    { w: 'YAK', f: ['Tíbet', 'Pelo largo', 'Montaña', 'Himalaya'] },
    { w: 'LLAMA', f: ['Escupir', 'Andes', 'Perú', 'Lana'] },
    { w: 'ALPACA', f: ['Lana suave', 'Perú', 'Montaña', 'Llama'] },
    { w: 'VICUÑA', f: ['Andes', 'Salvaje', 'Lana fina', 'Llama'] },
    { w: 'TAPIR', f: ['Trompa pequeña', 'Selva', 'Cerdo grande', 'Agua'] },
    { w: 'OSO HORMIGUERO', f: ['Lengua larga', 'Hormigas', 'Hocico fino', 'Garras'] },
    { w: 'PANGOLÍN', f: ['Escamas duras', 'Bola', 'Come hormigas', 'Armadura'] },
    { w: 'QUOKKA', f: ['Animal sonriente', 'Australia', 'Selfie', 'Marsupial'] },
    { w: 'WOMBAT', f: ['Caca cuadrada', 'Australia', 'Madriguera', 'Gordo'] },
    { w: 'DIABLO DE TASMANIA', f: ['Girar', 'Grito', 'Mandíbula fuerte', 'Australia'] },
    { w: 'KIWI (AVE)', f: ['Nueva Zelanda', 'Pico largo', 'No vuela', 'Nocturno'] },
    { w: 'CASUARIO', f: ['Pájaro peligroso', 'Casco azul', 'Garras', 'Australia'] },
    { w: 'EMÚ', f: ['Pájaro grande', 'Corre rápido', 'Australia', 'Avestruz'] },
    { w: 'CONDOR', f: ['Andes', 'Volar alto', 'Pájaro gigante', 'Carroñero'] },
    { w: 'BUITRE', f: ['Carroña', 'Cuello pelado', 'Círculos en el cielo', 'Animales muertos'] },
    { w: 'ALBATROS', f: ['Alas enormes', 'Océano', 'Volar sin parar', 'Mar'] },
    { w: 'PESTAÑOSO / MARTINETE', f: ['Pájaro pescador', 'Río', 'Agua', 'Pico'] },
    { w: 'MARTÍN PESCADOR', f: ['Azul brillante', 'Río', 'Pescado', 'Zambullirse'] },
    { w: 'MIRLO', f: ['Pico naranja', 'Plumas negras', 'Cantar', 'Jardín'] },
    { w: 'PETIRROJO', f: ['Pecho rojo', 'Pájaro pequeño', 'Jardín', 'Invierno'] },
    { w: 'GORRIÓN', f: ['Pájaro común', 'Migas de pan', 'Ciudad', 'Marrón'] },
    { w: 'JILGUERO', f: ['Cantar bien', 'Cara roja', 'Alas amarillas', 'Pájaro'] },
    { w: 'URRACA', f: ['Blanco y negro', 'Cosas brillantes', 'Robar', 'Pájaro listo'] },
    { w: 'GRAJO', f: ['Vuela bajo', 'Negro', 'Frío', 'Cuervo'] },
    { w: 'PÁJARO CARPINTERO', f: ['Picotear madera', 'Árbol', 'Pico fuerte', 'Ruido toc-toc'] },
    { w: 'NARVAL', f: ['Unicornio marino', 'Colmillo espiral', 'Ártico', 'Ballena'] },
    { w: 'BELUGA', f: ['Ballena blanca', 'Frente abultada', 'Sonreír', 'Ártico'] },
    { w: 'MANTECA / MANTA RAYA', f: ['Alas marinas', 'Flotar en agua', 'Cola con púa', 'Plana'] },
    { w: 'RAYA', f: ['Fondo de arena', 'Plana', 'Pez', 'Cola'] },
    { w: 'MORENA', f: ['Grieta de rocas', 'Dientes afilados', 'Serpiente marina', 'Morder'] },
    { w: 'ANGUILA', f: ['Eléctrica', 'Forma de serpiente', 'Río y mar', 'Resbaladiza'] },
    { w: 'BARRACUDA', f: ['Dientes grandes', 'Pez rápido', 'Mar tropical', 'Plateada'] },
    { w: 'PEZ GLOBO', f: ['Hincharse', 'Púas', 'Veneno fugu', 'Bola'] },
    { w: 'CABALLA', f: ['Pescado azul', 'Lata', 'Rayas oscuras', 'Saludable'] },
    { w: 'LENGUADO', f: ['Pez plano', 'Ojos arriba', 'Plancha', 'Arena'] },
    { w: 'RODABALLO', f: ['Pescado plano', 'Plato caro', 'Redondo', 'Mar'] },
    { w: 'LUBINA', f: ['Pescado al horno', 'Sal', 'Costa', 'Rico'] },
    { w: 'DORADA', f: ['Franja dorada', 'Horno a la sal', 'Pescado blanco', 'Espinas'] },
    { w: 'SEPIA / CHOCO', f: ['Tinta', 'Plancha con alioli', 'Calamar', 'Blanca'] },
    { w: 'GAMBA', f: ['Bigotes', 'Pelar', 'Plancha', 'Marisco'] },
    { w: 'LANGOSTINO', f: ['Navidad', 'Gamba grande', 'Pelar cabeza', 'Mayo'] },
    { w: 'BUEY DE MAR', f: ['Cangrejo gigante', 'Carrozas', 'Marisco', 'Pinzas'] },
    { w: 'CENTOLLO', f: ['Patas largas', 'Cangrejo con espinas', 'Galicia', 'Marisco'] },
    { w: 'PERCEBE', f: ['Rocas batidas', 'Uña negra', 'Galicia', 'Caro'] },
    { w: 'GUSANO DE SEDA', f: ['Hojas de morera', 'Capullo', 'Caja de zapatos', 'Mariposa'] }
  ],
  food: [
    { w: 'PAN CON TOMATE', f: ['Cataluña', 'Aceite', 'Ajo', 'Tostada'] },
    { w: 'ENSALADA MIXTA', f: ['Lechuga', 'Tomate', 'Atún', 'Cebolla'] },
    { w: 'SALCHICHÓN', f: ['Embutido', 'Pimienta', 'Curado', 'Bocadillo'] },
    { w: 'CHORIZO', f: ['Pimentón', 'Rojo', 'Tapa', 'Bocadillo'] },
    { w: 'MORCILLA DE BURGOS', f: ['Arroz', 'Sangre', 'Cebolla', 'Freír'] },
    { w: 'LOMO EMBUCHADO', f: ['Carne curada', 'Fino', 'Tapa', 'Cerdo'] },
    { w: 'LACÓN CON GRELOS', f: ['Galicia', 'Cerdo', 'Verdura amarga', 'Patatas cocidas'] },
    { w: 'POTAJE DE VIGILIA', f: ['Garbanzos', 'Espinacas', 'Bacalao', 'Cuaresma'] },
    { w: 'AJOBLANCO', f: ['Almendras', 'Ajo', 'Sopa fría', 'Uvas'] },
    { w: 'ESCALIVADA', f: ['Pimientos asados', 'Berenjena', 'Cebolla', 'Horno'] },
    { w: 'PISTO MANCHEGO', f: ['Verduras pochadas', 'Tomate', 'Huevo frito', 'Calabacín'] },
    { w: 'RABO DE TORO', f: ['Guiso meloso', 'Vino tinto', 'Carne tierna', 'Córdoba'] },
    { w: 'COCHINILLO ASADO', f: ['Segovia', 'Piel crujiente', 'Cortar con plato', 'Horno de leña'] },
    { w: 'LECHAZO ASADO', f: ['Cordero lechal', 'Castilla', 'Horno', 'Fiesta'] },
    { w: 'CHULETÓN DE BUEY', f: ['Brasas', 'Poco hecho', 'Carne roja', 'Sal gorda'] },
    { w: 'PULPO A LA BRASA', f: ['Tentáculo', 'Carbón', 'Puré de patatas', 'Restaurante'] },
    { w: 'MEJILLONES A LA MARINERA', f: ['Salsa picante', 'Tomate', 'Vapor', 'Pan'] },
    { w: 'ZAMBURIÑAS', f: ['Concha pequeña', 'Plancha', 'Galicia', 'Vieira'] },
    { w: 'VIEIRAS', f: ['Concha del peregrino', 'Santiago', 'Gratinada', 'Horno'] },
    { w: 'ALMEJAS AL VAPOR', f: ['Limón', 'Abrirse al calor', 'Cazuela', 'Mar'] },
    { w: 'ARROZ NEGRO', f: ['Tinta de calamar', 'Alioli', 'Paella oscura', 'Marisco'] },
    { w: 'FIDEUÁ', f: ['Fideos cortos', 'Marisco', 'Alioli', 'Paella de pasta'] },
    { w: 'ARROZ CALDOSO', f: ['Bogavante', 'Cazuela de barro', 'Caldo rico', 'Cuchara'] },
    { w: 'BOCADILLO DE CALAMARES', f: ['Plaza Mayor', 'Madrid', 'Pan crujiente', 'Mayonesa'] },
    { w: 'BOCADILLO DE TORTILLA', f: ['Barra de pan', 'Excursión', 'Huevos', 'Albal'] },
    { w: 'BIKINI / SÁNDWICH MIXTO', f: ['Jamón york', 'Queso fundido', 'Pan de molde', 'Plancha'] },
    { w: 'CROQUETAS DE BOLETUS', f: ['Setas', 'Bechamel', 'Hongos', 'Rebozadas'] },
    { w: 'HUEVOS ROTOS', f: ['Jamón', 'Yema líquida', 'Patatas fritas', 'Lucio'] },
    { w: 'REVUELTO DE SETAS', f: ['Ajos tiernos', 'Gambas', 'Sartén', 'Huevos'] },
    { w: 'TORTITAS CON NATA', f: ['Sirope', 'Desayuno americano', 'Masa esponjosa', 'Merienda'] },
    { w: 'BROWNIE', f: ['Nueces', 'Chocolate caliente', 'Bola de helado', 'Bizcocho denso'] },
    { w: 'COULANT DE CHOCOLATE', f: ['Volcán de chocolate', 'Centro líquido', 'Caliente', 'Postre'] },
    { w: 'TIRAMISÚ', f: ['Café', 'Mascarpone', 'Cacao en polvo', 'Bizcochos soletilla'] },
    { w: 'PROFITEROLES', f: ['Masa choux', 'Rellenos de nata', 'Salsa de chocolate', 'Bolas'] },
    { w: 'CREMA CATALANA', f: ['Azúcar quemado', 'Costra de caramelo', 'Quemador', 'Postre'] },
    { w: 'POLVORÓN', f: ['Navidad', 'Manteca de cerdo', 'Papel de seda', 'Apretar antes de comer'] },
    { w: 'TURRÓN DE JIJONA', f: ['Blando', 'Almendra molida', 'Navidad', 'Caja de madera'] },
    { w: 'TURRÓN DE ALICANTE', f: ['Duro', 'Almendras enteras', 'Oblea blanca', 'Miel'] },
    { w: 'TURRÓN DE CHOCOLATE', f: ['Arroz inflado', 'Suchard', 'Navidad', 'Tableta'] },
    { w: 'ROSCÓN DE REYES', f: ['Fruta escarchada', 'Haba', 'Figura', 'Nata'] },
    { w: 'BUÑUELOS DE VIENTO', f: ['Fritos', 'Huecos por dentro', 'Nata o crema', 'Noviembre'] },
    { w: 'HUESOS DE SANTO', f: ['Mazapán', 'Yema', 'Dulce blanco', 'Todos los Santos'] },
    { w: 'BARTOLILLOS', f: ['Crema pastelera', 'Frito', 'Masa fina', 'Madrid'] },
    { w: 'PALMERITA DE CHOCOLATE', f: ['Hojaldre', 'Forma de corazón', 'Glaseado oscuro', 'Pastelería'] },
    { w: 'MAGDALENAS', f: ['Copete', 'Mojar en leche', 'Papel rizado', 'Desayuno'] },
    { w: 'SOBAOS PASIEGOS', f: ['Cantabria', 'Mantequilla pura', 'Papel doblado', 'Bizcocho cuadrado'] },
    { w: 'QUESADA PASIEGA', f: ['Cantabria', 'Leche cuajada', 'Canela y limón', 'Horno'] },
    { w: 'ENSAYMADA', f: ['Mallorca', 'Espiral', 'Azúcar glas', 'Manteca de cerdo'] },
    { w: 'FARTONS', f: ['Bollos alargados', 'Mojar en horchata', 'Glaseado de azúcar', 'Valencia'] },
    { w: 'BATIDO DE FRESA', f: ['Leche rosa', 'Pajita', 'Fruta', 'Dulce'] }
  ],
  objects: [
    { w: 'GOMAELÁSTICA', f: ['Tirar', 'Sujetar billetes', 'Estirar', 'Goma'] },
    { w: 'CHINCHETA DE COLORES', f: ['Corcho', 'Avisos', 'Pinchar', 'Pared'] },
    { w: 'POST-IT / NOTA ADHESIVA', f: ['Papel amarillo', 'Pegar en pantalla', 'Recordatorio', 'Despegar'] },
    { w: 'SUBRAYADOR FLUORESCENTE', f: ['Tinta amarilla chillona', 'Apuntes', 'Resaltar texto', 'Estudiar'] },
    { w: 'TÍPEX / CORRECTOR LÍQUIDO', f: ['Bote blanco', 'Tapar falta', 'Cinta blanca', 'Borrar boli'] },
    { w: 'PORTAMINAS', f: ['Minas finas', 'Pulsar botón', 'Lápiz mecánico', 'Dibujar'] },
    { w: 'ROTULADOR PERMANENTE', f: ['Olor fuerte', 'No se borra', 'Negro', 'Escribir en plástico'] },
    { w: 'BRÚJULA DE SENDERISMO', f: ['Aguja magnética', 'Norte', 'Mapa', 'Perderse'] },
    { w: 'CANICAS', f: ['Bolas de cristal', 'Jugar en el suelo', 'Chocar', 'Colores dentro'] },
    { w: 'DADO DE SEIS CARAS', f: ['Puntos del uno al seis', 'Tirar', 'Juego de mesa', 'Azar'] },
    { w: 'FICHAS DE PARCHÍS', f: ['Cuatro colores', 'Comer y contar veinte', 'Casillas', 'Tablero'] },
    { w: 'BARAJA DE CARTAS', f: ['Repartir', 'Mezclar', 'Tapete', 'Barajar'] },
    { w: 'DEDAL DE COSTURA', f: ['Proteger dedo', 'Aguja', 'Metal con hoyitos', 'Coser'] },
    { w: 'IMÁN DE NEVERA', f: ['Pegar fotos', 'Souvenir de viaje', 'Metal', 'Atracción'] },
    { w: 'ABANICO', f: ['Darse aire', 'Calor', 'Varillas', 'Plegar'] },
    { w: 'BOTIQUÍN', f: ['Tiritas', 'Alcohol', 'Algodón', 'Primeros auxilios'] },
    { w: 'TIRITA', f: ['Herida', 'Corte en el dedo', 'Pegar', 'Sangre'] },
    { w: 'GASAS ESTÉRILES', f: ['Heridas', 'Blanco', 'Venda', 'Botiquín'] },
    { w: 'TENSIÓMETRO', f: ['Presión arterial', 'Brazo inflable', 'Médico', 'Pulsaciones'] },
    { w: 'TERMÓMETRO DIGITAL', f: ['Fiebre', 'Pitido', 'Temperatura', 'Grados'] },
    { w: 'PASTILLERO SEMANAL', f: ['Lunes a domingo', 'Compartimentos', 'Medicamentos', 'Abuelos'] },
    { w: 'LIMA DE UÑAS', f: ['Papel de lija', 'Manicura', 'Raspar', 'Borde'] },
    { w: 'CORTAÚÑAS', f: ['Palanca', 'Filo curvo', 'Pedicura', 'Cortar'] },
    { w: 'PINZAS DE DEPILAR', f: ['Pelos de las cejas', 'Tirar', 'Metal', 'Puntas finas'] },
    { w: 'ESPEJO DE BOLSILLO', f: ['Maquillaje', 'Abrir tapa', 'Mirarse los dientes', 'Pequeño'] },
    { w: 'PEINE DE PÚAS', f: ['Desenredar pelo', 'Raya al medio', 'Plástico', 'Cabello'] },
    { w: 'CEPILLO DEL PELO', f: ['Cerdas', 'Melena', 'Peinarse', 'Mango'] },
    { w: 'GOMA DEL PELO / COLETERO', f: ['Recogerse el pelo', 'Coleta', 'Muñeca', 'Moño'] },
    { w: 'HORQUILLA', f: ['Sujetar mechón', 'Metal negro', 'Pelo', 'Peinado'] },
    { w: 'PASADOR DE PELO', f: ['Clip', 'Adorno', 'Melena', 'Cerrar'] },
    { w: 'ESPONJA DE BAÑO', f: ['Enjabonarse', 'Agua y jabón', 'Frotar cuerpo', 'Ducha'] },
    { w: 'TOALLA DE PLAYA', f: ['Tumbarse en la arena', 'Secarse', 'Grande y colorida', 'Sol'] },
    { w: 'SOM sombrilla de playa', f: ['Sombra', 'Clavar en la arena', 'Viento vuela', 'Verano'] },
    { w: 'NEVERA PORTÁTIL', f: ['Plástico azul', 'Hielo / acumuladores', 'Bebidas frías', 'Playa'] },
    { w: 'CANTIMPLORA', f: ['Agua de excursión', 'Funda de tela', 'Tapón con cadenita', 'Beber'] },
    { w: 'NAVAJA SUIZA', f: ['Multiusos', 'Roja con cruz', 'Tijeras y lima', 'Acampada'] }
  ],
  places: [
    { w: 'MIRADOR DE LA MONTAÑA', f: ['Vistas panorámicas', 'Barandilla', 'Fotografías', 'Altura'] },
    { w: 'FARO EN EL ACANTILADO', f: ['Luz marina', 'Torre alta', 'Rocas', 'Guiar barcos'] },
    { w: 'EMBALSE / PANTANO', f: ['Presa de hormigón', 'Agua dulce', 'Sequía', 'Río retenido'] },
    { w: 'REFUGIO DE MONTAÑA', f: ['Dormir excursionistas', 'Camas de literas', 'Chimenea', 'Cumbres'] },
    { w: 'MERENDERO CON MESAS DE PIEDRA', f: ['Comer al aire libre', 'Sombras de árboles', 'Tortilla', 'Parque'] },
    { w: 'CHIRINGUITO DE PLAYA', f: ['Sardinas al espeto', 'Caña fría', 'Pies en la arena', 'Música verano'] },
    { w: 'PASEO MARÍTIMO', f: ['Caminar junto al mar', 'Puestos de pulseras', 'Palmeras', 'Bicicletas'] },
    { w: 'PUERTO DEPORTIVO', f: ['Yates y veleros', 'Pantalanes', 'Club náutico', 'Marineros'] },
    { w: 'PEAJE DE AUTOPISTA', f: ['Barrera', 'Ticket', 'Pagar telepeaje', 'Cabina'] },
    { w: 'ÁREA DE SERVICIO', f: ['Gasolinera', 'Café caro', 'Baños limpios', 'Camioneros'] },
    { w: 'TALLER MECÁNICO', f: ['Elevador de coches', 'Manchas de grasa', 'Herramientas', 'Arreglar'] },
    { w: 'ITV / INSPECCIÓN TÉCNICA', f: ['Revisión del coche', 'Pegatina en cristal', 'Frenos', 'Gases'] },
    { w: 'DESGUACE DE COCHES', f: ['Piezas de repuesto', 'Coches apilados', 'Chatarra', 'Grúa'] },
    { w: 'LAVADERO DE COCHES', f: ['Túnel de rodillos', 'Espuma activa', 'Monedas de un euro', 'Secado'] },
    { w: 'PARKING SUBTERRÁNEO', f: ['Plazas estrechas', 'Columna de cemento', 'Ticket y cajero', 'Bajo tierra'] },
    { w: 'VIVERO DE PLANTAS', f: ['Invernadero', 'Macetas', 'Tierra abonada', 'Flores para comprar'] },
    { w: 'FERRETERÍA DE BARRIO', f: ['Tornillos sueltos', 'Copias de llaves', 'Pinturas', 'Herramientas'] },
    { w: 'QUIOSCO DE PRENSA', f: ['Periódicos', 'Revistas', 'Chuches', 'Cromos'] },
    { w: 'ESTANCO', f: ['Letrero marrón y amarillo', 'Tabaco', 'Sellos', 'Timbre del estado'] },
    { w: 'LOTERÍAS Y APUESTAS', f: ['Comprobar boleto', 'Primitiva', 'Décimos en ventanilla', 'Suerte'] }
  ],
  professions: [
    { w: 'PEDIATRA', f: ['Médico de niños', 'Vacunas', 'Palito en la lengua', 'Crecimiento'] },
    { w: 'CARDIÓLOGO', f: ['Corazón', 'Electrocardiograma', 'Tensión', 'Latidos'] },
    { w: 'TRAUMATÓLOGO', f: ['Huesos rotos', 'Escayolas', 'Radiografías', 'Esguinces'] },
    { w: 'DERMATÓLOGO', f: ['Piel', 'Lunares', 'Granos', 'Cremas'] },
    { w: 'OFTALMÓLOGO / OCULISTA', f: ['Graduar la vista', 'Fondo de ojo', 'Lentillas', 'Gafas'] },
    { w: 'ANESTESISTA', f: ['Dormir antes de operar', 'Gas', 'Quirófano', 'Dolor cero'] },
    { w: 'PODÓLOGO', f: ['Pies', 'Plantillas', 'Uñas encarnadas', 'Durezas'] },
    { w: 'NUTRICIONISTA', f: ['Dieta', 'Bajar de peso', 'Calorías', 'Comer sano'] },
    { w: 'AUXILIAR DE ENFERMERÍA', f: ['Cuidar enfermos', 'Medir tensión', 'Camas de hospital', 'Ayudar'] },
    { w: 'CELADOR DE HOSPITAL', f: ['Empujar camillas', 'Sillas de ruedas', 'Trasladar pacientes', 'Pasillos'] },
    { w: 'NOTARIO', f: ['Firmar escrituras', 'Dar fe pública', 'Comprar piso', 'Sello oficial'] },
    { w: 'CONTABLE / ASESOR FISCAL', f: ['Declaración de la renta', 'Facturas', 'Impuestos', 'Hacienda'] },
    { w: 'GESTOR INMOBILIARIO', f: ['Vender pisos', 'Alquiler', 'Comisión', 'Enseñar casa'] },
    { w: 'DIRECTOR DE BANCO', f: ['Hipotecas', 'Préstamos', 'Despacho', 'Dinero'] },
    { w: 'CAJERO DE SUPERMERCADO', f: ['Pisar código de barras', 'Cobrar', 'Dar cambio', 'Bolsas'] },
    { w: 'REPONEDOR DE TIENDA', f: ['Colocar cajas', 'Estanterías', 'Pasillos de noche', 'Palés'] },
    { w: 'REPARTIDOR DE AMAZON', f: ['Furgoneta blanca', 'Paquetes de cartón', 'Timbrar al telefonillo', 'Firma'] },
    { w: 'MENSAJERO EN MOTO', f: ['Mochila cuadrada', 'Glovo / Uber', 'Repartir comida', 'Tráfico'] },
    { w: 'CONDUCTOR DE METRO', f: ['Cabina delantera', 'Abrir y cerrar puertas', 'Túnel oscuro', 'Vía'] },
    { w: 'CONTROLADOR AÉREO', f: ['Torre del aeropuerto', 'Radares', 'Pistas de aterrizaje', 'Estrés'] }
  ],
  sports: [
    { w: 'LANZAMIENTO DE JABALINA', f: ['Lanza puntiaguda', 'Tirar lejos', 'Pista de atletismo', 'Brazo'] },
    { w: 'LANZAMIENTO DE PESO', f: ['Bola de hierro pesada', 'Cuello', 'Círculo de lanzamiento', 'Fuerza'] },
    { w: 'SALTO DE ALTURA', f: ['Listón', 'Colchoneta grande', 'Espalda', 'Fosbury flop'] },
    { w: 'SALTO CON PÉRTIGA', f: ['Barra flexible', 'Clavar y subir', 'Listón muy alto', 'Caer en colchoneta'] },
    { w: 'SALTO DE LONGITUD', f: ['Correr y saltar', 'Foso de arena', 'Tabla de batida', 'Medir metros'] },
    { w: 'CARRERA DE RELEVOS', f: ['Testigo / tubo', 'Pasar de mano en mano', 'Cuatro atletas', 'Pista'] },
    { w: 'MARATÓN', f: ['Cuarenta y dos kilómetros', 'Correr por ciudad', 'Muro del kilómetro 30', 'Meta'] },
    { w: 'CARRERA DE VALLAS', f: ['Saltar obstáculos', 'Tirar valla', 'Velocidad en pista', 'Piernas'] },
    { w: 'SALTO DE TRAMPOLÍN', f: ['Piscina profunda', 'Pirueta en el aire', 'Plataforma de diez metros', 'Entrar al agua'] },
    { w: 'NATACIÓN SINCRONIZADA', f: ['Música bajo el agua', 'Pinza en la nariz', 'Figuras con las piernas', 'Maquillaje resistente'] },
    { w: 'HOCKEY SOBRE HIERBA', f: ['Stick curvado', 'Bola dura', 'Protector bucal', 'Porterías'] },
    { w: 'HOCKEY SOBRE HIELO', f: ['Puck / pastilla negra', 'Patinar en hielo', 'Peleas con guantes', 'Casco con rejilla'] },
    { w: 'CURLED / CURLING', f: ['Piedras de granito', 'Barrer el hielo con escobas', 'Diana circular', 'Invierno'] },
    { w: 'BOBSLEIGH', f: ['Trineo cerrado', 'Túnel de hielo', 'Curvas a gran velocidad', 'Empujar al inicio'] },
    { w: 'TIRO AL PLATO', f: ['Escopeta', 'Plato naranja volando', 'Disparar al aire', 'Puntería'] },
    { w: 'KICKBOXING', f: ['Puñetazos y patadas', 'Ring', 'Guantes y espinilleras', 'Combate'] },
    { w: 'LUCHA LIBRE / WWE', f: ['Cuadrilátero', 'Golpes simulados', 'Cinturón de campeón', 'Personajes'] },
    { w: 'MOTOCROSS', f: ['Motos de campo', 'Saltos en barro', 'Circuito de tierra', 'Casco con gafas'] },
    { w: 'RALLY', f: ['Copiloto con notas', 'Curva a ras', 'Caminos de tierra o nieve', 'Derrapar'] },
    { w: 'KARTING', f: ['Mini coches', 'Circuito cerrado', 'Volante duro', 'Cumpleaños con amigos'] }
  ],
  actions: [
    { w: 'BRINDAR CON COPAS', f: ['Chin chin', 'Arriba abajo al centro', 'Celebrar', 'Mirarse a los ojos'] },
    { w: 'CHUPARSE LOS DEDOS', f: ['Comida rica', 'Salsa', 'Servilleta', 'Gesto'] },
    { w: 'SONARSE LOS MOCOS', f: ['Pañuelo de papel', 'Soplar fuerte', 'Nariz tapada', 'Resfriado'] },
    { w: 'HACER GÁRGARAS', f: ['Agua con sal', 'Mirar al techo', 'Garganta', 'Burbujas en la boca'] },
    { w: 'TRAGAR PASTILLAS', f: ['Vaso de agua', 'Medicamento', 'Garganta', 'No atragantarse'] },
    { w: 'ECHARSE LA SIESTA', f: ['Sofá con manta', 'Veinte minutos', 'Después de comer', 'Cerrar los ojos'] },
    { w: 'HACERSE UN MOÑO', f: ['Goma de pelo', 'Enroscar cabello', 'Rápido en casa', 'Calor'] },
    { w: 'PINTARSE LAS UÑAS', f: ['Esmalte de color', 'Pincelito fino', 'Soplar para secar', 'Olor a acetona'] },
    { w: 'DEPILARSE LAS PIERNAS', f: ['Cera caliente', 'Tirón de papel', 'Dolor rápido', 'Piel suave'] },
    { w: 'AFEITARSE LA BARBA', f: ['Cuchilla', 'Espuma blanca', 'Espejo empañado', 'Aftershave'] },
    { w: 'ECHÁRSE COLONIA', f: ['Pulverizar en el cuello', 'Muñecas', 'Frasco de cristal', 'Buen olor'] },
    { w: 'PELAR PATATAS', f: ['Pelador o cuchillo', 'Quitar la piel', 'Olla con agua', 'Freír'] },
    { w: 'CORTAR CEBOLLA', f: ['Llorar en la cocina', 'Picar fino', 'Tabla de madera', 'Picor de ojos'] },
    { w: 'BATIR HUEVOS', f: ['Tenedor en plato hondo', 'Hacer tortilla', 'Clara y yema juntas', 'Espuma'] },
    { w: 'EXPRIMIR UN LIMÓN', f: ['Hacer zumo ácido', 'Mitad de la fruta', 'Apretar con fuerza', 'Pepitas'] },
    { w: 'ABRIR UNA LATA', f: ['Tirar de la anilla', 'Abrelatas', 'Atún o berberechos', 'Cuidado con el filo'] },
    { w: 'DESTAPAR UNA BOTELLA DE VINO', f: ['Sacacorchos en espiral', 'Tirar del corcho', 'Ruido pop', 'Botella'] },
    { w: 'TIRAR LA BASURA', f: ['Bajar en ascensor', 'Bolsa atada', 'Contenedor de la calle', 'Noche'] },
    { w: 'TENDER LA ROPA', f: ['Pinzas de colores', 'Cuerda en la terraza', 'Sacar de la lavadora', 'Secar al sol'] },
    { w: 'PASAR LA FREGONA', f: ['Escurrir el mocho en el cubo', 'Suelo mojado resbala', 'Olor a lejía', 'Caminar de espaldas'] }
  ],
  nature: [
    { w: 'MAREA ALTA', f: ['El agua sube', 'Cubre las toallas', 'Luna y gravedad', 'Playa estrecha'] },
    { w: 'MAREA BAJA', f: ['El mar se retira', 'Cangrejos al descubierto', 'Charcos entre rocas', 'Caminar lejos'] },
    { w: 'RESACA MARINA', f: ['Corriente que arrastra hacia dentro', 'Peligro bandera roja', 'Olas', 'Socorrista'] },
    { w: 'ROMPIENTE DE OLAS', f: ['Espuma blanca', 'Chocar contra rocas', 'Sonido del mar', 'Playa'] },
    { w: 'AGUA CRISTALINA', f: ['Ver el fondo', 'Peces nadando', 'Cala mediterránea', 'Transparente'] },
    { w: 'MANANTIAL DE AGUA', f: ['Nacer de las rocas', 'Agua pura de montaña', 'Beber fresco', 'Fuente natural'] },
    { w: 'POZA NATURAL', f: ['Bañarse en el río', 'Piedras redondas', 'Agua helada de verano', 'Cascada'] },
    { w: 'BARRANCO PROFUNDO', f: ['Cañón entre montañas', 'Eco al gritar', 'Paredes verticales', 'Vértigo'] },
    { w: 'DESFILADERO ESTRECHO', f: ['Paso entre rocas altas', 'Río al fondo', 'Carretera de curvas', 'Sombra'] },
    { w: 'VALLE VERDE', f: ['Entre dos montañas', 'Prados con vacas', 'Pueblo al fondo', 'Río cruzando'] },
    { w: 'MESETA CASTELLANA', f: ['Llanura infinita', 'Campos de trigo', 'Horizonte recto', 'Secano'] },
    { w: 'DEHESA DE ENCINAS', f: ['Cerdos ibéricos comiendo bellotas', 'Árboles dispersos', 'Pasto', 'Extremadura'] },
    { w: 'HAYEDO EN OTOÑO', f: ['Hojas doradas en el suelo', 'Árboles altos', 'Niebla matinal', 'Sombra fresca'] },
    { w: 'ALCORNOCAL', f: ['Corteza de corcho', 'Quitar la piel al árbol', 'Tronco rojizo', 'Mediterráneo'] },
    { w: 'OLIVAR ANDALUZ', f: ['Filas interminables de olivos', 'Aceitunas para molino', 'Tierra roja', 'Jaén'] },
    { w: 'VIÑEDO DE UVA', f: ['Cepas y racimos', 'Vendimia en septiembre', 'Bodegas de vino', 'Rioja'] },
    { w: 'CAMPO DE GIRASOLES', f: ['Cabezas amarillas mirando al sol', 'Pipas', 'Verano en Castilla', 'Fotografía'] },
    { w: 'CAMPO DE LAVANDA', f: ['Flores moradas aromáticas', 'Brihuega', 'Abejas zumbando', 'Perfume'] },
    { w: 'SALINAS MARINAS', f: ['Montañas de sal blanca', 'Agua rosa con flamencos', 'Evaporación', 'Costa'] },
    { w: 'CANDILAZO AL ATARDECER', f: ['Cielo rojo y naranja', 'Nubes iluminadas por abajo', 'Puesta de sol', 'Foto'] }
  ],
  moviesTv: [
    { w: 'EL PADRINO', f: ['Marlon Brando', 'Oferta que no podrá rechazar', 'Cabeza de caballo', 'Mafia italiana'] },
    { w: 'PULP FICTION', f: ['Hamburguesa Big Kahuna', 'Baile de Travolta y Thurman', 'Maletín brillante', 'Tarantino'] },
    { w: 'FORREST GUMP', f: ['Corre Forrest', 'Caja de bombones', 'Pluma flotando', 'Banco del parque'] },
    { w: 'GLADIATOR', f: ['Máximo Décimo Meridio', 'Mi nombre es Gladiador', 'Coliseo', 'Fuerza y honor'] },
    { w: 'BRAVEHEART', f: ['¡Libertad!', 'Cara pintada de azul', 'Falda escocesa', 'Mel Gibson'] },
    { w: 'CASABLANCA', f: ['Tócala otra vez Sam', 'Aeropuerto con niebla', 'Siempre nos quedará París', 'Blanco y negro'] },
    { w: 'PSICOSIS', f: ['Ducha con cortina', 'Cuchillo y música chirriante', 'Madre de Norman Bates', 'Motel'] },
    { w: 'EL RESPLANDOR', f: ['¡Aquí está Jack!', 'Hacha rompiendo puerta', 'Hotel nevado', 'Gemelas en el pasillo'] },
    { w: 'TIBURÓN (PELÍCULA)', f: ['Música de dos notas', 'Playa cerrada', 'Necesitamos un barco más grande', 'Spielberg'] },
    { w: 'E.T. EL EXTRATERRESTRE', f: ['Dedo con luz', 'Bicicleta volando ante la luna', 'Mi casa teléfono', 'Cesta'] },
    { w: 'PARQUE JURÁSICO', f: ['Vaso de agua vibrando', 'T-Rex rugiendo bajo la lluvia', 'Parque con valla eléctrica', 'Ámbar con mosquito'] },
    { w: 'REGRESO AL FUTURO', f: ['Ochenta y ocho millas por hora', 'Condensador de fluzo', 'Monopatín volador', 'Rayo en el reloj'] },
    { w: 'CAZAFANTASMAS', f: ['Moco verde', 'Hombre de malvavisco gigante', 'A quién vas a llamar', 'Rayo de protones'] },
    { w: 'LOS GOONIES', f: ['Mapa del tesoro pirata', 'Sloth chocolate', 'Bicicletas de niños', 'Cueva trampa'] },
    { w: 'GREMLINS', f: ['No mojar después de medianoche', 'Mogwai Gizmo', 'No darles de comer', 'Bichos malos'] },
    { w: 'SOLO EN CASA / MI POBRE ANGELITO', f: ['Trampas en casa', 'Ladrones tontos', 'Se olvidan del niño', 'Navidad'] },
    { w: 'LA HISTORIA INTERMINABLE', f: ['Fújur el dragón blanco', 'Ártax en el pantano', 'Auryn', 'Atreyu'] },
    { w: 'PESADILLA ANTES DE NAVIDAD', f: ['Jack Skellington', 'Rey de Halloween', 'Muñecos de plastilina', 'Tim Burton'] },
    { w: 'COCO (PIXAR)', f: ['Recuérdame', 'Tierra de los muertos', 'Guitarra blanca de calavera', 'Día de muertos en México'] },
    { w: 'ENCANTO (DISNEY)', f: ['No se habla de Bruno', 'Familia Madrigal con dones', 'Casita mágica', 'Colombia'] }
  ],
  videogames: [
    { w: 'HALF-LIFE', f: ['Gordon Freeman', 'Palanca de hierro', 'Científico mudo', 'Black Mesa'] },
    { w: 'COUNTER-STRIKE', f: ['Terroristas y antiterroristas', 'Bomba plantada en B', 'Dust II', 'AWP'] },
    { w: 'DOTA 2', f: ['Torneo The International', 'Ancestro destruido', 'Valve', 'MOBA'] },
    { w: 'WORLD OF WARCRAFT', f: ['Horda y Alianza', 'Orco contra humano', 'Incursión / Raid', 'Azeroth'] },
    { w: 'DIABLO', f: ['Clic para matar monstruos', 'Mazmorras oscuras', 'Piedra de alma', 'Botín legendario'] },
    { w: 'STARCRAFT', f: ['Terran Zerg y Protoss', 'Estrategia en tiempo real', 'Minerales y gas vespeno', 'Corea'] },
    { w: 'AGE OF EMPIRES', f: ['Aldeanos talando madera', 'Pasar de edad', 'Wololo del sacerdote', 'Estrategia'] },
    { w: 'CIVILIZATION', f: ['Un turno más', 'Construir maravillas', 'Diplomacia y guerra', 'Gandhi con bombas nucleares'] },
    { w: 'THE WITCHER', f: ['Geralt de Rivia', 'Espada de plata para monstruos', 'Pelo blanco', 'Sardinilla el caballo'] },
    { w: 'CYBERPUNK 2077', f: ['Night City', 'Implantes en el cuerpo', 'Keanu Reeves', 'Futuro distópico'] },
    { w: 'FALLOUT', f: ['Refugio nuclear / Vault', 'Pip-Boy en la muñeca', 'Yermo postapocalíptico', 'Chapas como moneda'] },
    { w: 'BIOSHOCK', f: ['Ciudad submarina Rapture', 'Big Daddy con taladro', 'Little Sister', 'Plásmidos'] },
    { w: 'MASS EFFECT', f: ['Comandante Shepard', 'Nave Normandía', 'Viajes entre galaxias', 'Segadores'] },
    { w: 'METAL GEAR SOLID', f: ['Solid Snake', 'Esconderse en caja de cartón', 'Signo de exclamación en la cabeza', 'Sigilo'] },
    { w: 'FINAL FANTASY', f: ['Chocobo amarillo', 'Espada gigante de Cloud', 'Invocaciones de monstruos', 'Turnos y magia'] },
    { w: 'KINGDOM HEARTS', f: ['Llave espada', 'Personajes de Disney con anime', 'Sora', 'Corazones'] },
    { w: 'PERSONA 5', f: ['Ladrones fantasma', 'Mascara de Joker', 'Colegio de día y metaverso de noche', 'Música jazz'] },
    { w: 'MONSTER HUNTER', f: ['Cazar dragones gigantes', 'Armas enormes hechas de escamas', 'Cocinar carne en hoguera', 'Gatos compañeros'] },
    { w: 'HOLLOW KNIGHT', f: ['Bicho con capa y aguja', 'Subterráneo oscuro de Hallownest', 'Metroidvania difícil', 'Almas'] },
    { w: 'DEAD CELLS', f: ['Morir y volver a empezar', 'Castillo de mazmorras', 'Rollo píxel art', 'Rogue-like'] }
  ],
  characters: [
    { w: 'LOBEZNO / WOLVERINE', f: ['Garras retráctiles de adamantium', 'Mutante con patillas', 'Factor de curación', 'X-Men'] },
    { w: 'DEADPOOL', f: ['Traje rojo y negro', 'Romper la cuarta pared', 'Espadas a la espalda', 'Chistes groseros'] },
    { w: 'MAGNETO', f: ['Casco para evitar telepatía', 'Controlar metales', 'Villano de X-Men', 'Capa morada'] },
    { w: 'PROFESOR X / XAVIER', f: ['Silla de ruedas futurista', 'Calvo y telépata', 'Escuela de mutantes', 'Cerebro'] },
    { w: 'FLASH', f: ['Corredor más rápido del mundo', 'Rayo amarillo en el pecho', 'Traje rojo ceñido', 'Fuerza de la velocidad'] },
    { w: 'AQUAMAN', f: ['Hablar con los peces', 'Tridente dorado', 'Rey de Atlantis', 'Héroe del océano'] },
    { w: 'LINTERNA VERDE', f: ['Anillo que crea cosas con luz', 'Fuerza de voluntad', 'Juramento en el día más brillante', 'Verde'] },
    { w: 'THANOS', f: ['Chasquido de dedos', 'Guantelete del infinito', 'Piel morada y barbilla estriada', 'Mitad del universo'] },
    { w: 'LOKI', f: ['Dios del engaño', 'Cuernos dorados', 'Hermano adoptivo de Thor', 'Magia verde'] },
    { w: 'GROOT', f: ['Yo soy Groot', 'Árbol que habla', 'Guardián de la galaxia', 'Rocket el mapache'] },
    { w: 'ROCKET RACCOON', f: ['Mapache con armas gigantes', 'Compañero de Groot', 'Guardián del espacio', 'Malsonante'] },
    { w: 'STAR-LORD', f: ['Walkman con cinta de casete', 'Chaqueta de cuero roja', 'Máscara con ojos rojos', 'Peter Quill'] },
    { w: 'CAPITANA MARVEL', f: ['Volante cósmico de energía', 'Estrella en el pecho', 'Traje azul y rojo', 'Carol Danvers'] },
    { w: 'OJO DE HALCÓN / HAWKEYE', f: ['Arco y flechas trucadas', 'Nunca falla un tiro', 'Vengador sin poderes', 'Carcaj'] },
    { w: 'VIUDA NEGRA / BLACK WIDOW', f: ['Espía rusa de traje negro', 'Pelo pelirrojo', 'Vengadora ágil', 'Natasha Romanoff'] },
    { w: 'DOCTOR STRANGE', f: ['Capa de levitación roja', 'Ojo de Agamotto en el cuello', 'Hechicero supremo', 'Portales dorados'] },
    { w: 'PANTERA NEGRA / BLACK PANTHER', f: ['Wakanda por siempre', 'Garras de vibranium', 'Rey T\'Challa', 'Traje de gato negro'] },
    { w: 'VISION', f: ['Gema de la mente en la frente', 'Cuerpo de androide', 'Amor de Bruja Escarlata', 'Capa amarilla'] },
    { w: 'BRUJA ESCARLATA', f: ['Magia del caos roja', 'Wanda Maximoff', 'Realidad alterada', 'Corona en la frente'] },
    { w: 'SOLDADO DE INVIERNO', f: ['Brazo de metal con estrella roja', 'Bucky Barnes', 'Amigo del Capitán América', 'Lavado de cerebro'] }
  ],
  technology: [
    { w: 'CABLE ETHERNET', f: ['Conector RJ45 de plástico', 'Internet por cable fijo', 'Router al ordenador', 'Pestaña'] },
    { w: 'TARJETA MICROSD', f: ['Memoria diminuta', 'Móvil o Nintendo Switch', 'Adaptador a tamaño grande', 'Gigas'] },
    { w: 'DISCO SSD', f: ['Disco sólido sin partes mecánicas', 'Arranque rápido de Windows', 'Silencioso', 'Almacenamiento'] },
    { w: 'VENTILADOR DE CPU', f: ['Disipador de calor de aluminio', 'Pasta térmica', 'Enfriar el procesador', 'Girar rápido'] },
    { w: 'FUENTE DE ALIMENTACIÓN', f: ['Caja de cables dentro del PC', 'Enchufe a la pared', 'Vatios de potencia', 'Interruptor'] },
    { w: 'REGLETA CON INTERRUPTOR', f: ['Muchos enchufes en fila', 'Botón rojo con luz', 'Conectar varios cables', 'Suelo'] },
    { w: 'ADAPTADOR DE ENCHUFE', f: ['Viajar a Inglaterra o USA', 'Tres clavijas cuadradas', 'Conversor de corriente', 'Maleta'] },
    { w: 'PUNTERO LÁSER', f: ['Punto rojo en la pared', 'Jugar con el gato', 'Presentaciones de diapositivas', 'Pilas de botón'] },
    { w: 'PANTALLA DE TINTA ELECTRÓNICA', f: ['Lector de libros Kindle', 'No cansa la vista', 'Blanco y negro sin reflejos', 'Batería de semanas'] },
    { w: 'PULSERA DE ACTIVIDAD', f: ['Contar diez mil pasos al día', 'Medir el sueño', 'Pantalla estrecha de goma', 'Alarma que vibra'] },
    { w: 'AURICULARES DE BOTÓN INALÁMBRICOS', f: ['Estuche que se carga', 'Sin cables a las orejas', 'Cancelación de ruido', 'AirPods'] },
    { w: 'AURICULARES DE DIADEMA', f: ['Almohadillas grandes en las orejas', 'Arco sobre la cabeza', 'Aislar del ruido', 'Gamers'] },
    { w: 'MICRÓFONO DE CONDENSADOR', f: ['Filtro antipop redondo', 'Streamers y podcasters', 'Brazo articulado en mesa', 'Voz clara'] },
    { w: 'ARO DE LUZ LED', f: ['Círculo blanco brillante', 'Grabar vídeos de TikTok', 'Móvil en el centro', 'Iluminación facial'] },
    { w: 'PANTALLA VERDE / CROMA', f: ['Tela de fondo para recortar', 'Poner fondos digitales', 'Efectos especiales de cine', 'Verde brillante'] },
    { w: 'PALO SELFIE', f: ['Brazo extensible de metal', 'Sujetar móvil lejos', 'Foto de grupo', 'Botón en el mango'] },
    { w: 'ESTABILIZADOR GIMBAL', f: ['Motores que nivelan el móvil', 'Vídeo suave sin temblores', 'Mango para caminar grabando', 'Cámara fluida'] },
    { w: 'DISCO DURO EXTERNO', f: ['Copia de seguridad', 'Cable USB', 'Guardar películas y fotos', 'Luz azul parpadeante'] },
    { w: 'ALFOMBRILLA DE RATÓN GIGANTE', f: ['Cubre todo el escritorio', 'Teclado y ratón encima', 'Bordes cosidos con luces', 'Deslizar suave'] },
    { w: 'SILLA GAMING', f: ['Forma de asiento de coche de carreras', 'Cojines lumbar y cervical', 'Ruedas y reposabrazos', 'Colores llamativos'] }
  ],
  transport: [
    { w: 'PATINES EN LÍNEA', f: ['Cuatro ruedas seguidas', 'Freno en el talón', 'Rodilleras y casco', 'Patinar por aceras'] },
    { w: 'PATINES DE CUATRO RUEDAS', f: ['Dos ruedas delante y dos detrás', 'Patinaje artístico', 'Taco de goma delante', 'Retro'] },
    { w: 'MONOCICLO', f: ['Una sola rueda', 'Pedales sin manillar', 'Equilibrio de circo', 'Sillín alto'] },
    { w: 'TÁNDEM', f: ['Bicicleta para dos personas', 'Dos sillines y dos manillares', 'Pedalear a la vez', 'Paseo en pareja'] },
    { w: 'TRICICLO DE NIÑO', f: ['Tres ruedas de plástico', 'Pedal en la rueda delantera', 'Palo para que empuje la madre', 'Bocina'] },
    { w: 'BICICLETA PLEGABLE', f: ['Bisagra en el cuadro', 'Ruedas pequeñas', 'Meter en el tren o maletero', 'Ciudad'] },
    { w: 'BICICLETA DE MONTAÑA', f: ['Ruedas gordas con tacos', 'Suspensión delantera', 'Caminos de tierra y piedras', 'Muchos piñones'] },
    { w: 'BICICLETA DE CARRETERA', f: ['Ruedas muy finas', 'Manillar curvado hacia abajo', 'Maillot pegado', 'Velocidad en asfalto'] },
    { w: 'QUAD / CUATRIMOTO', f: ['Cuatro ruedas de taco grande', 'Manillar de moto', 'Tierra y caminos rurales', 'Casco integral'] },
    { w: 'MOTO DE AGUA', f: ['Saltar olas a toda velocidad', 'Sin ruedas en el mar', 'Manillar y acelerador de gatillo', 'Chaleco salvavidas'] },
    { w: 'HIDROPEDAL CON TOBOGÁN', f: ['Pedalear en la playa', 'Flotadores gigantes de fibra', 'Tirarse al agua de espaldas', 'Alquilar una hora'] },
    { w: 'PADDLE SURF', f: ['Tabla ancha inflable', 'Remo largo de pie', 'Mar en calma', 'Equilibrio'] },
    { w: 'WAKEBOARD', f: ['Tabla agarrada a los pies', 'Cuerda tirada por lancha rápida', 'Hacer saltos sobre la estela', 'Neopreno'] },
    { w: 'CATAMARÁN', f: ['Barco con dos cascos paralelos', 'Red en medio para tumbarse', 'Vela grande', 'Estable en el agua'] },
    { w: 'FERRY DE COCHES', f: ['Rampa gigante en popa', 'Meter el coche en la bodega', 'Cruzar a las islas', 'Cubierta para pasajeros'] },
    { w: 'REMOLCADOR', f: ['Barco pequeño con mucha fuerza', 'Maniobrar barcos gigantes en puerto', 'Defensas de ruedas negras', 'Humo'] },
    { w: 'GÓNDOLA DE ESQUÍ', f: ['Cabina cerrada colgada de cable', 'Meter esquís en ranura exterior', 'Subir a la cumbre nevada', 'Vistas'] },
    { w: 'SILLAS DE TELESILLA', f: ['Barra de seguridad bajada', 'Pies colgando sobre la nieve', 'Esquís puestos', 'Subir a pistas'] },
    { w: 'CARRO DE CABALLOS', f: ['Tirar por fuerza animal', 'Ruedas grandes de madera', 'Paseo turístico en Sevilla', 'Cascabeles'] },
    { w: 'COCHE ELÉCTRICO', f: ['Cargar en poste con enchufe', 'Silencioso como un fantasma', 'Batería en el suelo', 'Pegatina cero emisiones'] }
  ],
  home: [
    { w: 'MANDO DEL AIRE ACONDICIONADO', f: ['Pantalla con grados', 'Botón de frío o calor', 'Pilas gastadas', 'Modo noche silencioso'] },
    { w: 'ESTUFA DE BUTANO', f: ['Bombona naranja con regulador', 'Llama azul por rejilla', 'Ruedas para moverla', 'Olor a gas'] },
    { w: 'RADIADOR DE ACEITE', f: ['Elementos de metal calientes', 'Ruedas pequeñas', 'Enchufe a pared', 'Calefacción portátil'] },
    { w: 'VENTILADOR DE TECHO', f: ['Aspas de madera girando', 'Luz en el centro', 'Cadena para regular velocidad', 'Dormir con brisa'] },
    { w: 'HUMIDIFICADOR DE AMBIENTE', f: ['Vapor frío de agua', 'Gotas de esencia perfumada', 'Luces de colores suaves', 'Aire seco'] },
    { w: 'DESHUMIDIFICADOR', f: ['Depósito de agua que se llena', 'Quitar humedad de la habitación', 'Evitar moho en paredes', 'Ruido de compresor'] },
    { w: 'MOSQUITERA DE VENTANA', f: ['Malla fina gris', 'Evitar que entren moscas', 'Marco de aluminio', 'Aire fresco de noche'] },
    { w: 'TOLDO DE TERRAZA', f: ['Manivela para desenrollar', 'Tela a rayas verdes y blancas', 'Dar sombra en verano', 'Recoger si hay viento'] },
    { w: 'TIMBRE DE LA PUERTA', f: ['Pulsador en la entrada', 'Sonido ding dong dentro', 'Esperar a que abran', 'Telefonillo'] },
    { w: 'MIRILLA DE LA PUERTA', f: ['Lente ojo de pez', 'Mirar quién llama antes de abrir', 'Círculo de metal en la madera', 'Portal'] },
    { w: 'FELPUDO DE ENTRADA', f: ['Bienvenido a casa', 'Limpiarse los zapatos', 'Fibras de coco ásperas', 'Delante de la puerta'] },
    { w: 'CADENA DE SEGURIDAD', f: ['Entreabrir la puerta unos centímetros', 'Eslabones de metal', 'Pestillo interior', 'Evitar intrusos'] },
    { w: 'BARRERA PARA BEBÉS', f: ['Puerta de madera en escaleras', 'Cierre a presión', 'Evitar que el niño caiga', 'Pasillo'] },
    { w: 'TABLA DE PLANCHAR', f: ['Funda acolchada con dibujos', 'Patas metálicas plegables', 'Soporte para apoyar la plancha caliente', 'Vapor'] },
    { w: 'RODILLO QUITAPELUSAS', f: ['Papel adhesivo que gira', 'Quitar pelos del gato en ropa negra', 'Mango de plástico', 'Arrancar hoja'] },
    { w: 'PLUMERO ATRAPAPOLVO', f: ['Fibras estáticas que atrapan el polvo', 'Limpiar estanterías y cuadros', 'Mango largo', 'Sacudir'] },
    { w: 'ESTROPAJO VERDE', f: ['Scotch-Brite áspero', 'Fregar ollas pegadas', 'Esponja amarilla por el otro lado', 'Fregadero'] },
    { w: 'BAYETA AMARILLA', f: ['Limpiar encimera de cocina', 'Escurrir húmeda', 'Secar gotas de agua', 'Microfibra'] },
    { w: 'GAMUZA DE MICROFIBRA', f: ['Limpiar cristales sin rayar', 'Gafas o pantallas', 'Sin pelusas', 'Lavar sin suavizante'] },
    { w: 'CUBO DE BASURA CON PEDAL', f: ['Pisar para levantar la tapa', 'Bolsa de basura encajada', 'Cocina limpia sin tocar nada', 'Olores cerrados'] }
  ],
  leisure: [
    { w: 'JUEGO DEL TWISTER', f: ['Círculos de cuatro colores', 'Ruleta que dice mano derecha a rojo', 'Nudo de cuerpos en el suelo', 'Caerse de risa'] },
    { w: 'JUEGO DE OPERACIÓN', f: ['Pinzas con cable', 'Sonido de nariz que se enciende en rojo', 'Huesos de plástico para sacar', 'Pulso de cirujano'] },
    { w: 'JUEGO DEL QUIÉN ES QUIÉN', f: ['¿Tiene bigote y gafas?', 'Bajar ventanitas con caras', 'Adivinar el personaje del rival', 'Pelo rubio'] },
    { w: 'JUEGO DEL CLUEDO', f: ['Asesinato en la mansión', 'Coronel Mostaza en la biblioteca', 'Candelabro o llave inglesa', 'Sobre confidencial'] },
    { w: 'JUEGO DEL HUNDIR LA FLOTA', f: ['Tocado y hundido', 'Coordenadas B4 o C7', 'Pivotes blancos y rojos', 'Portaviones y submarinos'] },
    { w: 'JUEGO DEL RISK', f: ['Conquistar el mundo', 'Ejércitos de plástico de colores', 'Tirar dados para atacar territorios', 'Kamchatka'] },
    { w: 'JUEGO DE CATÁN', f: ['Madera por ovejas', 'Construir caminos y poblados', 'Ladrón en el siete', 'Fichas hexagonales'] },
    { w: 'JUEGO DE CARCASSONNE', f: ['Poner losetas de caminos y castillos', 'Seguidores / meeples de madera', 'Murallas cerradas', 'Puntos al final'] },
    { w: 'JUEGO DEL DIXIT', f: ['Cartas con dibujos surrealistas', 'Dar una pista misteriosa', 'Conejitos en marcador', 'Votar la carta correcta'] },
    { w: 'JUEGO DEL TIME\'S UP', f: ['Adivinar personajes en tres rondas', 'Decir frases luego una palabra luego mímica', 'Reloj de arena', 'Risas en equipo'] },
    { w: 'JUEGO DEL JUS D\'ORANGE / PARTY & CO', f: ['Pruebas de dibujar mímica y tararear', 'Peanas de colores con fichas', 'Preguntas contrarreloj', 'Tablero en cruz'] },
    { w: 'JUEGO DEL VIRUS', f: ['Órganos sanos e infectados', 'Vacunas y medicinas', 'Robar el cuerpo al rival', 'Cartas rápidas'] },
    { w: 'JUEGO DEL EXPLODING KITTENS', f: ['Gato que explota si lo robas', 'Desactivar con puntero láser', 'Saltar turno o ver futuro', 'Cartas locas'] },
    { w: 'JUEGO DE LA TORRE JENGA', f: ['Bloques de madera apilados', 'Sacar uno con un dedo y ponerlo arriba', 'La torre tiembla y se cae', 'Pulso firme'] },
    { w: 'TIRO CON ESCOPETILLA DE FERIA', f: ['Plomos pequeños', 'Tirar un palillo para ganar peluche gigante', 'Cañón doblado', 'Atracción'] },
    { w: 'PESCA DE PATITOS DE PLÁSTICO', f: ['Caña con anzuelo en estanque circular', 'Ver el número bajo la base del patito', 'Premio asegurado para niños', 'Feria'] },
    { w: 'LANZAMIENTO DE ANILLAS A BOTELLAS', f: ['Aros de plástico', 'Encajar en el cuello de cristal', 'Difícil que entre', 'Premio de peluche'] },
    { w: 'TREN DE LA BRUJA', f: ['Globo que te quita la bruja con la escoba', 'Vagones dando vueltas en túnel oscuro', 'Susto a los niños', 'Feria de pueblo'] },
    { w: 'BARCO PIRATA BALANCÍN', f: ['Columpio gigante que sube de lado a lado', 'Cosquillas en la tripa al bajar', 'Gritos de la gente', 'Parque de atracciones'] },
    { w: 'CASA DEL TERROR', f: ['Actores disfrazados que te persiguen', 'Pasillo oscuro con luces estroboscópicas', 'Motosierra sonando sin cadena', 'Gritos'] }
  ],
  culture: [
    { w: 'CASTAÑADA DE OTOÑO', f: ['Puestos con humo blanco de carbón', 'Castañas asadas en cucurucho de papel', 'Noviembre', 'Calentarse las manos'] },
    { w: 'CHOCOLATADA POPULAR', f: ['Olla gigante en la plaza del pueblo', 'Churros o bizcochos para mojar', 'Fiestas patronales', 'Mañana de reyes'] },
    { w: 'PAELLA GIGANTE EN LA PLAZA', f: ['Sartén de varios metros de diámetro', 'Cocinero con pala de obra', 'Platos de plástico para todos los vecinos', 'Fiesta'] },
    { w: 'SARDINADA EN LA PLAYA', f: ['Espetos de caña clavados en la arena junto a brasas', 'Humo con olor a pescado rico', 'San Juan', 'Noche de verano'] },
    { w: 'HOGUERA DE SAN JUAN', f: ['Saltar por encima del fuego', 'Noche más corta del año', 'Quemar apuntes o deseos', 'Playa el 23 de junio'] },
    { w: 'CORREFOCS', f: ['Demonios con carretillas de chispas', 'Gente saltando bajo el fuego', 'Tambores ruidosos', 'Fiestas de Cataluña'] },
    { w: 'TAMBORRADA DE SAN SEBASTIÁN', f: ['Tambores tocando Marcha de San Sebastián 24 horas', 'Disfrazados de cocineros y soldados', '20 de enero', 'Fiesta'] },
    { w: 'BATALLA DEL VINO DE HARO', f: ['Gente vestida de blanco manchada de morado', 'Sulfatadoras llenas de vino tinto', 'La Rioja en junio', 'Empapados'] },
    { w: 'DESCENSO DEL SELLA', f: ['Piraguas en el río desde Arriondas', 'Sidra y fiesta de las piraguas', 'Primer sábado de agosto', 'Asturias'] },
    { w: 'ROMERÍA DEL ROCÍO', f: ['Carretas tiradas por bueyes cruzando marismas', 'Virgen del Rocío / Blanca Paloma', 'Almonte en Huelva', 'Cantes'] },
    { w: 'FIESTA DE LA PALOMA DE MADRID', f: ['Chulapos con chaleco y parpusa', 'Chulapas con mantón de Manila', 'Agosto en La Latina', 'Bailar el chotis'] },
    { w: 'BAILE DEL CHOTIS', f: ['Girar sobre una baldosa sin salirse', 'La mujer lleva al hombre', 'Música de organillo', 'Traje típico madrileño'] },
    { w: 'MANTÓN DE MANILA', f: ['Flecos largos bordados con flores', 'Seda brillante sobre los hombros', 'Traje de flamenca o chulapa', 'Elegante'] },
    { w: 'CORONA DE ESPINAS', f: ['Semana Santa', 'Cabeza de Cristo en el paso procesional', 'Pasión', 'Iglesia'] },
    { w: 'PALMA DEL DOMINGO DE RAMOS', f: ['Hojas de palmera trenzadas de blanco', 'Bendecir en la iglesia', 'Llevar los niños en la mano', 'Semana Santa'] },
    { w: 'MONA DE CHOCOLATE', f: ['Castillo o figura de dibujos animados', 'Regalo del padrino a su ahijado', 'Lunes de Pascua', 'Pastelería'] },
    { w: 'ROSCÓN CON HABA Y REY', f: ['Pagar el roscón si te sale el haba verde', 'Ponerse la corona dorada de cartón', 'Nata trufa o crema', 'Día de Reyes'] },
    { w: 'CAMPANADAS DE LA PUERTA DEL SOL', f: ['Bajada del carillón dorado', 'Cuatro cuartos para no atragantarse', 'Comer doce uvas a la vez', 'Nochevieja'] },
    { w: 'TRAJE DE LUCES', f: ['Torero', 'Bordados de oro y plata', 'Medias rosas', 'Montera en la cabeza'] },
    { w: 'CAPOTE DE BREGA', f: ['Tela pesada de color fucsia y amarillo', 'Torear de salida', 'Vuelo con las dos manos', 'Plaza'] }
  ],
  music: [
    { w: 'PÚA DE GUITARRA / PLEGAR', f: ['Triangulito de plástico duro', 'Rasguear las cuerdas metálicas', 'Perderla en el suelo', 'Dedos'] },
    { w: 'CAPOTRASTO / CEJILLA', f: ['Pinza de metal en el mástil', 'Subir el tono de la guitarra', 'Tornillo de ajuste', 'Traste'] },
    { w: 'AFINADOR DE CLIP', f: ['Enganchar en la pala de la guitarra', 'Pantalla que se pone verde cuando afina', 'Letras E A D G B E', 'Vibración'] },
    { w: 'SOPORTE DE GUITARRA', f: ['Trípode en el suelo', 'Apoyar el instrumento de pie', 'Goma para no rayar la madera', 'Habitación'] },
    { w: 'FUNDA DE GUITARRA CON ASAS', f: ['Llevar la guitarra a la espalda como mochila', 'Cremallera grande y acolchado', 'Bolsillo para partituras', 'Clases'] },
    { w: 'PEDAL DE DISTORSIÓN DE GUITARRA', f: ['Pisar con la bota en el suelo', 'Sonido rock sucio y potente', 'Luz roja que se enciende', 'Jack'] },
    { w: 'PEDAL WAH-WAH', f: ['Balancín con el pie', 'Sonido que llora uou uou', 'Jimi Hendrix y funk', 'Efecto'] },
    { w: 'METRÓNOMO DE PÉNDULO', f: ['Varilla con peso que oscila de lado a lado', 'Tic tac constante para no acelerarse', 'Marcar el tempo', 'Música'] },
    { w: 'DIAPASÓN DE HORQUILLA', f: ['Metal con dos puntas que da la nota LA 440', 'Golpear en la rodilla y apoyar en la oreja', 'Afilar instrumentos', 'Canto'] },
    { w: 'ATRIL DE MÚSICA PLEGABLE', f: ['Patas finas de metal negro', 'Sujetar las hojas de partituras abiertas', 'Ajustar la altura de pie o sentado', 'Orquesta'] },
    { w: 'BOQUILLA DE SAXOFÓN', f: ['Caña de madera sujeta con abrazadera', 'Apretar con los dientes y soplar', 'Sonido jazz', 'Limpiar con trapo'] },
    { w: 'SORDINA DE TROMPETA', f: ['Cono de metal que se mete en la campana', 'Bajar el volumen para ensayar en casa', 'Sonido apagado', 'Viento metal'] },
    { w: 'PALOS DE BATERÍA / BAQUETAS', f: ['Madera de nogal con punta redonda', 'Golpear la caja y los platillos', 'Romperse de tanto tocar', 'Ritmo'] },
    { w: 'PEDAL DE BOMBO', f: ['Pisar con el pie derecho', 'Maza que golpea el parche del tambor gigante', 'Sonido grave del ritmo', 'Muelle'] },
    { w: 'PLATILLO CHARLES / HI-HAT', f: ['Dos platillos que chocan con pedal de pie', 'Marcar el compás con baqueta', 'Sonido tss tss', 'Batería'] },
    { w: 'PLATILLO CRASH', f: ['Platillo grande que estalla al final de frase', 'Sonido explosivo y brillante', 'Moverse vibrando', 'Batería'] },
    { w: 'TAMBOR DE REDOBLANTE', f: ['Bordonero de alambres por debajo', 'Sonido seco y militar trrr-pum', 'Caja metálica de la batería', 'Baquetas'] },
    { w: 'CAJÓN FLAMENCO', f: ['Caja de madera sobre la que te sientas', 'Golpear con las palmas abiertas', 'Agudo en el borde y grave en el centro', 'Compás'] },
    { w: 'TIMBALES DE ORQUESTA', f: ['Calderos gigantes de cobre con parche', 'Mazas con cabeza de fieltro suave', 'Sonido retumbante dramático', 'Afinar con pedal'] },
    { w: 'GONG ORIENTAL', f: ['Disco gigante de bronce colgado', 'Maza pesada que golpea el centro', 'Vibración misteriosa que dura mucho', 'Meditación'] }
  ],
  body: [
    { w: 'PUPILA DEL OJO', f: ['Punto negro central', 'Se dilata en la oscuridad', 'Se encoge con mucha luz', 'Iris de color alrededor'] },
    { w: 'IRIS DE COLOR', f: ['Ojos azules verdes o marrones', 'Círculo que rodea la pupila', 'Mirada', 'Parte visible del ojo'] },
    { w: 'LÓBULO DE LA OREJA', f: ['Carne blanda donde se pone el pendiente', 'Tirar de las orejas en cumpleaños', 'Colgando abajo', 'Pendiente'] },
    { w: 'PÓMULO DE LA CARA', f: ['Hueso debajo del ojo', 'Ponerse colorete', 'Mejilla alta', 'Cara angulosa'] },
    { w: 'FOSAS NASALES', f: ['Dos agujeros de la nariz', 'Respirar aire', 'Pelitos dentro que filtran', 'Oler'] },
    { w: 'PALADAR DE LA BOCA', f: ['Techo de la boca', 'Quemarse con la pizza caliente', 'Tocar con la punta de la lengua', 'Duro y blando'] },
    { w: 'CAMPANILLA / ÚVULA', f: ['Colgando al fondo de la garganta', 'Tocarla da arcadas', 'Vibrar al roncar', 'Abrir la boca y decir ah'] },
    { w: 'AMÍGDALAS', f: ['Bolas a los lados de la garganta', 'Inflamarse con anginas y fiebre', 'Dolor al tragar saliva', 'Médico'] },
    { w: 'NUEZ DE LA GARGANTA / MANZANA DE ADÁN', f: ['Bulto en el cuello de los hombres', 'Sube y baja al tragar', 'Cartílago tiroides', 'Voz grave'] },
    { w: 'CLAVÍCULA', f: ['Hueso largo entre el cuello y el hombro', 'Rompérselo al caerse de la bici', 'Tocar el hueso horizontal', 'Pecho alto'] },
    { w: 'AXILA', f: ['Hacerse cosquillas', 'Ponerse desodorante', 'Sudar con calor', 'Debajo del brazo'] },
    { w: 'BÍCEPS DEL BRAZO', f: ['Hacer bola con el brazo flexionado', 'Músculo que se marca', 'Fuerza al levantar peso', 'Brazo'] },
    { w: 'TRÍCEPS DEL BRAZO', f: ['Músculo de la parte trasera del brazo', 'Extender el codo', 'Fondo en paralelas', 'Entrenar'] },
    { w: 'ANTEBRAZO', f: ['Entre el codo y la muñeca', 'Huesos radio y cúbito', 'Apoyar en la mesa', 'Brazos'] },
    { w: 'PALMA DE LA MANO', f: ['Líneas de la vida que leen las brujas', 'Aplaudir chocando dos', 'Piel sin pelo', 'Abrir la mano'] },
    { w: 'DEDO ÍNDICE', f: ['Señalar con el dedo', 'Ponerse en los labios para pedir silencio', 'Al lado del pulgar', 'Apretar botón'] },
    { w: 'DEDO CORAZÓN', f: ['El dedo más largo de la mano', 'Gesto obsceno / peineta', 'En medio de los cinco', 'Mano'] },
    { w: 'DEDO ANULAR', f: ['Donde se pone el anillo de boda', 'Entre el corazón y el meñique', 'Mano', 'Alianza'] },
    { w: 'DEDO MEÑIQUE', f: ['El más chiquitito de la mano', 'Levantarlo al beber té con elegancia', 'Golpearse en la pata del sofá', 'Pie'] },
    { w: 'NUDILLOS DE LA MANO', f: ['Hacerse sonar los dedos craaac', 'Huesos que sobresalen al cerrar el puño', 'Golpear la puerta para llamar', 'Pelea'] }
  ],
  clothing: [
    { w: 'CAMISETA DE TIRANTES', f: ['Sin mangas', 'Hombros al aire en verano', 'Fresca', 'Debajo de la camisa'] },
    { w: 'POLO DE CUELLO', f: ['Dos o tres botones', 'Cuello camisero de punto', 'Cocodrilo o jinete bordado', 'Elegante informal'] },
    { w: 'CAMISA DE CUADROS', f: ['Estilo leñador americano', 'Franela calentita de invierno', 'Botones en los bolsillos', 'Mangas remangadas'] },
    { w: 'TOP CORTO / CROP TOP', f: ['Camiseta corta que deja el ombligo al aire', 'Verano juvenil', 'Tirantes o manga corta', 'Moda'] },
    { w: 'MONO ENTERIZO', f: ['Pantalón y parte de arriba unidos en una pieza', 'Difícil para ir al baño', 'Cremallera trasera', 'Elegante'] },
    { w: 'PETO VAQUERO', f: ['Tirantes con hebillas metálicas sobre el pecho', 'Bolsillo grande delantero', 'Minions o mecánicos', 'Pantalón'] },
    { w: 'LEGGINGS / MALLAS', f: ['Pantalón elástico muy pegado al cuerpo', 'Hacer deporte o estar cómoda', 'Negro ajustado', 'Sin botones'] },
    { w: 'PANTALÓN DE CHÁNDAL', f: ['Cintura con cordón ajustable', 'Algodón suave con bolsillos', 'Estar por casa un domingo', 'Elástico en los tobillos'] },
    { w: 'CHAQUETA BLAZER', f: ['Americana elegante para trabajar', 'Solapas y bolsillos con tapeta', 'Botón central', 'Poner sobre camiseta'] },
    { w: 'CAZADORA VAQUERA', f: ['Tela de jeans azul con botones metálicos', 'Chaqueta de entretiempo', 'Bolsillos en el pecho', 'Costuras amarillas'] },
    { w: 'CAZADORA DE CUERO / PERFECTO', f: ['Cremallera cruzada en diagonal', 'Estilo motero rebelde', 'Color negro brillante', 'Solapas con tachuelas'] },
    { w: 'CHAQUETA BÓMBER', f: ['Gomas en cuello cintura y puños', 'Forro naranja por dentro', 'Pilotos de aviación militar', 'Bolsillo en la manga'] },
    { w: 'GABARDINA CLÁSICA', f: ['Color beige claro impermeable', 'Cinturón con hebilla para atar', 'Detective privado bajo la lluvia', 'Botones dobles'] },
    { w: 'ANORAK DE PLUMAS', f: ['Chaqueta acolchada como un muñeco Michelín', 'Relleno de pluma muy calentito', 'Capucha con pelo sintético', 'Invierno frío'] },
    { w: 'CORTAVIENTOS', f: ['Chaqueta muy fina que no pesa nada', 'Correr por la montaña', 'Tejido impermeable y ligero', 'Cremallera'] },
    { w: 'CHALECO ACOLCHADO', f: ['Cuerpo abrigado sin mangas en los brazos', 'Cremallera delantera', 'Poner sobre jersey', 'Otoño'] },
    { w: 'ESMÓQUIN ELEGANTE', f: ['Solapas de raso brillante en la chaqueta', 'Pajarita negra y camisa con gemelos', 'Alfombra roja de los Óscar', 'James Bond'] },
    { w: 'VESTIDO DE NOVIA', f: ['Blanco inmaculado con cola larga', 'Velo de tul sobre la cabeza', 'Ramo de flores en la mano', 'Boda en el altar'] },
    { w: 'VELO DE BODA', f: ['Tela transparente sobre la cara', 'Levantar para dar el beso de casados', 'Sujeto con peineta al peinado', 'Blanco'] },
    { w: 'ZAPATOS MOCASINES', f: ['Sin cordones para meter el pie directo', 'Antifaz de cuero sobre el empeine', 'Suela dura que hace ruido', 'Elegante clásico'] }
  ],
  everyday: [
    { w: 'METER LA PATA', f: ['Decir algo inoportuno sin querer', 'Tierra trágame', 'Momento de vergüenza', 'Disculparse'] },
    { w: 'TIERRA TRÁGAME', f: ['Vergüenza monumental', 'Querer desaparecer del mapa', 'Meter la pata delante de todos', 'Ganas de llorar'] },
    { w: 'ESTAR HASTA LAS NARICES', f: ['Harto de aguantar una situación', 'Paciencia agotada', 'No poder más', 'Gritar ya basta'] },
    { w: 'DORMIRSE EN LOS LAURELES', f: ['Relajarse cuando ibas ganando', 'Perder la ventaja por confiado', 'No esforzarse a tiempo', 'Refrán'] },
    { w: 'DAR LA LATA', f: ['Molestar a alguien sin parar', 'Ser muy pesado e insistente', 'Hacer preguntas todo el rato', 'Niños'] },
    { w: 'TOMAR EL PELO', f: ['Gastar una broma inocente', 'Hacer creer una mentira graciosa', 'No te lo tomes en serio', 'Risas'] },
    { w: 'COSTAR UN OJO DE LA CARA', f: ['Precio desorbitado y carísimo', 'Factura enorme', 'Quedarse sin blanca', 'No poder pagarlo'] },
    { w: 'NO PEGAR OJO EN TODA LA NOCHE', f: ['Insomnio dando vueltas en la cama', 'Mirar el reloj a las cuatro de la mañana', 'Vecinos con fiesta', 'Ojeras'] },
    { w: 'DORMIR COMO UN LIRÓN', f: ['Sueño profundísimo sin despertarse', 'Diez horas seguidas en la cama', 'Descanso total', 'No oír la alarma'] },
    { w: 'TENER AGUJETAS', f: ['Dolor muscular al día siguiente del gimnasio', 'No poder ni bajar las escaleras', 'Hacer ejercicio sin calentar', 'Ácido láctico'] },
    { w: 'QUEDARSE EN BLANCO', f: ['Olvidar todo en medio de un examen', 'Cerebro bloqueado ante una pregunta', 'Silencio incómodo al hablar en público', 'Mente vacía'] },
    { w: 'VER LA LUZ AL FINAL DEL TÚNEL', f: ['Por fin se acaba una mala racha', 'Esperanza tras mucho esfuerzo', 'Últimos exámenes del curso', 'Alivio'] },
    { w: 'LLEVARSE UN CHASCO', f: ['Decepción inesperada', 'Esperabas algo genial y fue un desastre', 'Desilusión', 'Cara de pena'] },
    { w: 'ESTAR EN LAS NUBES', f: ['Despistado pensando en musarañas', 'Mirar por la ventana sin enterarse de la clase', 'Soñar despierto', 'Distraído'] },
    { w: 'CHUPARSE EL DEDO', f: ['No ser tonto ni ingenuo', 'No me engañas tan fácil', 'Tener experiencia en la vida', 'Gesto'] },
    { w: 'ECHAR LEÑA AL FUEGO', f: ['Empeorar una discusión que ya estaba tensa', 'Decir cosas que enfadan más a los demás', 'Provocar bronca', 'Polémica'] },
    { w: 'DARSE CON UN CANTO EN LOS DIENTES', f: ['Conformarse porque podía haber sido mucho peor', 'Tener relativa suerte en una desgracia', 'Alivio amargo', 'Agradecido'] },
    { w: 'HACERSE LA BOCA AGUA', f: ['Pensar en una comida deliciosa', 'Empezar a salivar de golpe', 'Olor a pan caliente o carne asada', 'Ganas de comer'] },
    { w: 'TIRAR LA TOALLA', f: ['Rendirse y abandonar la pelea', 'No intentarlo más', 'Gesto de boxeo', 'Darse por vencido'] },
    { w: 'IRSE POR LAS RAMAS', f: ['No ir al grano al explicar una historia', 'Enredarse con detalles que no importan', 'Tardar horas en llegar al punto', 'Despistar'] }
  ]
};
