// Part 1: Categories 1 to 10 for Palabra Secreta
export const part1Categories = [
  {
    categoryKey: 'animals',
    categoryName: 'Animales',
    idPrefix: 'ani',
    words: [
      { w: 'ELEFANTE', f: ['Trompa', 'Grande', 'África', 'Colmillos'] },
      { w: 'JIRAFA', f: ['Cuello', 'Alto', 'Manchas', 'Sabana'] },
      { w: 'PINGÜINO', f: ['Polo', 'Hielo', 'Nieve', 'Pájaro'] },
      { w: 'TIBURÓN', f: ['Mar', 'Dientes', 'Aleta', 'Peligro'] },
      { w: 'DELFÍN', f: ['Mar', 'Inteligente', 'Saltar', 'Agua'] },
      { w: 'CANGURO', f: ['Saltar', 'Australia', 'Bolsa', 'Cría'] },
      { w: 'COCODRILO', f: ['Dientes', 'Río', 'Reptil', 'Verde'] },
      { w: 'RINOCERONTE', f: ['Cuerno', 'Nariz', 'Piel', 'Grande'] },
      { w: 'HIPOPÓTAMO', f: ['Agua', 'Pesado', 'Boca', 'África'] },
      { w: 'ÁGUILA', f: ['Volar', 'Garras', 'Pico', 'Caza'] },
      { w: 'BÚHO', f: ['Noche', 'Ojos', 'Girar', 'Árbol'] },
      { w: 'FLAMENCO', f: ['Rosa', 'Pata', 'Pájaro', 'Agua'] },
      { w: 'CAMALEÓN', f: ['Color', 'Cambiar', 'Lengua', 'Reptil'] },
      { w: 'PULPO', f: ['Tentáculos', 'Mar', 'Tinta', 'Ocho'] },
      { w: 'MEDUSA', f: ['Picar', 'Agua', 'Transparente', 'Tentáculos'] },
      { w: 'LANGOSTA', f: ['Marisco', 'Pinzas', 'Mar', 'Rojo'] },
      { w: 'CANGREJO', f: ['Pinzas', 'Playa', 'Andar de lado', 'Concha'] },
      { w: 'ARDILLA', f: ['Nuez', 'Cola', 'Árbol', 'Bellota'] },
      { w: 'MAPACHE', f: ['Antifaz', 'Basura', 'Cola', 'Manos'] },
      { w: 'MURCIÉLAGO', f: ['Noche', 'Cueva', 'Volar', 'Vampiro'] },
      { w: 'LOBO', f: ['Aullar', 'Luna', 'Manada', 'Caperucita'] },
      { w: 'ZORRO', f: ['Astuto', 'Rojo', 'Cola', 'Bosque'] },
      { w: 'GORILA', f: ['Mono', 'Pecho', 'Selva', 'Grande'] },
      { w: 'CHIMPANCÉ', f: ['Inteligente', 'Mono', 'Plátano', 'Árbol'] },
      { w: 'PANDA', f: ['Bambú', 'Blanco y negro', 'Oso', 'China'] },
      { w: 'KOALA', f: ['Eucalipto', 'Australia', 'Árbol', 'Dormir'] },
      { w: 'ORNITORRINCO', f: ['Pico', 'Pato', 'Australia', 'Mamífero'] },
      { w: 'AVESTRUZ', f: ['Correr', 'Huevo', 'Cuello', 'Cabeza en tierra'] },
      { w: 'PAVO REAL', f: ['Plumas', 'Cola', 'Colores', 'Abanico'] },
      { w: 'CABALLITO DE MAR', f: ['Mar', 'Cola', 'Pez', 'Agua'] },
      { w: 'LEÓN', f: ['Rey', 'Selva', 'Melena', 'Rugido'] },
      { w: 'TIGRE', f: ['Rayas', 'Naranja', 'Felino', 'Garras'] },
      { w: 'CEBRA', f: ['Rayas', 'Blanco y negro', 'Caballo', 'Sabana'] },
      { w: 'OSO POLAR', f: ['Blanco', 'Ártico', 'Frío', 'Hielo'] },
      { w: 'OSO PARDO', f: ['Bosque', 'Miel', 'Hibernar', 'Cueva'] },
      { w: 'LINCE IBÉRICO', f: ['España', 'Pinceles', 'Orejas', 'Gato salvaje'] },
      { w: 'ERIZO', f: ['Púas', 'Espinas', 'Bola', 'Pinchos'] },
      { w: 'CAMELLO', f: ['Joroba', 'Desierto', 'Arena', 'Sed'] },
      { w: 'DROMEDARIO', f: ['Una joroba', 'Desierto', 'Camello', 'Arena'] },
      { w: 'FOCA', f: ['Circo', 'Pelota', 'Hielo', 'Bigotes'] },
      { w: 'MORSA', f: ['Colmillos', 'Hielo', 'Bigotes', 'Gorda'] },
      { w: 'ORCA', f: ['Ballena asesina', 'Blanco y negro', 'Mar', 'Aleta'] },
      { w: 'BALLENA JOROBADA', f: ['Mar', 'Grande', 'Canto', 'Chorro'] },
      { w: 'GUEPARDO', f: ['Rápido', 'Velocidad', 'Manchas', 'Correr'] },
      { w: 'HIENA', f: ['Risa', 'Carroña', 'Sabana', 'África'] },
      { w: 'CASTOR', f: ['Presa', 'Madera', 'Dientes', 'Río'] },
      { w: 'CIERVO', f: ['Cuernos', 'Bambi', 'Bosque', 'Pelo'] },
      { w: 'JABALÍ', f: ['Cerdo salvaje', 'Colmillos', 'Bosque', 'Caza'] },
      { w: 'TORO', f: ['Cuernos', 'Rojo', 'Plaza', 'Vaca'] },
      { w: 'VACA', f: ['Leche', 'Pasto', 'Manchas', 'Muu'] },
      { w: 'CABALLO', f: ['Cabalgar', 'Silla', 'Herradura', 'Crin'] },
      { w: 'BURRO', f: ['Orejas', 'Carga', 'Rebuznar', 'Terco'] },
      { w: 'OVEJA', f: ['Lana', 'Rebaño', 'Pastoreo', 'Balido'] },
      { w: 'CABRA', f: ['Monte', 'Cuernos', 'Barba', 'Leche'] },
      { w: 'CERDO', f: ['Jamón', 'Barro', 'Granja', 'Oink'] },
      { w: 'PERRO', f: ['Ladrar', 'Mascota', 'Hueso', 'Guau'] },
      { w: 'GATO', f: ['Miau', 'Bigotes', 'Arañar', 'Mascota'] },
      { w: 'CONEJO', f: ['Zanahoria', 'Orejas', 'Saltar', 'Madriguera'] },
      { w: 'HÁMSTER', f: ['Rueda', 'Jaula', 'Mejillas', 'Roedor'] },
      { w: 'HURÓN', f: ['Tubo', 'Alargado', 'Mascota', 'Juguetón'] },
      { w: 'GALLINA', f: ['Huevos', 'Corral', 'Plumas', 'Gallo'] },
      { w: 'GALLO', f: ['Cantar', 'Mañana', 'Cresta', 'Despertar'] },
      { w: 'PATO', f: ['Cuac', 'Estanque', 'Plumas', 'Pico'] },
      { w: 'PAVO', f: ['Navidad', 'Plumas', 'Comida', 'Granja'] },
      { w: 'LORO', f: ['Hablar', 'Repetir', 'Verde', 'Pirata'] },
      { w: 'CANARIO', f: ['Amarillo', 'Cantar', 'Jaula', 'Pájaro'] },
      { w: 'PALOMA', f: ['Plaza', 'Paz', 'Volar', 'Ciudad'] },
      { w: 'GAVIOTA', f: ['Playa', 'Mar', 'Pescado', 'Pájaro'] },
      { w: 'CUERVO', f: ['Negro', 'Mal agüero', 'Inteligente', 'Graznido'] },
      { w: 'CIGÜEÑA', f: ['Campanario', 'Bebé', 'Nido', 'Pico largo'] },
      { w: 'PELÍCANO', f: ['Bolsa', 'Pico', 'Pez', 'Agua'] },
      { w: 'COLIBRÍ', f: ['Pequeño', 'Alas rápidas', 'Flores', 'Néctar'] },
      { w: 'GOLONDRINA', f: ['Primavera', 'Nido', 'Volar', 'Cola partida'] },
      { w: 'RANA', f: ['Saltar', 'Verde', 'Charca', 'Croar'] },
      { w: 'SAPO', f: ['Verrugas', 'Príncipe', 'Charca', 'Anfibio'] },
      { w: 'TORTUGA', f: ['Caparazón', 'Lenta', 'Verde', 'Vieja'] },
      { w: 'SERPIENTE', f: ['Veneno', 'Reptar', 'Escamas', 'Cascabel'] },
      { w: 'IGUANA', f: ['Reptil', 'Verde', 'Cresta', 'Árbol'] },
      { w: 'LAGARTIJA', f: ['Pared', 'Sol', 'Cola suelta', 'Pequeña'] },
      { w: 'SALAMANDRA', f: ['Fuego', 'Manchas amarillas', 'Anfibio', 'Agua'] },
      { w: 'CARACOL', f: ['Baba', 'Concha', 'Lento', 'Cuernos'] },
      { w: 'ABEJA', f: ['Miel', 'Picar', 'Colmena', 'Amarillo'] },
      { w: 'AVISPA', f: ['Picadura', 'Rayas', 'Negro y amarillo', 'Nido'] },
      { w: 'MARIPOSA', f: ['Alas', 'Gusano', 'Flores', 'Metamorfosis'] },
      { w: 'HORMIGA', f: ['Hormiguero', 'Fila', 'Trabajar', 'Cargar'] },
      { w: 'MOSQUITO', f: ['Picar', 'Sangre', 'Verano', 'Zumbido'] },
      { w: 'MOSCA', f: ['Molesta', 'Basura', 'Alas', 'Zumbido'] },
      { w: 'ESCARABAJO', f: ['Caparazón duro', 'Patas', 'Pelotero', 'Insecto'] },
      { w: 'MARIQUITA', f: ['Puntos negros', 'Rojo', 'Suerte', 'Insecto'] },
      { w: 'GRILLO', f: ['Cantar', 'Noche', 'Saltamontes', 'Pinocho'] },
      { w: 'SALTAMONTES', f: ['Saltar', 'Verde', 'Patas largas', 'Hierba'] },
      { w: 'LIBÉLULA', f: ['Alas transparentes', 'Río', 'Vuelo', 'Insecto'] },
      { w: 'ARAÑA', f: ['Telaraña', 'Ocho patas', 'Miedo', 'Picar'] },
      { w: 'ESCORPIÓN', f: ['Aguijón', 'Pinzas', 'Veneno', 'Desierto'] },
      { w: 'CIEMPIÉS', f: ['Muchas patas', 'Bicho', 'Suelo', 'Alargado'] },
      { w: 'PEZ PAYASO', f: ['Nemo', 'Naranja', 'Anémona', 'Rayas blancas'] },
      { w: 'PEZ ESPADA', f: ['Pico largo', 'Mar', 'Pez', 'Arma'] },
      { w: 'ATÚN', f: ['Lata', 'Rojo', 'Pescado', 'Ensalada'] },
      { w: 'SALMÓN', f: ['Naranja', 'Río', 'Saltar', 'Sushi'] },
      { w: 'SARDINA', f: ['Lata', 'Pequeña', 'Plata', 'Fuego'] },
      { w: 'CALAMAR', f: ['Tinta', 'Rebozado', 'Tentáculos', 'Mar'] },
      { w: 'MEJILLÓN', f: ['Negro', 'Concha', 'Vapor', 'Roca'] },
      { w: 'ALMEJA', f: ['Concha', 'Arena', 'Arroz', 'Marisco'] },
      { w: 'OSTRA', f: ['Perla', 'Abrir', 'Marisco', 'Cara'] },
      { w: 'ESTRELLA DE MAR', f: ['Cinco puntas', 'Fondo marino', 'Playa', 'Brazos'] },
      { w: 'ERIZO DE MAR', f: ['Pinchos', 'Roca', 'Playa', 'Negro'] },
      { w: 'NUTRIA', f: ['Río', 'Nadar', 'Jugar', 'Piedra'] },
      { w: 'SURICATA', f: ['Timón', 'De pie', 'Vigilar', 'África'] },
      { w: 'LEMUR', f: ['Madagascar', 'Ojos grandes', 'Cola rayada', 'Rey'] },
      { w: 'JAGUAR', f: ['Selva', 'Manchas', 'Amazonas', 'Felino'] },
      { w: 'LEOPARDO', f: ['Manchas', 'Árbol', 'Cazar', 'África'] },
      { w: 'PANTERA NEGRA', f: ['Negro', 'Selva', 'Bagheera', 'Felino'] },
      { w: 'PUMA', f: ['Montaña', 'América', 'Felino', 'Marrón'] },
      { w: 'MANATÍ', f: ['Vaca marina', 'Gordo', 'Agua', 'Herbívoro'] },
      { w: 'TEJÓN', f: ['Rayas cara', 'Bosque', 'Madriguera', 'Feroz'] },
      { w: 'ARMADILLO', f: ['Armadura', 'Bola', 'Caparazón', 'Cavar'] },
      { w: 'PEREZOZO', f: ['Lento', 'Árbol', 'Colgado', 'Garras'] },
      { w: 'CHINCHILLA', f: ['Pelo suave', 'Orejas', 'Roedor', 'Andes'] },
      { w: 'COBAYA', f: ['Cuy', 'Conejillo de indias', 'Mascota', 'Chillido'] }
    ]
  },
  {
    categoryKey: 'food',
    categoryName: 'Comida y Bebida',
    idPrefix: 'com',
    words: [
      { w: 'PIZZA', f: ['Queso', 'Masa', 'Italia', 'Horno'] },
      { w: 'HAMBURGUESA', f: ['Carne', 'Pan', 'Ketchup', 'McDonalds'] },
      { w: 'PAELLA', f: ['Arroz', 'Valencia', 'Marisco', 'Azafrán'] },
      { w: 'TORTILLA DE PATATAS', f: ['Huevos', 'Cebolla', 'Española', 'Sartén'] },
      { w: 'CROQUETA', f: ['Bechamel', 'Jamón', 'Freír', 'Abuela'] },
      { w: 'GAZPACHO', f: ['Tomate', 'Frío', 'Verano', 'Sopa'] },
      { w: 'SALMOREJO', f: ['Córdoba', 'Tomate', 'Huevo duro', 'Pan'] },
      { w: 'CHURROS CON CHOCOLATE', f: ['Desayuno', 'Porras', 'Masa', 'Azúcar'] },
      { w: 'HELADO', f: ['Frío', 'Cucurucho', 'Verano', 'Bola'] },
      { w: 'CHOCOLATE', f: ['Cacao', 'Dulce', 'Tableta', 'Negro'] },
      { w: 'PALOMITAS DE MAÍZ', f: ['Cine', 'Sal', 'Película', 'Maíz'] },
      { w: 'ESPAGUETIS', f: ['Pasta', 'Tomate', 'Largas', 'Tenedor'] },
      { w: 'LASAÑA', f: ['Capas', 'Carne', 'Queso', 'Garfield'] },
      { w: 'SUSHI', f: ['Arroz', 'Pescado crudo', 'Japón', 'Alga'] },
      { w: 'KEBAB', f: ['Carne giratoria', 'Pita', 'Turco', 'Salsa'] },
      { w: 'TACO', f: ['Tortilla', 'México', 'Picante', 'Guacamole'] },
      { w: 'BURRITO', f: ['Enrollado', 'Frijoles', 'México', 'Carne'] },
      { w: 'DONUT', f: ['Agujero', 'Glaseado', 'Rosquilla', 'Homer'] },
      { w: 'GALLETA', f: ['Horno', 'Leche', 'Chocolate', 'Monstruo'] },
      { w: 'SANDÍA', f: ['Verano', 'Roja', 'Pepitas', 'Verde'] },
      { w: 'AGUACATE', f: ['Verde', 'Guacamole', 'Hueso', 'Tostada'] },
      { w: 'LIMONADA', f: ['Limón', 'Agua', 'Azúcar', 'Fresca'] },
      { w: 'CAFÉ', f: ['Despertar', 'Taza', 'Cafeína', 'Leche'] },
      { w: 'BATIDO', f: ['Fruta', 'Leche', 'Fresa', 'Pajita'] },
      { w: 'QUESO', f: ['Ratón', 'Leche', 'Curado', 'Manchego'] },
      { w: 'JAMÓN IBÉRICO', f: ['Bellota', 'Cerdo', 'Pata negra', 'Cortar'] },
      { w: 'FABADA ASTURIANA', f: ['Asturias', 'Alubias', 'Chorizo', 'Morcilla'] },
      { w: 'COCIDO MADRILEÑO', f: ['Garbanzos', 'Sopa', 'Carne', 'Madrid'] },
      { w: 'PULPO A LA GALLEGA', f: ['Pimentón', 'Galicia', 'Patatas', 'Madera'] },
      { w: 'PATATAS BRAVAS', f: ['Salsa picante', 'Tapa', 'Bar', 'Fritas'] },
      { w: 'CALAMARES A LA ROMANA', f: ['Anillas', 'Rebozado', 'Limón', 'Bocadillo'] },
      { w: 'EMPANADA', f: ['Masa', 'Atún', 'Horno', 'Relleno'] },
      { w: 'ENSALADILLA RUSA', f: ['Mayonesa', 'Patata', 'Atún', 'Zanahoria'] },
      { w: 'TORREZNOS', f: ['Panceta', 'Crujiente', 'Cerdo', 'Soria'] },
      { w: 'TORRIJAS', f: ['Semana Santa', 'Pan', 'Leche', 'Canela'] },
      { w: 'ARROZ CON LECHE', f: ['Postre', 'Canela', 'Azúcar', 'Limón'] },
      { w: 'NATILLAS', f: ['Galleta María', 'Canela', 'Vainilla', 'Cuchara'] },
      { w: 'FLAN', f: ['Caramelo', 'Huevo', 'Temblar', 'Postre'] },
      { w: 'TARTA DE QUESO', f: ['Horno', 'Queso crema', 'Mermelada', 'Postre'] },
      { w: 'GOFRE', f: ['Cuadrados', 'Bélgica', 'Chocolate', 'Masa'] },
      { w: 'CRUASÁN', f: ['Mantequilla', 'Francia', 'Cuernos', 'Bollo'] },
      { w: 'NACHOS', f: ['Queso fundido', 'Triángulos', 'México', 'Jalapeño'] },
      { w: 'HUMMUS', f: ['Garbanzos', 'Tahini', 'Untar', 'Árabe'] },
      { w: 'ALBÓNDIGAS', f: ['Carne picada', 'Redondas', 'Salsa tomate', 'Guiso'] },
      { w: 'ESCALOPE', f: ['Carne', 'Empanado', 'Milanesa', 'Filete'] },
      { w: 'POLLO ASADO', f: ['Domingo', 'Horno', 'Piel crujiente', 'Patatas'] },
      { w: 'BACON', f: ['Panceta', 'Desayuno', 'Cerdo', 'Crujiente'] },
      { w: 'GAMBAS AL AJILLO', f: ['Cazuela', 'Ajo', 'Guindilla', 'Aceite'] },
      { w: 'HUEVO FRITO', f: ['Yema', 'Puntilla', 'Mojar pan', 'Aceite'] },
      { w: 'TORTILLA FRANCESA', f: ['Huevos batidos', 'Sencilla', 'Cena', 'Doblada'] },
      { w: 'PIMIENTOS DE PADRÓN', f: ['Unos pican', 'Verdes', 'Galicia', 'Sal gorda'] },
      { w: 'PATATAS FRITAS', f: ['Aceite', 'Ketchup', 'Bolsa', 'Bastones'] },
      { w: 'PURÉ DE PATATAS', f: ['Mantequilla', 'Triturar', 'Suave', 'Guarnición'] },
      { w: 'SOPA DE FIDEOS', f: ['Caldo', 'Caliente', 'Invierno', 'Cuchara'] },
      { w: 'LENTEJAS', f: ['Hierro', 'Cuchara', 'Chorizo', 'Si quieres las comes'] },
      { w: 'GARBANZOS', f: ['Legumbres', 'Cocido', 'Redondos', 'Olla'] },
      { w: 'ALUBIAS BLANCAS', f: ['Judías', 'Fabes', 'Guiso', 'Bote'] },
      { w: 'PIÑA', f: ['Tropical', 'Corona', 'Pizza hawai', 'Amarilla'] },
      { w: 'PLÁTANO', f: ['Canarias', 'Amarillo', 'Pelar', 'Potasio'] },
      { w: 'MANZANA', f: ['Blanca Nieves', 'Roja', 'Fruta', 'Árbol'] },
      { w: 'PERA', f: ['Verde', 'Agua', 'Fruta', 'Forma'] },
      { w: 'NARANJA', f: ['Zumo', 'Vitamina C', 'Gajos', 'Cítrico'] },
      { w: 'MANDARINA', f: ['Pequeña', 'Pelar fácil', 'Olor', 'Navidad'] },
      { w: 'UVAS', f: ['Nochevieja', 'Doce', 'Racimo', 'Vino'] },
      { w: 'FRESAS', f: ['Nata', 'Rojas', 'Pequeñas', 'Primavera'] },
      { w: 'MELÓN', f: ['Jamón', 'Verano', 'Tajada', 'Dulce'] },
      { w: 'MELOCOTÓN', f: ['Piel con pelo', 'Hueso', 'Almíbar', 'Fruta'] },
      { w: 'CEREZAS', f: ['Rojas', 'Rabo', 'Verano', 'Pareja'] },
      { w: 'KIWI', f: ['Verde', 'Peludo', 'Semillas negras', 'Ácido'] },
      { w: 'LIMÓN', f: ['Ácido', 'Amarillo', 'Exprimir', 'Pescado'] },
      { w: 'MANGO', f: ['Tropical', 'Hueso grande', 'Dulce', 'Fibra'] },
      { w: 'ACEITUNAS', f: ['Olivas', 'Aceite', 'Aperitivo', 'Hueso'] },
      { w: 'ALMENDRAS', f: ['Fruto seco', 'Turrón', 'Cáscara', 'Tostadas'] },
      { w: 'NUECES', f: ['Cerebro', 'Cáscara dura', 'Cascanueces', 'Árbol'] },
      { w: 'PISTACHOS', f: ['Verdes', 'Abrir cáscara', 'Fruto seco', 'Salados'] },
      { w: 'GUSANITOS', f: ['Bolsa chuches', 'Naranjas', 'Maíz', 'Cumpleaños'] },
      { w: 'REGALIZ', f: ['Negro o rojo', 'Palo', 'Chuchería', 'Dulce'] },
      { w: 'CHICLE', f: ['Masticar', 'Pompa', 'Menta', 'Tragar'] },
      { w: 'ALGODÓN DE AZÚCAR', f: ['Feria', 'Rosa', 'Palo', 'Pegajoso'] },
      { w: 'TÉ VERDE', f: ['Infusión', 'Hierbas', 'Taza', 'Caliente'] },
      { w: 'HORCHATA', f: ['Chufa', 'Valencia', 'Fartons', 'Blanca'] },
      { w: 'GRANIZADO', f: ['Hielo picado', 'Limón', 'Pajita', 'Verano'] },
      { w: 'ZUMO DE NARANJA', f: ['Desayuno', 'Exprimir', 'Pulpa', 'Vaso'] },
      { w: 'REFRESCO DE COLA', f: ['Burbujas', 'Coca-Cola', 'Hielo', 'Lata'] },
      { w: 'CERVEZA', f: ['Caña', 'Espuma', 'Cebada', 'Bar'] },
      { w: 'SIDRA', f: ['Asturias', 'Escanciar', 'Manzana', 'Vaso ancho'] },
      { w: 'SANGRÍA', f: ['Vino', 'Fruta', 'Jarra', 'Verano'] },
      { w: 'TINTO DE VERANO', f: ['Vino', 'Gaseosa', 'Limón', 'Terraza'] },
      { w: 'VINO TINTO', f: ['Copa', 'Uva', 'Botella', 'Rioja'] },
      { w: 'CAVA', f: ['Brindis', 'Burbujas', 'Navidad', 'Corcho'] },
      { w: 'MOJITO', f: ['Hierbabuena', 'Ron', 'Lima', 'Azúcar moreno'] },
      { w: 'MERLUZA', f: ['Pescado blanco', 'Plancha', 'Rebozada', 'Espinas'] },
      { w: 'BACALAO', f: ['Salazón', 'Semana Santa', 'Pil pil', 'Pescado'] },
      { w: 'CANELONES', f: ['San Esteban', 'Pasta rellena', 'Bechamel', 'Gratinado'] },
      { w: 'GUACAMOLE', f: ['Aguacate', 'Cilantro', 'Nachos', 'Verde'] },
      { w: 'CREPE', f: ['Nutella', 'Masa fina', 'Francia', 'Sartén'] },
      { w: 'FOCACCIA', f: ['Pan italiano', 'Romero', 'Aceite de oliva', 'Horno'] }
    ]
  },
  {
    categoryKey: 'objects',
    categoryName: 'Objetos',
    idPrefix: 'obj',
    words: [
      { w: 'PARAGUAS', f: ['Lluvia', 'Agua', 'Mojarse', 'Abrir'] },
      { w: 'MARTILLO', f: ['Clavo', 'Golpear', 'Herramienta', 'Pared'] },
      { w: 'DESTORNILLADOR', f: ['Tornillo', 'Girar', 'Punta', 'Herramienta'] },
      { w: 'ASPIRADORA', f: ['Polvo', 'Limpiar', 'Suelo', 'Ruido'] },
      { w: 'MICROONDAS', f: ['Calentar', 'Comida', 'Horno', 'Cocina'] },
      { w: 'NEVERA', f: ['Frío', 'Hielo', 'Comida', 'Abrir'] },
      { w: 'LAVADORA', f: ['Ropa', 'Lavar', 'Detergente', 'Girar'] },
      { w: 'ALMOHADA', f: ['Cama', 'Dormir', 'Cabeza', 'Funda'] },
      { w: 'ESPEJO', f: ['Reflejo', 'Mirarse', 'Cristal', 'Cara'] },
      { w: 'LINTERNA', f: ['Luz', 'Oscuridad', 'Pilas', 'Noche'] },
      { w: 'MOCHILA', f: ['Espalda', 'Libros', 'Colegio', 'Cremallera'] },
      { w: 'MALETA', f: ['Viaje', 'Ropa', 'Aeropuerto', 'Ruedas'] },
      { w: 'CANDADO', f: ['Llave', 'Cerrar', 'Seguridad', 'Bicicleta'] },
      { w: 'RELOJ DE PARED', f: ['Hora', 'Agujas', 'Tic tac', 'Colgar'] },
      { w: 'CALCULADORA', f: ['Números', 'Sumar', 'Pantalla', 'Matemáticas'] },
      { w: 'TIJERAS', f: ['Cortar', 'Papel', 'Pelo', 'Hojas'] },
      { w: 'GRAPADORA', f: ['Grapas', 'Papel', 'Unir', 'Oficina'] },
      { w: 'CEPILLO DE DIENTES', f: ['Boca', 'Pasta', 'Lavarse', 'Dientes'] },
      { w: 'CARGADOR', f: ['Móvil', 'Cable', 'Enchufe', 'Batería'] },
      { w: 'AURICULARES', f: ['Música', 'Oreja', 'Escuchar', 'Sonido'] },
      { w: 'MANDO A DISTANCIA', f: ['Tele', 'Canal', 'Botones', 'Sofá'] },
      { w: 'EXTINTOR', f: ['Fuego', 'Apagar', 'Humo', 'Rojo'] },
      { w: 'BRÚJULA', f: ['Norte', 'Aguja', 'Orientarse', 'Mapa'] },
      { w: 'TELESCOPIO', f: ['Estrellas', 'Mirar', 'Espacio', 'Planeta'] },
      { w: 'SACACORCHOS', f: ['Vino', 'Botella', 'Abrir', 'Tapa'] },
      { w: 'ABRELATAS', f: ['Lata', 'Conservas', 'Metal', 'Cocina'] },
      { w: 'SARTÉN', f: ['Freír', 'Mango', 'Aceite', 'Tortilla'] },
      { w: 'OLLA EXPRÉS', f: ['Presión', 'Guisar', 'Válvula', 'Vapor'] },
      { w: 'CUCHILLO', f: ['Cortar', 'Filo', 'Carne', 'Tenedor'] },
      { w: 'TENEDOR', f: ['Pinchos', 'Comer', 'Plato', 'Cuchara'] },
      { w: 'CUCHARA', f: ['Sopa', 'Comer', 'Líquido', 'Postre'] },
      { w: 'PLATO LLANO', f: ['Comida', 'Cerámica', 'Mesa', 'Redondo'] },
      { w: 'VASO DE CRISTAL', f: ['Agua', 'Beber', 'Romper', 'Transparente'] },
      { w: 'TAZA', f: ['Café', 'Asa', 'Desayuno', 'Caliente'] },
      { w: 'TERMO', f: ['Calor', 'Frío', 'Líquido', 'Botella'] },
      { w: 'FIAMBRERA / TUPPER', f: ['Plástico', 'Comida', 'Tapa', 'Guardar'] },
      { w: 'SERVILLETA', f: ['Papel', 'Limpiar boca', 'Mesa', 'Comer'] },
      { w: 'ESCOBA', f: ['Barrer', 'Suelo', 'Palo', 'Polvo'] },
      { w: 'FREGONA', f: ['Cubo', 'Agua', 'Fregar', 'Suelo'] },
      { w: 'RECOGEDOR', f: ['Basura', 'Escoba', 'Polvo', 'Pala'] },
      { w: 'PLANCHA DE ROPA', f: ['Arrugas', 'Calor', 'Camisa', 'Vapor'] },
      { w: 'SECADOR DE PELO', f: ['Aire caliente', 'Bañarse', 'Pelo', 'Enchufe'] },
      { w: 'DESPERTADOR', f: ['Alarma', 'Mañana', 'Dormir', 'Hora'] },
      { w: 'BÁSCULA', f: ['Peso', 'Kilos', 'Baño', 'Pesar'] },
      { w: 'VENTILADOR', f: ['Aire', 'Calor', 'Aspas', 'Verano'] },
      { w: 'CALEFACTOR', f: ['Frío', 'Invierno', 'Calor', 'Estufa'] },
      { w: 'FLEXO', f: ['Lámpara', 'Estudiar', 'Mesa', 'Luz'] },
      { w: 'BOMBILLA', f: ['Luz', 'Casquillo', 'Techo', 'Enroscar'] },
      { w: 'VELA', f: ['Cera', 'Llama', 'Fuego', 'Cumpleaños'] },
      { w: 'MECHERO', f: ['Fuego', 'Encender', 'Gas', 'Cigarro'] },
      { w: 'CERILLAS', f: ['Fósforo', 'Madera', 'Fricción', 'Caja'] },
      { w: 'CHUBASQUERO', f: ['Lluvia', 'Impermeable', 'Chaqueta', 'Mojarse'] },
      { w: 'GAFAS DE SOL', f: ['Ojos', 'Verano', 'Oscuras', 'Lentes'] },
      { w: 'CARTERA', f: ['Dinero', 'Tarjetas', 'Billetes', 'Bolsillo'] },
      { w: 'LLAVERO', f: ['Llaves', 'Cerradura', 'Anilla', 'Bolsillo'] },
      { w: 'LIBRETA', f: ['Hojas', 'Escribir', 'Apuntes', 'Líneas'] },
      { w: 'BOLÍGRAFO', f: ['Tinta', 'Escribir', 'Bic', 'Papel'] },
      { w: 'GOMA DE BORRAR', f: ['Borrar', 'Lápiz', 'Milan', 'Colegio'] },
      { w: 'SACAPUNTAS', f: ['Lápiz', 'Mina', 'Afeitar', 'Virutas'] },
      { w: 'REGLA', f: ['Centímetros', 'Línea recta', 'Medir', 'Plástico'] },
      { w: 'CINTA ADHESIVA / CELO', f: ['Pegar', 'Rollo', 'Transparente', 'Tijeras'] },
      { w: 'PEGAMENTO EN BARRA', f: ['Pritt', 'Papel', 'Pegar', 'Barra'] },
      { w: 'CHINCHETA', f: ['Corcho', 'Pinchar', 'Pared', 'Cartel'] },
      { w: 'CLIP DE PAPEL', f: ['Sujetar', 'Metal', 'Hojas', 'Doblar'] },
      { w: 'BUZÓN', f: ['Cartas', 'Correos', 'Ranura', 'Portal'] },
      { w: 'SELLO', f: ['Pegar', 'Carta', 'Correos', 'Estampilla'] },
      { w: 'CALENDARIO', f: ['Meses', 'Días', 'Año', 'Pared'] },
      { w: 'ESTUCHE', f: ['Lápices', 'Cremallera', 'Colegio', 'Bolígrafos'] },
      { w: 'PRISMÁTICOS', f: ['Lejos', 'Ojos', 'Aumentar', 'Mirar'] },
      { w: 'MICROSCOPIO', f: ['Pequeño', 'Bacterias', 'Laboratorio', 'Lente'] },
      { w: 'LUPA', f: ['Aumento', 'Detective', 'Sherlock', 'Cristal'] },
      { w: 'CINTA MÉTRICA', f: ['Medir', 'Metros', 'Enrollar', 'Costura'] },
      { w: 'ALICATES', f: ['Apretar', 'Cortar alambre', 'Herramienta', 'Pinza'] },
      { w: 'LLAVE INGLESA', f: ['Tuerca', 'Girar', 'Fontanero', 'Herramienta'] },
      { w: 'SIERRA / SERRUCHO', f: ['Madera', 'Dientes', 'Cortar', 'Carpintero'] },
      { w: 'CLAVO', f: ['Martillo', 'Metal', 'Punta', 'Pared'] },
      { w: 'TORNILLO', f: ['Rosca', 'Destornillador', 'Girar', 'Pared'] },
      { w: 'ESCALERA DE MANO', f: ['Subir', 'Peldaños', 'Pintar', 'Alto'] },
      { w: 'MANGUERA', f: ['Agua', 'Jardín', 'Regar', 'Tubo'] },
      { w: 'REGADERA', f: ['Plantas', 'Agua', 'Flor', 'Pitorro'] },
      { w: 'CARRETILLA', f: ['Rueda', 'Obra', 'Cargar', 'Tierra'] },
      { w: 'PALA', f: ['Cavar', 'Tierra', 'Playa', 'Arena'] },
      { w: 'SILBATO', f: ['Pitar', 'Árbitro', 'Soplar', 'Sonido'] },
      { w: 'MEGÁFONO', f: ['Gritar', 'Voz', 'Volumen', 'Cono'] },
      { w: 'MICRÓFONO', f: ['Cantar', 'Voz', 'Escenario', 'Hablar'] },
      { w: 'CÁMARA DE FOTOS', f: ['Foto', 'Flash', 'Disparar', 'Lente'] },
      { w: 'TRÍPODE', f: ['Tres patas', 'Cámara', 'Sujetar', 'Foto'] },
      { w: 'PARACAÍDAS', f: ['Avión', 'Saltar', 'Cielo', 'Caer'] },
      { w: 'FLOTADOR', f: ['Piscina', 'Playa', 'Agua', 'Inflar'] },
      { w: 'SEMÁFORO', f: ['Rojo', 'Verde', 'Coches', 'Calle'] },
      { w: 'CAMPANA', f: ['Iglesia', 'Sonar', 'Metal', 'Tolón'] },
      { w: 'PIZARRA', f: ['Tiza', 'Colegio', 'Borrar', 'Profesor'] },
      { w: 'TALADRO', f: ['Agujero', 'Pared', 'Broca', 'Ruido'] }
    ]
  },
  {
    categoryKey: 'places',
    categoryName: 'Lugares',
    idPrefix: 'lug',
    words: [
      { w: 'PLAYA', f: ['Arena', 'Mar', 'Olas', 'Sol'] },
      { w: 'MONTAÑA', f: ['Nieve', 'Subir', 'Cima', 'Escalar'] },
      { w: 'BOSQUE', f: ['Árboles', 'Lobos', 'Madera', 'Senderismo'] },
      { w: 'DESIERTO', f: ['Arena', 'Calor', 'Camellos', 'Dunas'] },
      { w: 'ISLA DESIERTA', f: ['Náufrago', 'Mar', 'Palmera', 'Aislado'] },
      { w: 'VOLCÁN', f: ['Lava', 'Fuego', 'Erupción', 'Cráter'] },
      { w: 'CUEVA', f: ['Oscuro', 'Murciélagos', 'Rocas', 'Cueva'] },
      { w: 'CASCADA', f: ['Agua caer', 'Río', 'Catarata', 'Salto'] },
      { w: 'LAGO', f: ['Agua dulce', 'Monstruo', 'Peces', 'Barca'] },
      { w: 'POLO NORTE', f: ['Hielo', 'Frío', 'Papá Noel', 'Oso polar'] },
      { w: 'SELVA TROPICAL', f: ['Vegetación', 'Lluvia', 'Monos', 'Amazonas'] },
      { w: 'MUSEO', f: ['Cuadros', 'Arte', 'Pinturas', 'Silencio'] },
      { w: 'BIBLIOTECA', f: ['Libros', 'Silencio', 'Estudiar', 'Leer'] },
      { w: 'CINE', f: ['Palomitas', 'Película', 'Pantalla grande', 'Butacas'] },
      { w: 'TEATRO', f: ['Actores', 'Escenario', 'Telón', 'Obra'] },
      { w: 'CIRCO', f: ['Carpa', 'Payasos', 'Trapecistas', 'Espectáculo'] },
      { w: 'PARQUE DE ATRACCIONES', f: ['Montaña rusa', 'Noria', 'Entrada', 'Diversión'] },
      { w: 'ZOOLÓGICO', f: ['Animales', 'Jaulas', 'Visitar', 'Fieras'] },
      { w: 'ACUARIO', f: ['Peces', 'Tiburones', 'Cristal', 'Agua'] },
      { w: 'ESTADIO DE FÚTBOL', f: ['Césped', 'Gradas', 'Goles', 'Partido'] },
      { w: 'GIMNASIO', f: ['Pesas', 'Músculos', 'Sudar', 'Entrenar'] },
      { w: 'PISCINA MUNICIPAL', f: ['Bañador', 'Cloro', 'Nadar', 'Trampolín'] },
      { w: 'PISTA DE PATINAJE', f: ['Hielo', 'Patines', 'Frío', 'Deslizarse'] },
      { w: 'BOLERA', f: ['Bolos', 'Bola pesada', 'Pleno', 'Zapatos'] },
      { w: 'DISCOTECA', f: ['Bailar', 'Música alta', 'Copas', 'Noche'] },
      { w: 'BAR DE TAPAS', f: ['Cañas', 'Barra', 'Tapas', 'Camarero'] },
      { w: 'RESTAURANTE', f: ['Comer', 'Carta', 'Mesa', 'Camarero'] },
      { w: 'CAFETERÍA', f: ['Café', 'Desayuno', 'Tarta', 'Camarero'] },
      { w: 'PANADERÍA', f: ['Pan', 'Barra', 'Horno', 'Olor'] },
      { w: 'SUPERMERCADO', f: ['Carro', 'Comprar', 'Cajas', 'Pasillos'] },
      { w: 'MERCADILLO', f: ['Puestos', 'Regatear', 'Domingo', 'Ropa barata'] },
      { w: 'CENTRO COMERCIAL', f: ['Tiendas', 'Escaleras mecánicas', 'Comprar', 'Ropa'] },
      { w: 'FARMACIA', f: ['Medicamentos', 'Cruz verde', 'Pastillas', 'Receta'] },
      { w: 'HOSPITAL', f: ['Médicos', 'Camas', 'Enfermos', 'Urgencias'] },
      { w: 'CLÍNICA DENTAL', f: ['Dientes', 'Dentista', 'Sillón', 'Boca'] },
      { w: 'COMISARÍA DE POLICÍA', f: ['Policías', 'Denuncia', 'Calabozo', 'Sirena'] },
      { w: 'PARQUE DE BOMBEROS', f: ['Camión rojo', 'Barra', 'Manguera', 'Fuego'] },
      { w: 'AYUNTAMIENTO', f: ['Alcalde', 'Plaza', 'Trámites', 'Pueblo'] },
      { w: 'CATEDRAL', f: ['Iglesia', 'Campanario', 'Vidrieras', 'Curas'] },
      { w: 'CEMENTERIO', f: ['Tumbas', 'Muertos', 'Flores', 'Noche'] },
      { w: 'CASTILLO MEDIEVAL', f: ['Murallas', 'Foso', 'Rey', 'Torres'] },
      { w: 'PALACIO REAL', f: ['Reyes', 'Lujo', 'Corona', 'Salón del trono'] },
      { w: 'CÁRCEL / PRISIÓN', f: ['Rejas', 'Presos', 'Celdas', 'Guardias'] },
      { w: 'AEROPUERTO', f: ['Aviones', 'Maletas', 'Pista', 'Embarque'] },
      { w: 'ESTACIÓN DE TREN', f: ['Vías', 'Andén', 'Billetes', 'Locomotora'] },
      { w: 'PARADA DE AUTOBÚS', f: ['Marquesina', 'Esperar', 'Línea', 'Conductor'] },
      { w: 'PUERTO MARÍTIMO', f: ['Barcos', 'Muelles', 'Contenedores', 'Mar'] },
      { w: 'ESTACIÓN ESPACIAL', f: ['Astronautas', 'Órbita', 'Gravedad cero', 'Tierra'] },
      { w: 'FARO', f: ['Luz giratoria', 'Costa', 'Rocas', 'Barcos'] },
      { w: 'GASOLINERA', f: ['Gasolina', 'Manguera', 'Coche', 'Depósito'] },
      { w: 'HOTEL', f: ['Habitación', 'Recepción', 'Dormir', 'Llave'] },
      { w: 'CAMPING', f: ['Tienda de campaña', 'Saco de dormir', 'Naturaleza', 'Aire libre'] },
      { w: 'CABAÑA DE MADERA', f: ['Bosque', 'Chimenea', 'Troncos', 'Montaña'] },
      { w: 'GRANJA', f: ['Animales', 'Tractor', 'Pajar', 'Vacas'] },
      { w: 'PLAZA MAYOR', f: ['Soportales', 'Centro', 'Terrazas', 'Pueblo'] },
      { w: 'PARQUE INFANTIL', f: ['Columpios', 'Tobogán', 'Niños', 'Arena'] },
      { w: 'MIRADOR', f: ['Vistas', 'Paisaje', 'Foto', 'Altura'] },
      { w: 'PIRÁMIDES DE EGIPTO', f: ['Faraón', 'Momia', 'Desierto', 'Tumbas'] },
      { w: 'TORRE EIFFEL', f: ['París', 'Francia', 'Hierro', 'Monumento'] },
      { w: 'COLISEO ROMANO', f: ['Gladiadores', 'Roma', 'Leones', 'Ruinas'] }
    ]
  },
  {
    categoryKey: 'professions',
    categoryName: 'Profesiones',
    idPrefix: 'prof',
    words: [
      { w: 'MÉDICO', f: ['Hospital', 'Estetoscopio', 'Curar', 'Receta'] },
      { w: 'ENFERMERO', f: ['Jeringuilla', 'Cuidar', 'Hospital', 'Vendas'] },
      { w: 'CIRUJANO', f: ['Operar', 'Bisturí', 'Quirófano', 'Mascara'] },
      { w: 'BOMBERO', f: ['Fuego', 'Manguera', 'Camión', 'Apagar'] },
      { w: 'POLICÍA', f: ['Pistola', 'Sirena', 'Esposas', 'Patrulla'] },
      { w: 'DETECTIVE PRIVADO', f: ['Lupa', 'Investigar', 'Huellas', 'Gabardina'] },
      { w: 'JUEZ', f: ['Mazo', 'Tribunal', 'Juicio', 'Sentencia'] },
      { w: 'ABOGADO', f: ['Leyes', 'Defender', 'Juicio', 'Pleito'] },
      { w: 'PROFESOR', f: ['Colegio', 'Enseñar', 'Pizarra', 'Examen'] },
      { w: 'MAESTRO DE INFANTIL', f: ['Niños pequeños', 'Guardería', 'Canciones', 'Jugar'] },
      { w: 'CIENTÍFICO', f: ['Laboratorio', 'Probeta', 'Bata blanca', 'Experimento'] },
      { w: 'ASTRÓNOMO', f: ['Telescopio', 'Estrellas', 'Planetas', 'Galaxias'] },
      { w: 'ARQUEÓLOGO', f: ['Fósiles', 'Excavar', 'Huesos', 'Dinosaurios'] },
      { w: 'ARQUITECTO', f: ['Planos', 'Edificios', 'Diseñar', 'Construir'] },
      { w: 'ALBAÑIL', f: ['Ladrillos', 'Cemento', 'Obra', 'Paleta'] },
      { w: 'FONTANERO', f: ['Tuberías', 'Agua', 'Grifo', 'Desatascar'] },
      { w: 'ELECTRICISTA', f: ['Cables', 'Luz', 'Enchufes', 'Corriente'] },
      { w: 'CARPINTERO', f: ['Madera', 'Lijar', 'Mesa', 'Sierra'] },
      { w: 'PINTOR DE PAREDES', f: ['Brocha', 'Rodillo', 'Pintura', 'Color'] },
      { w: 'MECÁNICO', f: ['Coche', 'Taller', 'Motor', 'Aceite'] },
      { w: 'CERRAJERO', f: ['Llaves', 'Cerradura', 'Puerta', 'Abrir'] },
      { w: 'COCINERO / CHEF', f: ['Sartén', 'Restaurante', 'Comida', 'Gorro'] },
      { w: 'CAMARERO', f: ['Bandeja', 'Mesa', 'Servir', 'Cuenta'] },
      { w: 'PANADERO', f: ['Harina', 'Masa', 'Pan', 'Horno'] },
      { w: 'PASTELERO', f: ['Tartas', 'Dulces', 'Nata', 'Manga pastelera'] },
      { w: 'CARNICERO', f: ['Carne', 'Cuchillo grande', 'Filetes', 'Picadora'] },
      { w: 'PESCADERO', f: ['Pescado', 'Hielo', 'Limpiar espinas', 'Mostrador'] },
      { w: 'FRUTERO', f: ['Frutas', 'Verduras', 'Pesar', 'Kilos'] },
      { w: 'BARRENDERO', f: ['Calle', 'Escoba', 'Carro', 'Limpiar'] },
      { w: 'JARDINERO', f: ['Plantas', 'Cortacésped', 'Flores', 'Regar'] },
      { w: 'AGRICULTOR', f: ['Campo', 'Tractor', 'Cosecha', 'Sembrar'] },
      { w: 'VETERINARIO', f: ['Perros', 'Animales', 'Gatos', 'Clínica'] },
      { w: 'PELUQUERO', f: ['Pelo', 'Tijeras', 'Cortar', 'Peinar'] },
      { w: 'BARBERO', f: ['Barba', 'Navaja', 'Afeitar', 'Bigote'] },
      { w: 'MAQUILLADOR', f: ['Pintalabios', 'Base', 'Pinceles', 'Cara'] },
      { w: 'DENTISTA', f: ['Dientes', 'Boca', 'Caries', 'Torno'] },
      { w: 'ÓPTICO', f: ['Gafas', 'Graduar', 'Vista', 'Letras'] },
      { w: 'FARMACÉUTICO', f: ['Medicinas', 'Farmacia', 'Receta', 'Bata'] },
      { w: 'FISIOTERAPEUTA', f: ['Masaje', 'Músculos', 'Espalda', 'Huesos'] },
      { w: 'PSICÓLOGO', f: ['Diván', 'Terapia', 'Mente', 'Escuchar'] },
      { w: 'PILOTO DE AVIÓN', f: ['Volar', 'Cabina', 'Azafata', 'Aeropuerto'] },
      { w: 'AZAFATA / TCP', f: ['Avión', 'Pasajeros', 'Seguridad', 'Bebidas'] },
      { w: 'TAXISTA', f: ['Coche', 'Taxímetro', 'Calle', 'Pasajero'] },
      { w: 'CONDUCTOR DE AUTOBÚS', f: ['Billete', 'Paradas', 'Ruta', 'Volante'] },
      { w: 'MAQUINISTA DE TREN', f: ['Vías', 'Locomotora', 'Estación', 'Frenar'] },
      { w: 'CAPITÁN DE BARCO', f: ['Grumete', 'Timón', 'Mar', 'Barco'] },
      { w: 'ASTRONAUTA', f: ['Espacio', 'Luna', 'Cohete', 'Traje'] },
      { w: 'SOLDADO / MILITAR', f: ['Ejército', 'Uniforme', 'Fusil', 'Cuartel'] },
      { w: 'GUARDAESPALDAS', f: ['Proteger', 'Famoso', 'Gafas de sol', 'Seguridad'] },
      { w: 'SOCORRISTA', f: ['Piscina', 'Playa', 'Ahogarse', 'Flotador'] },
      { w: 'CARTERO', f: ['Cartas', 'Buzón', 'Repartir', 'Paquetes'] },
      { w: 'PERIODISTA', f: ['Noticias', 'Periódico', 'Entrevista', 'Micro'] },
      { w: 'FOTÓGRAFO', f: ['Cámara', 'Foto', 'Flash', 'Posar'] },
      { w: 'LOCUTOR DE RADIO', f: ['Voz', 'Micrófono', 'Emisora', 'Oyentes'] },
      { w: 'ACTOR', f: ['Película', 'Teatro', 'Papel', 'Guión'] },
      { w: 'CANTANTE', f: ['Canción', 'Voz', 'Concierto', 'Micro'] },
      { w: 'BAILARÍN', f: ['Ballet', 'Música', 'Bailar', 'Coreografía'] },
      { w: 'PAYASO', f: ['Circo', 'Nariz roja', 'Risa', 'Zapatos gigantes'] },
      { w: 'MAGO', f: ['Varita', 'Truco', 'Conejo', 'Chistera'] },
      { w: 'ÁRBITRO', f: ['Silbato', 'Tarjeta roja', 'Fútbol', 'Falta'] },
      { w: 'ENTRENADOR', f: ['Pizarra', 'Equipo', 'Estrategia', 'Gritar'] },
      { w: 'MINERO', f: ['Casco con luz', 'Carbón', 'Mina', 'Pico'] }
    ]
  },
  {
    categoryKey: 'sports',
    categoryName: 'Deportes',
    idPrefix: 'dep',
    words: [
      { w: 'FÚTBOL', f: ['Pelota', 'Gol', 'Portería', 'Once'] },
      { w: 'BALONCESTO', f: ['Canasta', 'Aro', 'Botar', 'Triples'] },
      { w: 'TENIS', f: ['Raqueta', 'Red', 'Pelota amarilla', 'Nadal'] },
      { w: 'PÁDEL', f: ['Pala', 'Pared de cristal', 'Parejas', 'Pista'] },
      { w: 'VOLEIBOL', f: ['Red', 'Manos', 'Rematar', 'Playa'] },
      { w: 'BALONMANO', f: ['Mano', 'Portería', 'Botar', 'Siete'] },
      { w: 'RUGBY', f: ['Balón ovalado', 'Placaje', 'Melé', 'Ensayo'] },
      { w: 'BÉISBOL', f: ['Bate', 'Guante', 'Bases', 'Home run'] },
      { w: 'GOLF', f: ['Hoyo', 'Palo', 'Pelota blanca', 'Tee'] },
      { w: 'NATACIÓN', f: ['Nadar', 'Piscina', 'Gorro', 'Gafas'] },
      { w: 'ATLETISMO', f: ['Correr', 'Pista', 'Salto', 'Velocidad'] },
      { w: 'CICLISMO', f: ['Bicicleta', 'Pedales', 'Tour', 'Casco'] },
      { w: 'MOTOCICLISMO', f: ['Moto', 'Circuito', 'Casco', 'Marc Márquez'] },
      { w: 'FÓRMULA 1', f: ['Coches', 'Circuito', 'Fernando Alonso', 'Boxes'] },
      { w: 'BOXEO', f: ['Guantes', 'Ring', 'K.O.', 'Puñetazo'] },
      { w: 'JUDO', f: ['Kimono', 'Cinturón negro', 'Tatamí', 'Llave'] },
      { w: 'KARATE', f: ['Patada', 'Golpe', 'Cinturón', 'Artes marciales'] },
      { w: 'ESGRIMA', f: ['Espada', 'Careta', 'Florete', 'Blanco'] },
      { w: 'ESQUÍ', f: ['Nieve', 'Palos', 'Tablas', 'Pista blanca'] },
      { w: 'SNOWBOARD', f: ['Tabla', 'Nieve', 'Descenso', 'Invierno'] },
      { w: 'PATINAJE SOBRE HIELO', f: ['Cuchillas', 'Pista fría', 'Girar', 'Salto'] },
      { w: 'SURF', f: ['Ola', 'Tabla', 'Neopreno', 'Playa'] },
      { w: 'KAYAK / PIRAGÜISMO', f: ['Remo', 'Canoa', 'Río', 'Agua'] },
      { w: 'VELA', f: ['Barco', 'Viento', 'Mar', 'Timón'] },
      { w: 'BUCEO / SUBMARINISMO', f: ['Botella de oxígeno', 'Aletas', 'Peces', 'Fondo marino'] },
      { w: 'ESCALADA', f: ['Roca', 'Arnés', 'Cuerda', 'Montaña'] },
      { w: 'SENDERISMO', f: ['Caminar', 'Montaña', 'Mochila', 'Botas'] },
      { w: 'EQUITACIÓN / HÍPICA', f: ['Caballo', 'Silla', 'Saltar vallas', 'Jinete'] },
      { w: 'GIMNASIA RÍTMICA', f: ['Cinta', 'Maza', 'Aro', 'Música'] },
      { w: 'TIRO CON ARCO', f: ['Flecha', 'Diana', 'Centro', 'Tirar'] },
      { w: 'BÁDMINTON', f: ['Volante / pluma', 'Raqueta ligera', 'Red', 'Pista'] },
      { w: 'PING-PONG / TENIS DE MESA', f: ['Pala pequeña', 'Pelota blanca', 'Mesa verde', 'Red'] },
      { w: 'WATERPOLO', f: ['Piscina', 'Gorro con orejeras', 'Balón', 'Flotar'] },
      { w: 'TRIATLÓN', f: ['Nadar', 'Bici', 'Correr', 'Resistencia'] },
      { w: 'HALTEROFILIA', f: ['Pesas', 'Barra', 'Discos', 'Fuerza'] },
      { w: 'CROSSFIT', f: ['Neumático', 'Cuerda', 'Entrenamiento', 'Sudar'] },
      { w: 'YOGA', f: ['Esterilla', 'Postura', 'Respirar', 'Paz'] },
      { w: 'BILLAR', f: ['Taco', 'Bolas', 'Troneras', 'Mesa verde'] },
      { w: 'DARDOS', f: ['Diana', 'Punta', 'Centro', 'Lanzar'] },
      { w: 'BOLOS', f: ['Pleno', 'Diez bolos', 'Pista', 'Canaleta'] },
      { w: 'FÚTBOL SALA', f: ['Cinco jugadores', 'Pabellón', 'Balón pequeño', 'Portería'] },
      { w: 'SKATEBOARD / MONOPATÍN', f: ['Tabla', 'Cuatro ruedas', 'Rampa', 'Ollie'] },
      { w: 'PARACAIDISMO', f: ['Avión', 'Cielo', 'Tirarse', 'Abrir'] }
    ]
  },
  {
    categoryKey: 'actions',
    categoryName: 'Acciones',
    idPrefix: 'act',
    words: [
      { w: 'BOSTEZAR', f: ['Sueño', 'Boca abierta', 'Cansado', 'Contagio'] },
      { w: 'ESTORNUDAR', f: ['Achsís', 'Nariz', 'Pañuelo', 'Resfriado'] },
      { w: 'RONCAR', f: ['Dormir', 'Ruido', 'Noche', 'Nariz'] },
      { w: 'SALTAR', f: ['Pies', 'Suelo', 'Aire', 'Arriba'] },
      { w: 'NADAR', f: ['Agua', 'Piscina', 'Brazadas', 'Flotar'] },
      { w: 'BAILAR', f: ['Música', 'Ritmo', 'Moverse', 'Pista'] },
      { w: 'COCINAR', f: ['Comida', 'Sartén', 'Fuego', 'Ingredientes'] },
      { w: 'APLAUDIR', f: ['Manos', 'Chocar', 'Bravo', 'Público'] },
      { w: 'SUSURRAR', f: ['Oreja', 'Bajo', 'Secreto', 'Voz'] },
      { w: 'GRITAR', f: ['Fuerte', 'Voz', 'Chillido', 'Susto'] },
      { w: 'PATINAR', f: ['Ruedas', 'Hielo', 'Deslizarse', 'Equilibrio'] },
      { w: 'ESCALAR', f: ['Montaña', 'Manos', 'Subir', 'Pared'] },
      { w: 'BUCEAR', f: ['Fondo', 'Agua', 'Gafas', 'Respirar'] },
      { w: 'HACER MALABARES', f: ['Pelotas', 'Aire', 'Circo', 'Manos'] },
      { w: 'PASEAR AL PERRO', f: ['Correa', 'Calle', 'Mascota', 'Bolsita'] },
      { w: 'INFLAR UN GLOBO', f: ['Soplar', 'Aire', 'Explotar', 'Fiesta'] },
      { w: 'HACER UNA FOTO', f: ['Cámara', 'Móvil', 'Sonreír', 'Click'] },
      { w: 'LAVARSE LOS DIENTES', f: ['Cepillo', 'Pasta', 'Espuma', 'Boca'] },
      { w: 'TOCAR LA GUITARRA', f: ['Cuerdas', 'Dedos', 'Música', 'Acordes'] },
      { w: 'GUIÑAR UN OJO', f: ['Cerrar', 'Cara', 'Cómplice', 'Pestaña'] },
      { w: 'SILBAR', f: ['Labios', 'Canción', 'Sonido', 'Boca'] },
      { w: 'TROPEZAR', f: ['Piedra', 'Caerse', 'Pie', 'Torpe'] },
      { w: 'REÍR A CARCAJADAS', f: ['Chiste', 'Gracia', 'Ja ja', 'Boca'] },
      { w: 'LLORAR', f: ['Lágrimas', 'Triste', 'Ojos', 'Pañuelo'] },
      { w: 'RASCARSE', f: ['Picar', 'Uñas', 'Piel', 'Alivio'] },
      { w: 'HACER COSQUILLAS', f: ['Risa', 'Dedos', 'Pies', 'Axilas'] },
      { w: 'MORDERSE LAS UÑAS', f: ['Nervios', 'Dientes', 'Manos', 'Dedos'] },
      { w: 'DAR UN ABRAZO', f: ['Brazos', 'Cariño', 'Pecho', 'Apretar'] },
      { w: 'CHOCAR LOS CINCO', f: ['Mano abierta', 'Amigo', 'Arriba', 'Golpe'] },
      { w: 'MANDAR UN BESO', f: ['Labios', 'Mano', 'Aire', 'Muac'] },
      { w: 'ATARSE LOS CORDONES', f: ['Zapatos', 'Lazo', 'Nudo', 'Agacharse'] },
      { w: 'FREGAR LOS PLATOS', f: ['Estropajo', 'Jabón', 'Fregadero', 'Espuma'] },
      { w: 'PLANCHAR UNA CAMISA', f: ['Calor', 'Arrugas', 'Tabla', 'Vapor'] },
      { w: 'BARRER EL SUELO', f: ['Escoba', 'Polvo', 'Recogedor', 'Limpiar'] },
      { w: 'CAMBIAR UNA BOMBILLA', f: ['Girar', 'Luz', 'Fundida', 'Techo'] },
      { w: 'LEER UN LIBRO', f: ['Páginas', 'Ojos', 'Letras', 'Historia'] },
      { w: 'CANTAR EN LA DUCHA', f: ['Agua', 'Jabón', 'Voz', 'Esponja'] },
      { w: 'MONTAR EN BICICLETA', f: ['Pedales', 'Ruedas', 'Manillar', 'Equilibrio'] },
      { w: 'TIRAR UN PENALTI', f: ['Fútbol', 'Portero', 'Balón', 'Punto blanco'] },
      { w: 'PESCAR', f: ['Caña', 'Anzuelo', 'Pez', 'Río'] },
      { w: 'COSER UN BOTÓN', f: ['Aguja', 'Hilo', 'Camisa', 'Puntada'] },
      { w: 'PINTAR UN CUADRO', f: ['Lienzo', 'Pincel', 'Colores', 'Pintura'] },
      { w: 'REGATEAR', f: ['Precio', 'Mercadillo', 'Descuento', 'Barato'] },
      { w: 'MADRUGAR', f: ['Despertador', 'Temprano', 'Mañana', 'Cama'] },
      { w: 'COTILLEAR / CHISMEAR', f: ['Secreto', 'Hablar', 'Vecina', 'Enterarse'] },
      { w: 'HACER LA CAMA', f: ['Sábanas', 'Edredón', 'Almohada', 'Ordenar'] },
      { w: 'BEBER CON PAJITA', f: ['Sorber', 'Vaso', 'Líquido', 'Tubo'] },
      { w: 'APAGAR LAS VELAS', f: ['Soplar', 'Tarta', 'Cumpleaños', 'Deseo'] },
      { w: 'PELAR UNA NARANJA', f: ['Cáscara', 'Uñas', 'Gajos', 'Cuchillo'] },
      { w: 'ABRIR UN REGALO', f: ['Papel', 'Lazo', 'Sorpresa', 'Romper'] }
    ]
  },
  {
    categoryKey: 'nature',
    categoryName: 'Naturaleza',
    idPrefix: 'nat',
    words: [
      { w: 'ARCOÍRIS', f: ['Colores', 'Cielo', 'Lluvia', 'Sol'] },
      { w: 'RELÁMPAGO / RAYO', f: ['Tormenta', 'Luz', 'Cielo', 'Trueno'] },
      { w: 'TRUENO', f: ['Sonido', 'Tormenta', 'Fuerte', 'Rayo'] },
      { w: 'TORMENTA', f: ['Lluvia', 'Nubes negras', 'Viento', 'Rayo'] },
      { w: 'GRANIZO', f: ['Hielo', 'Bolas', 'Caer del cielo', 'Romper'] },
      { w: 'NIEVE', f: ['Blanco', 'Frío', 'Invierno', 'Copos'] },
      { w: 'LLUVIA', f: ['Gotas', 'Nubes', 'Agua', 'Paraguas'] },
      { w: 'NIEBLA', f: ['Blanco', 'Ver nada', 'Humo', 'Carretera'] },
      { w: 'SOL', f: ['Luz', 'Calor', 'Día', 'Estrella'] },
      { w: 'LUNA LLENA', f: ['Noche', 'Redonda', 'Hombre lobo', 'Cielo'] },
      { w: 'ECLIPSE', f: ['Ocultar', 'Sol', 'Luna', 'Oscuridad'] },
      { w: 'ESTRELLA FUGAZ', f: ['Deseo', 'Cielo', 'Noche', 'Caer'] },
      { w: 'AURORA BOREAL', f: ['Luces verdes', 'Norte', 'Cielo nocturno', 'Polo'] },
      { w: 'VOLCÁN EN ERUPCIÓN', f: ['Lava', 'Fuego', 'Ceniza', 'Humo'] },
      { w: 'TERREMOTO', f: ['Temblores', 'Suelo', 'Grieta', 'Escala Richter'] },
      { w: 'TSUNAMI', f: ['Ola gigante', 'Mar', 'Terremoto', 'Costa'] },
      { w: 'TORNADO / HURACÁN', f: ['Viento', 'Girar', 'Embudo', 'Destruir'] },
      { w: 'GLACIAR', f: ['Hielo', 'Montaña', 'Frío', 'Deshielo'] },
      { w: 'ICEBERG', f: ['Titanic', 'Hielo', 'Flotar', 'Punta'] },
      { w: 'DUNA DE ARENA', f: ['Desierto', 'Viento', 'Montaña de arena', 'Camello'] },
      { w: 'ARRECIFE DE CORAL', f: ['Peces', 'Colores', 'Mar', 'Submarino'] },
      { w: 'PRADERA', f: ['Hierba', 'Verde', 'Flores', 'Campo'] },
      { w: 'ACANTILADO', f: ['Caída', 'Mar', 'Rocas', 'Altura'] },
      { w: 'BOSQUE DE PINOS', f: ['Piñas', 'Árboles', 'Resina', 'Verde'] },
      { w: 'GÉISER', f: ['Agua caliente', 'Chorro', 'Suelo', 'Vapor'] },
      { w: 'ROBLE', f: ['Bellotas', 'Árbol fuerte', 'Tronco', 'Hojas'] },
      { w: 'PALMERA', f: ['Cocos', 'Playa', 'Hojas grandes', 'Oasis'] },
      { w: 'GIRASOL', f: ['Amarillo', 'Girar', 'Pipas', 'Sol'] },
      { w: 'ROSA', f: ['Espinas', 'Roja', 'Flor', 'Olor'] },
      { w: 'MARGARITA', f: ['Pétalos', 'Me quiere no me quiere', 'Blanca', 'Centro amarillo'] },
      { w: 'AMAPOLA', f: ['Roja', 'Campo', 'Trigo', 'Flor'] },
      { w: 'CACTUS', f: ['Pinchos', 'Desierto', 'Verde', 'Agua'] }
    ]
  },
  {
    categoryKey: 'moviesTv',
    categoryName: 'Cine y Televisión',
    idPrefix: 'cine',
    words: [
      { w: 'HARRY POTTER', f: ['Mago', 'Cicatriz', 'Hogwarts', 'Varita'] },
      { w: 'STAR WARS', f: ['Espada láser', 'Darth Vader', 'Fuerza', 'Galaxia'] },
      { w: 'SHREK', f: ['Ogro', 'Verde', 'Asno', 'Pantano'] },
      { w: 'TITANIC', f: ['Barco', 'Iceberg', 'Jack y Rose', 'Hundirse'] },
      { w: 'AVATAR', f: ['Azules', 'Pandora', 'Alienígenas', 'James Cameron'] },
      { w: 'FROZEN', f: ['Elsa', 'Hielo', 'Let it go', 'Muñeco de nieve'] },
      { w: 'TOY STORY', f: ['Woody', 'Buzz Lightyear', 'Juguetes', 'Vaquero'] },
      { w: 'CARS', f: ['Rayo McQueen', 'Coches', 'Rojo', 'Carrera'] },
      { w: 'MATRIX', f: ['Pastilla roja', 'Neo', 'Balas', 'Cables'] },
      { w: 'JURASSIC PARK', f: ['Dinosaurios', 'T-Rex', 'Isla', 'Ámbar'] },
      { w: 'EL SEÑOR DE LOS ANILLOS', f: ['Anillo', 'Frodo', 'Mordor', 'Gollum'] },
      { w: 'SPIDER-MAN', f: ['Telaraña', 'Araña', 'Peter Parker', 'Rojo y azul'] },
      { w: 'BATMAN', f: ['Murciélago', 'Gotham', 'Bruce Wayne', 'Joker'] },
      { w: 'SUPERMAN', f: ['Kryptonita', 'Capa roja', 'Volar', 'Clark Kent'] },
      { w: 'JOKER', f: ['Risa', 'Pelo verde', 'Payaso', 'Enemigo de Batman'] },
      { w: 'LOS SIMPSON', f: ['Amarillos', 'Homer', 'Bart', 'Springfield'] },
      { w: 'BOB ESPONJA', f: ['Fondo de Bikini', 'Pantalones cuadrados', 'Piña', 'Hamburguesa'] },
      { w: 'STRANGER THINGS', f: ['Once (Eleven)', 'Demogorgon', 'Mundo del revés', 'Bicis'] },
      { w: 'MIÉRCOLES / WEDNESDAY', f: ['Familia Addams', 'Cosas', 'Trenzas', 'Baile'] },
      { w: 'BREAKING BAD', f: ['Química', 'Walter White', 'Cristal azul', 'Heisenberg'] },
      { w: 'FRIENDS', f: ['Sofá', 'Cafetería', 'Nueva York', 'Central Perk'] },
      { w: 'FUTURAMA', f: ['Fry', 'Bender', 'Robot', 'Futuro'] },
      { w: 'LOS VENGADORES / AVENGERS', f: ['Marvel', 'Thanos', 'Gemas', 'Superhéroes'] },
      { w: 'PIRATAS DEL CARIBE', f: ['Jack Sparrow', 'Barco', 'Ron', 'Perla Negra'] },
      { w: 'EL REY LEÓN', f: ['Simba', 'Mufasa', 'Hakuna Matata', 'Sabana'] },
      { w: 'BUSCANDO A NEMO', f: ['Pez payaso', 'Dory', 'Océano', 'Australia'] },
      { w: 'MONSTRUOS S.A.', f: ['Puertas', 'Sully', 'Mike Wazowski', 'Gritos'] },
      { w: 'REGRESO AL FUTURO', f: ['Delorean', 'Marty McFly', 'Doc', 'Viajar en el tiempo'] },
      { w: 'INDIANA JONES', f: ['Látigo', 'Sombrero', 'Arqueólogo', 'Roca gigante'] },
      { w: 'TERMINATOR', f: ['Sayonara baby', 'Robot', 'Schwarzenegger', 'Volveré'] },
      { w: 'CAZAFANTASMAS', f: ['Mochilas de protones', 'Fantasmas', 'Moquete', 'Coche blanco'] },
      { w: 'MEN IN BLACK', f: ['Traje negro', 'Alienígenas', 'Borrar memoria', 'Will Smith'] },
      { w: 'LA CASA DE PAPEL', f: ['Moneda y Timbre', 'Mono rojo', 'Máscara de Dalí', 'El Profesor'] },
      { w: 'JUEGO DE TRONOS', f: ['Trono de hierro', 'Dragones', 'Invierno', 'Daenerys'] },
      { w: 'PEAKY BLINDERS', f: ['Gorra con cuchilla', 'Thomas Shelby', 'Birmingham', 'Gangsters'] },
      { w: 'EL JUEGO DEL CALAMAR', f: ['Luz roja luz verde', 'Muñeca gigante', 'Chándal verde', 'Corea'] },
      { w: 'DRAGON BALL', f: ['Goku', 'Bolas de dragón', 'Kamehameha', 'Super Saiyan'] },
      { w: 'POKÉMON (SERIE)', f: ['Ash Ketchum', 'Pikachu', 'Pokéball', 'Hazte con todos'] },
      { w: 'DORAEMON', f: ['Gato cósmico', 'Bolsillo mágico', 'Nobita', 'Dorayaki'] },
      { w: 'SCOOBY-DOO', f: ['Perro miedoso', 'Furgoneta', 'Misterio', 'Galletas'] }
    ]
  },
  {
    categoryKey: 'videogames',
    categoryName: 'Videojuegos',
    idPrefix: 'vid',
    words: [
      { w: 'MINECRAFT', f: ['Bloques', 'Creeper', 'Picar', 'Steve'] },
      { w: 'FORTNITE', f: ['Battle Royale', 'Autobús', 'Bailes', 'Pico'] },
      { w: 'ROBLOX', f: ['Avatares', 'Monedas Robux', 'Juegos', 'Mundos'] },
      { w: 'TETRIS', f: ['Piezas', 'Líneas', 'Encajar', 'Rusia'] },
      { w: 'PAC-MAN', f: ['Comer cocos', 'Fantasmas', 'Laberinto', 'Amarillo'] },
      { w: 'POKÉMON', f: ['Pikachu', 'Gimnasios', 'Capturar', 'Nintendo'] },
      { w: 'SUPER MARIO BROS', f: ['Fontanero', 'Champiñón', 'Princesa Peach', 'Bowser'] },
      { w: 'LUIGI', f: ['Hermano verde', 'Aspiradora', 'Fantasmas', 'Mansion'] },
      { w: 'SONIC THE HEDGEHOG', f: ['Erizo azul', 'Anillos dorados', 'Rápido', 'Sega'] },
      { w: 'THE LEGEND OF ZELDA', f: ['Link', 'Espada Maestra', 'Trifuerza', 'Princesa'] },
      { w: 'MARIO KART', f: ['Coches', 'Caparazón azul', 'Plátano', 'Pista arcoíris'] },
      { w: 'GRAND THEFT AUTO (GTA)', f: ['Robar coches', 'Policía', 'Estrellas', 'Mundo abierto'] },
      { w: 'THE SIMS', f: ['Rombo verde', 'Casa', 'Vida virtual', 'Simlish'] },
      { w: 'AMONG US', f: ['Impostor', 'Nave', 'Tripulante', 'Votar'] },
      { w: 'FALL GUYS', f: ['Judías', 'Obstáculos', 'Corona', 'Carreras'] },
      { w: 'ROCKET LEAGUE', f: ['Coches', 'Fútbol', 'Turbo', 'Balón gigante'] },
      { w: 'BRAWL STARS', f: ['Móvil', 'Gemas', 'Personajes', 'Supercell'] },
      { w: 'CLASH ROYALE', f: ['Torres', 'Cartas', 'Elixir', 'Rey'] },
      { w: 'VALORANT', f: ['Disparos', 'Agentes', 'Spike', 'Riot Games'] },
      { w: 'OVERWATCH', f: ['Héroes', 'Payload', 'Tracer', 'Blizzard'] },
      { w: 'TERRARIA', f: ['2D', 'Bloques', 'Cavar', 'Jefes'] },
      { w: 'SKYRIM', f: ['Dragones', 'Sangre de dragón', 'Nieve', 'Gritar'] },
      { w: 'PORTAL', f: ['Portales azul y naranja', 'GLaDOS', 'Tarta', 'Puzles'] },
      { w: 'DOOM', f: ['Demonios', 'Infierno', 'Escopeta', 'Música metal'] },
      { w: 'TEKKEN', f: ['Pelea', 'Torneo', 'Kazuya', 'Puño de hierro'] },
      { w: 'STREET FIGHTER', f: ['Hadouken', 'Ryu', 'Ken', 'Pelea'] },
      { w: 'FIFA / EA SPORTS FC', f: ['Fútbol', 'Ultimate Team', 'Sobres', 'Goles'] },
      { w: 'CALL OF DUTY', f: ['Guerra', 'Soldados', 'Zombis', 'Disparos'] },
      { w: 'LEAGUE OF LEGENDS (LOL)', f: ['MOBA', 'Grieta del Invocador', 'Torres', 'Minions'] },
      { w: 'GOD OF WAR', f: ['Kratos', 'Hacha', 'Hijo / Boy', 'Mitología'] },
      { w: 'RED DEAD REDEMPTION', f: ['Vaqueros', 'Caballos', 'Oeste', 'Arthur Morgan'] },
      { w: 'THE LAST OF US', f: ['Hongos', 'Chasqueadores', 'Joel y Ellie', 'Infección'] },
      { w: 'ASSASSIN\'S CREED', f: ['Capucha', 'Hoja oculta', 'Salto de fe', 'Historia'] },
      { w: 'ELDEN RING', f: ['Difícil', 'Jefes', 'Caballo espiritual', 'Tierras Intermedias'] },
      { w: 'ANIMAL CROSSING', f: ['Isla', 'Tom Nook', 'Peces e insectos', 'Bayas'] },
      { w: 'SUPER SMASH BROS', f: ['Luchar', 'Nintendo', 'Echar del escenario', 'Porcentaje'] },
      { w: 'CRASH BANDICOOT', f: ['Marsupial', 'Manzanas', 'Cajas de madera', 'Máscara Aku Aku'] },
      { w: 'RESIDENT EVIL', f: ['Zombis', 'Mansión', 'Virus T', 'Miedo'] },
      { w: 'SUBWAY SURFERS', f: ['Correr', 'Trenes', 'Monedas', 'Inspector'] },
      { w: 'CANDY CRUSH', f: ['Caramelos', 'Juntar tres', 'Azúcar', 'Niveles'] }
    ]
  }
];
