// Part 2: Categories 11 to 20 for Palabra Secreta
export const part2Categories = [
  {
    categoryKey: 'characters',
    categoryName: 'Personajes',
    idPrefix: 'per',
    words: [
      { w: 'SHERLOCK HOLMES', f: ['Lupa', 'Watson', 'Elemental', 'Londres'] },
      { w: 'DRÁCULA', f: ['Vampiro', 'Sangre', 'Colmillos', 'Transilvania'] },
      { w: 'FRANKENSTEIN', f: ['Monstruo', 'Tornillos cuello', 'Científico', 'Electricidad'] },
      { w: 'TARZÁN', f: ['Lianas', 'Selva', 'Monos', 'Grito'] },
      { w: 'ROBIN HOOD', f: ['Arco', 'Robar a ricos', 'Bosque Sherwood', 'Verde'] },
      { w: 'DON QUIJOTE DE LA MANCHA', f: ['Molinos', 'Caballero', 'Rocinante', 'Loco'] },
      { w: 'SANCHO PANZA', f: ['Escudero', 'Burro', 'Gordo', 'Refranes'] },
      { w: 'CAPERUCITA ROJA', f: ['Lobo', 'Abuelita', 'Cesta', 'Capa roja'] },
      { w: 'BLANCANIEVES', f: ['Siete enanitos', 'Manzana', 'Espejo', 'Madrastra'] },
      { w: 'CENICIENTA', f: ['Zapato de cristal', 'Calabaza', 'Medianoche', 'Madrastra'] },
      { w: 'PINOCHO', f: ['Nariz', 'Mentira', 'Madera', 'Gepetto'] },
      { w: 'PETER PAN', f: ['Nunca Jamás', 'Volar', 'Sombra', 'Campanilla'] },
      { w: 'ALICIA EN EL PAÍS DE LAS MARAVILLAS', f: ['Conejo blanco', 'Madriguera', 'Sombrerero', 'Cartas'] },
      { w: 'PAPÁ NOEL / SANTA CLAUS', f: ['Trineo', 'Renos', 'Regalos', 'Barba blanca'] },
      { w: 'REYES MAGOS', f: ['Camellos', 'Corona', 'Oro incienso mirra', 'Enero'] },
      { w: 'RATONCITO PÉREZ', f: ['Diente', 'Almohada', 'Moneda', 'Ratón'] },
      { w: 'CAPITÁN GARFIO', f: ['Mano', 'Pirata', 'Cocodrilo con reloj', 'Peter Pan'] },
      { w: 'ALADDÍN', f: ['Alfombra mágica', 'Lámpara', 'Genio', 'Jasmine'] },
      { w: 'GENIO DE LA LÁMPARA', f: ['Tres deseos', 'Azul', 'Frotar', 'Humor'] },
      { w: 'JAMES BOND (007)', f: ['Espía', 'Martini', 'Licencia para matar', 'Aston Martin'] },
      { w: 'DARTH VADER', f: ['Yo soy tu padre', 'Casco negro', 'Respiración', 'Lado oscuro'] },
      { w: 'YODA', f: ['Verde', 'Pequeño', 'Hablar al revés', 'Maestro Jedi'] },
      { w: 'GANDALF', f: ['Mago', 'Barba blanca', 'No pasarás', 'Bastón'] },
      { w: 'GOLLUM', f: ['Mi tesoro', 'Anillo', 'Criatura', 'Sméagol'] },
      { w: 'VOLDEMORT', f: ['Sin nariz', 'El que no debe ser nombrado', 'Varita de Saúco', 'Mortífagos'] },
      { w: 'HERMIONE GRANGER', f: ['Libros', 'Lista', 'Gira-tiempo', 'Gryffindor'] },
      { w: 'MICKEY MOUSE', f: ['Orejas redondas', 'Pantalones rojos', 'Disney', 'Ratón'] },
      { w: 'PATO DONALD', f: ['Grajear', 'Gorra marinero', 'Enfado', 'Pato'] },
      { w: 'BUZZ LIGHTYEAR', f: ['Hasta el infinito', 'Espacio', 'Alas', 'Astronauta'] },
      { w: 'HOMER SIMPSON', f: ['Donuts', 'Cerveza Duff', 'Nuclear', 'Mosquis'] },
      { w: 'BART SIMPSON', f: ['Monopatín', 'Pelo pincho', 'Multiplícate por cero', 'Tirachinas'] },
      { w: 'PIKACHU', f: ['Rayo', 'Amarillo', 'Pika pika', 'Mejillas rojas'] },
      { w: 'IRON MAN', f: ['Armadura roja', 'Tony Stark', 'Reactor en el pecho', 'Millonario'] },
      { w: 'THOR', f: ['Martillo', 'Dios del trueno', 'Rayo', 'Asgard'] },
      { w: 'HULK', f: ['Verde', 'Furia', 'Aplastar', 'Músculos'] },
      { w: 'HARLEY QUINN', f: ['Bate de béisbol', 'Pelo coletas', 'Joker', 'Payasa'] },
      { w: 'WONDER WOMAN', f: ['Lazo de la verdad', 'Pulseras', 'Amazona', 'Corona'] },
      { w: 'TARANTINO', f: ['Director', 'Pulp Fiction', 'Pies', 'Violencia'] },
      { w: 'CLEOPATRA', f: ['Egipto', 'Reina', 'Serpiente', 'Pirámides'] },
      { w: 'JULIO CÉSAR', f: ['Emperador', 'Roma', 'Laurel', 'Tú también Bruto'] }
    ]
  },
  {
    categoryKey: 'technology',
    categoryName: 'Tecnología',
    idPrefix: 'tec',
    words: [
      { w: 'SMARTPHONE / MÓVIL', f: ['Pantalla táctil', 'Llamar', 'Apps', 'Bolsillo'] },
      { w: 'ORDENADOR PORTÁTIL', f: ['Teclado', 'Pantalla', 'Batería', 'Ratón'] },
      { w: 'TABLET', f: ['Pantalla plana', 'Dedos', 'iPad', 'Grande'] },
      { w: 'SMARTWATCH / RELOJ INTELIGENTE', f: ['Muñeca', 'Pasos', 'Pulsaciones', 'Hora'] },
      { w: 'MEMORIA USB / PENDRIVE', f: ['Guardar archivos', 'Conectar', 'Pincho', 'Puerto'] },
      { w: 'DISCO DURO', f: ['Gigabytes', 'Almacenamiento', 'Memoria', 'Guardar'] },
      { w: 'ROUTER WI-FI', f: ['Internet', 'Antenas', 'Contraseña', 'Luces verdes'] },
      { w: 'DRON', f: ['Volar', 'Hélices', 'Cámara aérea', 'Mando'] },
      { w: 'GAFAS DE REALIDAD VIRTUAL', f: ['Ojos', 'Metaverso', 'Visor', 'Inmersión'] },
      { w: 'IMPRESORA 3D', f: ['Filamento', 'Plástico', 'Capas', 'Fabricar'] },
      { w: 'CONSOLA DE VIDEOJUEGOS', f: ['PlayStation', 'Xbox', 'Mando', 'Jugar'] },
      { w: 'BATERÍA PORTÁTIL / POWERBANK', f: ['Cargar móvil', 'Cable', 'Sin batería', 'Enchufe'] },
      { w: 'CÓDIGO QR', f: ['Cuadrado blanco y negro', 'Escanear', 'Cámara', 'Menú del bar'] },
      { w: 'ROBOT ASPIRADOR / ROOMBA', f: ['Suelo', 'Redondo', 'Limpiar solo', 'Cargador'] },
      { w: 'SATÉLITE ARTIFICIAL', f: ['Órbita', 'Espacio', 'Señal', 'Antena'] },
      { w: 'WEBCAM / CÁMARA WEB', f: ['Videollamada', 'Ordenador', 'Grabar', 'Lente'] },
      { w: 'TARJETA GRÁFICA', f: ['FPS', 'Nvidia', 'Videojuegos', 'Potencia'] },
      { w: 'INTELIGENCIA ARTIFICIAL', f: ['ChatGPT', 'Robots', 'Algoritmo', 'Aprender'] },
      { w: 'GPS / NAVEGADOR', f: ['Mapa', 'Girar a la derecha', 'Ruta', 'Coche'] },
      { w: 'BLUETOOTH', f: ['Sin cables', 'Conectar', 'Auriculares', 'Sincronizar'] },
      { w: 'FIBRA ÓPTICA', f: ['Internet rápido', 'Cable', 'Luz', 'Velocidad'] },
      { w: 'RATÓN INALÁMBRICO', f: ['Clic', 'Puntero', 'Sin cable', 'Alfombrilla'] },
      { w: 'TECLADO MECÁNICO', f: ['Teclas', 'Escribir', 'Ruido', 'Luces RGB'] },
      { w: 'MONITOR CURVO', f: ['Pantalla', 'Ver', 'Pulgadas', 'Escritorio'] },
      { w: 'ALTAVOZ INTELIGENTE / ALEXA', f: ['Voz', 'Poner música', 'Preguntar', 'Amazon'] },
      { w: 'CABLE HDMI', f: ['Televisión', 'Conectar', 'Imagen y sonido', 'Consola'] },
      { w: 'ENCHUFE INTELIGENTE', f: ['Wi-Fi', 'Apagar móvil', 'Corriente', 'App'] },
      { w: 'DOMÓTICA', f: ['Casa inteligente', 'Automatizar', 'Luces', 'Voz'] },
      { w: 'PROYECTOR LÁSER', f: ['Pared blanca', 'Cine en casa', 'Luz', 'Película'] },
      { w: 'PATINETE ELÉCTRICO', f: ['Batería', 'Acera', 'Manillar', 'Transporte urbano'] }
    ]
  },
  {
    categoryKey: 'transport',
    categoryName: 'Transporte',
    idPrefix: 'tra',
    words: [
      { w: 'COCHE', f: ['Cuatro ruedas', 'Volante', 'Conducir', 'Motor'] },
      { w: 'MOTOCICLETA', f: ['Dos ruedas', 'Casco', 'Tubo de escape', 'Manillar'] },
      { w: 'BICICLETA', f: ['Pedales', 'Cadena', 'Manillar', 'Dos ruedas'] },
      { w: 'PATINETE ELÉCTRICO', f: ['Batería', 'Manillar', 'Calle', 'De pie'] },
      { w: 'AUTOBÚS', f: ['Paradas', 'Pasajeros', 'Billete', 'Grande'] },
      { w: 'TRANVÍA', f: ['Raíles en calle', 'Cables arriba', 'Ciudad', 'Campanilla'] },
      { w: 'METRO', f: ['Bajo tierra', 'Túnel', 'Estación', 'Vagón'] },
      { w: 'TREN DE ALTA VELOCIDAD / AVE', f: ['Rápido', 'Vías', 'Renfe', 'Estación'] },
      { w: 'AVIÓN COMERCIAL', f: ['Alas', 'Volar', 'Piloto', 'Aeropuerto'] },
      { w: 'HELICÓPTERO', f: ['Hélice arriba', 'Aterrizar vertical', 'Ruido', 'Cielo'] },
      { w: 'BARCO VELERO', f: ['Vela blanca', 'Viento', 'Mar', 'Timón'] },
      { w: 'CRUCERO', f: ['Vacaciones', 'Piscina a bordo', 'Barco gigante', 'Camarotes'] },
      { w: 'SUBMARINO', f: ['Bajo el agua', 'Periscopio', 'Profundidad', 'Torpedos'] },
      { w: 'LANCHA MOTORA', f: ['Rápida', 'Motor fueraborda', 'Olas', 'Agua'] },
      { w: 'GLOBO AEROSTÁTICO', f: ['Cesta', 'Aire caliente', 'Fuego', 'Flotar'] },
      { w: 'TELEFÉRICO', f: ['Cable', 'Cabina colgante', 'Montaña', 'Altura'] },
      { w: 'TAXI', f: ['Luz verde', 'Pagar', 'Conductor', 'Coche amarillo o blanco'] },
      { w: 'AMBULANCIA', f: ['Sirena', 'Hospital', 'Urgencias', 'Cruz roja'] },
      { w: 'CAMIÓN DE BOMBEROS', f: ['Escalera', 'Rojo', 'Sirena', 'Manguera'] },
      { w: 'COCHE DE POLICÍA', f: ['Sirena azul', 'Luces', 'Patrulla', 'Detener'] },
      { w: 'CAMIÓN DE BASURA', f: ['Contenedores', 'Noche', 'Triturar', 'Olor'] },
      { w: 'TRACTOR', f: ['Ruedas gigantes', 'Campo', 'Granja', 'Lento'] },
      { w: 'FURGONETA', f: ['Reparto', 'Amazon', 'Paquetes', 'Carga'] },
      { w: 'AUTOCARAVANA', f: ['Cama dentro', 'Viajar', 'Casa con ruedas', 'Camping'] },
      { w: 'MONOPATÍN / SKATE', f: ['Tabla', 'Cuatro ruedas', 'Hacer trucos', 'Pie'] },
      { w: 'TRINEO CON PERROS', f: ['Huskies', 'Nieve', 'Polo', 'Madera'] },
      { w: 'GÓNDOLA', f: ['Venecia', 'Canales', 'Remo largo', 'Romántico'] },
      { w: 'COHETE ESPACIAL', f: ['Despegue', 'Fuego', 'Luna', 'NASA'] }
    ]
  },
  {
    categoryKey: 'home',
    categoryName: 'Casa',
    idPrefix: 'cas',
    words: [
      { w: 'SALÓN', f: ['Sofá', 'Tele', 'Mesa de centro', 'Descansar'] },
      { w: 'COCINA', f: ['Fogones', 'Frigorífico', 'Fregadero', 'Comida'] },
      { w: 'DORMITORIO', f: ['Cama', 'Armario', 'Dormir', 'Mesita'] },
      { w: 'CUARTO DE BAÑO', f: ['Ducha', 'Lavabo', 'Espejo', 'Váter'] },
      { w: 'PASILLO', f: ['Largo', 'Puertas', 'Caminar', 'Cuadros'] },
      { w: 'RECIBIDOR', f: ['Entrada', 'Perchero', 'Puerta principal', 'Llaves'] },
      { w: 'BALCÓN', f: ['Barandilla', 'Calle', 'Asomarse', 'Plantas'] },
      { w: 'TERRAZA', f: ['Mesa y sillas', 'Sol', 'Exterior', 'Ático'] },
      { w: 'JARDÍN', f: ['Césped', 'Flores', 'Regar', 'Árboles'] },
      { w: 'GARAJE', f: ['Aparcar', 'Coche', 'Puerta automática', 'Herramientas'] },
      { w: 'DESVÁN / BUHARDILLA', f: ['Tejado', 'Cajas viejas', 'Arriba', 'Polvo'] },
      { w: 'SÓTANO', f: ['Abajo', 'Oscuro', 'Bodega', 'Escaleras'] },
      { w: 'CHIMENEA', f: ['Fuego', 'Leña', 'Humo', 'Ladrillos'] },
      { w: 'SOFÁ', f: ['Cojines', 'Sentarse', 'Tele', 'Siesta'] },
      { w: 'ESTANTERÍA', f: ['Libros', 'Baldas', 'Pared', 'Colocar'] },
      { w: 'ARMARIO ROPERO', f: ['Perchas', 'Ropa', 'Puertas', 'Cajones'] },
      { w: 'MESITA DE NOCHE', f: ['Lámpara', 'Al lado de la cama', 'Despertador', 'Cajón'] },
      { w: 'CAMA DE MATRIMONIO', f: ['Dos personas', 'Colchón', 'Sábanas', 'Dormir'] },
      { w: 'LITERA', f: ['Dos pisos', 'Escalera', 'Hermanos', 'Arriba y abajo'] },
      { w: 'CUNA', f: ['Bebé', 'Barrotes', 'Dormir', 'Colchoncito'] },
      { w: 'ESCRITORIO', f: ['Estudiar', 'Mesa', 'Ordenador', 'Silla'] },
      { w: 'BAÑERA', f: ['Agua caliente', 'Espuma', 'Sumergirse', 'Grifo'] },
      { w: 'DUCHA', f: ['De pie', 'Mampara', 'Cortina', 'Chorro'] },
      { w: 'LAVABO', f: ['Lavarse las manos', 'Grifo', 'Jabón', 'Desagüe'] },
      { w: 'INODORO / VÁTER', f: ['Tirar de la cadena', 'Tapa', 'Papel higiénico', 'Sentarse'] },
      { w: 'BIDÉ', f: ['Chorro', 'Higiene', 'Baño', 'Al lado del váter'] },
      { w: 'FREGADERO', f: ['Lavar platos', 'Grifo cocina', 'Estropajo', 'Desagüe'] },
      { w: 'LAVAVAJILLAS', f: ['Pastilla de jabón', 'Platos limpios', 'Electrodoméstico', 'Cestas'] },
      { w: 'HORNO', f: ['Asar', 'Calor', 'Bandeja', 'Pasteles'] },
      { w: 'PLACA DE INDUCCIÓN / VITRO', f: ['Sartén', 'Cocinar', 'Cristal negro', 'Calor'] },
      { w: 'CAMPANA EXTRACTORA', f: ['Humo', 'Olores', 'Ruido', 'Encima de la vitro'] },
      { w: 'TENDEDERO', f: ['Pinzas', 'Ropa mojada', 'Secar', 'Sol'] },
      { w: 'CESTO DE LA ROPA SUCIA', f: ['Ropa', 'Lavar', 'Tapa', 'Meter'] },
      { w: 'CORTINAS', f: ['Ventana', 'Luz', 'Telas', 'Correr'] },
      { w: 'PERSIANAS', f: ['Cuerda', 'Bajar', 'Subir', 'Oscuridad'] },
      { w: 'ALFOMBRA', f: ['Suelo', 'Pisar', 'Pelo', 'Aspiradora'] },
      { w: 'PERCHERO', f: ['Colgar abrigos', 'Chaquetas', 'Entrada', 'Pared'] },
      { w: 'ZAPATERO', f: ['Guardar zapatos', 'Zapatillas', 'Puertas', 'Armario'] }
    ]
  },
  {
    categoryKey: 'leisure',
    categoryName: 'Ocio',
    idPrefix: 'oci',
    words: [
      { w: 'PARCHÍS', f: ['Dado', 'Fichas', 'Comerse una', 'Tablero'] },
      { w: 'JUEGO DE LA OCA', f: ['De oca a oca', 'Puente', 'Dado', 'Pozo'] },
      { w: 'AJEDREZ', f: ['Jaque mate', 'Rey', 'Reina', 'Blancas y negras'] },
      { w: 'DAMAS', f: ['Fichas redondas', 'Comer', 'Diagonal', 'Tablero'] },
      { w: 'DOMINÓ', f: ['Fichas con puntos', 'Blanca doble', 'Mesa', 'Emparejar'] },
      { w: 'MONOPOLY', f: ['Comprar calles', 'Casas y hoteles', 'Cárcel', 'Billetes'] },
      { w: 'TRIVIAL PURSUIT', f: ['Quesitos', 'Preguntas', 'Categorías', 'Saber'] },
      { w: 'SCRABBLE', f: ['Letras', 'Palabras cruzadas', 'Puntos', 'Fichas de madera'] },
      { w: 'JUEGO DEL UNO', f: ['Cambio de sentido', 'Chúpate cuatro', 'Carta', 'Decir uno'] },
      { w: 'BARAJA ESPAÑOLA', f: ['Oros', 'Copas', 'Espadas', 'Bastos'] },
      { w: 'BARAJA DE PÓKER', f: ['Picas', 'Corazones', 'Tréboles', 'Diamantes'] },
      { w: 'FUTBOLÍN', f: ['Barras de metal', 'Muñecos', 'Bolas', 'Gol'] },
      { w: 'KARAOKE', f: ['Cantar', 'Micrófono', 'Letra en pantalla', 'Música'] },
      { w: 'ESCAPE ROOM', f: ['Pistas', 'Candados', 'Salir de la habitación', 'Tiempo'] },
      { w: 'PARQUE DE BOLAS', f: ['Piscina de bolas', 'Niños', 'Toboganes', 'Calcetines'] },
      { w: 'CONCIERTO', f: ['Grupo de música', 'Entradas', 'Escenario', 'Público'] },
      { w: 'FESTIVAL DE MÚSICA', f: ['Escenarios', 'Pulsera', 'Camping', 'Verano'] },
      { w: 'FIESTA DE CUMPLEAÑOS', f: ['Tarta', 'Velas', 'Regalos', 'Amigos'] },
      { w: 'PICNIC', f: ['Manta en la hierba', 'Cesta', 'Parque', 'Sandwiches'] },
      { w: 'BARBACOA', f: ['Carne', 'Brasas', 'Carbón', 'Humo'] },
      { w: 'MONTAÑA RUSA', f: ['Vagón', 'Bajada rápida', 'Looping', 'Gritos'] },
      { w: 'TIOVIVO / CARRUSEL', f: ['Caballos de madera', 'Girar', 'Música infantil', 'Feria'] },
      { w: 'NORIA', f: ['Rueda gigante', 'Cabinas', 'Vistas', 'Altura'] },
      { w: 'COCHES DE CHOQUE', f: ['Antena con chispas', 'Chocar', 'Volante', 'Feria'] },
      { w: 'CASETA DE FERIA', f: ['Tiro al blanco', 'Peluche', 'Dardos a globos', 'Puesto'] },
      { w: 'CRUCIGRAMA', f: ['Casillas blancas y negras', 'Definiciones', 'Horizontal', 'Vertical'] },
      { w: 'SOPA DE LETRAS', f: ['Buscar palabras', 'Lápiz', 'Líneas', 'Letras revueltas'] },
      { w: 'SUDOKU', f: ['Números del 1 al 9', 'Cuadrícula', 'No repetir', 'Lógica'] },
      { w: 'PUZZLE / ROMPECABEZAS', f: ['Piezas', 'Encajar', 'Bordes', 'Imagen'] },
      { w: 'LEGO', f: ['Bloques', 'Construir', 'Pisar descalzo', 'Instrucciones'] },
      { w: 'PLASTILINA', f: ['Moldear', 'Colores', 'Olor', 'Blandita'] }
    ]
  },
  {
    categoryKey: 'culture',
    categoryName: 'Cultura',
    idPrefix: 'cul',
    words: [
      { w: 'FERIA DE ABRIL', f: ['Sevilla', 'Casetas', 'Farolillos', 'Rebujito'] },
      { w: 'SAN FERMÍN', f: ['Pamplona', 'Encierro', 'Pañuelo rojo', 'Toros'] },
      { w: 'LAS FALLAS', f: ['Valencia', 'Monumentos de cartón', 'Fuego / Cremà', 'Mascletà'] },
      { w: 'LA TOMATINA', f: ['Buñol', 'Tomates', 'Guerra roja', 'Agosto'] },
      { w: 'CAMPANADAS DE FIN DE AÑO', f: ['Puerta del Sol', 'Doce uvas', 'Reloj', 'Nochevieja'] },
      { w: 'CABALGATA DE REYES', f: ['Carrozas', 'Caramelos', 'Cinco de enero', 'Niños'] },
      { w: 'SEMANA SANTA', f: ['Procesiones', 'Pasos', 'Nazarenos', 'Tambores'] },
      { w: 'CARNAVAL', f: ['Disfraces', 'Cádiz', 'Chirigotas', 'Máscaras'] },
      { w: 'SAN JORDI', f: ['Rosa', 'Libro', 'Dragón', 'Cataluña'] },
      { w: 'FLAMENCO', f: ['Guitarra', 'Cante', 'Taconeo', 'Palmas'] },
      { w: 'SEVILLANAS', f: ['Baile', 'Cuatro coplas', 'Volantes', 'Feria'] },
      { w: 'JOTA ARAGONESA', f: ['Castañuelas', 'Saltos', 'Aragón', 'Traje regional'] },
      { w: 'CASTELLS', f: ['Torres humanas', 'Enxaneta', 'Cataluña', 'Subir'] },
      { w: 'SIESTA', f: ['Dormir después de comer', 'Sofá', 'Pijama y orinal', 'Descanso'] },
      { w: 'TAPEO / IR DE TAPAS', f: ['Bares', 'Cañas', 'Picar', 'Amigos'] },
      { w: 'SOBREMESA', f: ['Quedarse hablando', 'Después de comer', 'Café', 'Mesa'] },
      { w: 'LOTERÍA DE NAVIDAD', f: ['El Gordo', 'Niños de San Ildefonso', 'Bombos', '22 de diciembre'] },
      { w: 'BELÉN / NACIMIENTO', f: ['Figuras', 'Niño Jesús', 'Portal', 'Pastor'] },
      { w: 'ÁRBOL DE NAVIDAD', f: ['Bolas', 'Estrella en la punta', 'Luces', 'Abeto'] },
      { w: 'BOTELLÓN', f: ['Parque', 'Jóvenes', 'Bolsas de plástico', 'Beber'] },
      { w: 'MONA DE PASCUA', f: ['Huevo de chocolate', 'Padrino', 'Lunes de Pascua', 'Plumas'] },
      { w: 'DÍA DE LOS SANTOS', f: ['Cementerio', 'Flores', 'Buñuelos', 'Huesos de santo'] },
      { w: 'FIESTA DE PUEBLO', f: ['Orquesta', 'Plaza', 'Pregón', 'Peñas'] }
    ]
  },
  {
    categoryKey: 'music',
    categoryName: 'Música',
    idPrefix: 'mus',
    words: [
      { w: 'GUITARRA ESPAÑOLA', f: ['Cuerdas', 'Caja de madera', 'Tocar', 'Clavijero'] },
      { w: 'GUITARRA ELÉCTRICA', f: ['Amplificador', 'Púa', 'Rock', 'Distorsión'] },
      { w: 'BATERÍA', f: ['Platillos', 'Baquetas', 'Bombo', 'Caja'] },
      { w: 'PIANO', f: ['Teclas blancas y negras', 'Pedales', 'Cola', 'Partitura'] },
      { w: 'VIOLÍN', f: ['Arco', 'Cuerdas', 'Barbilla', 'Agudo'] },
      { w: 'VIOLONCHELO', f: ['Grande', 'Sentado', 'Entre las piernas', 'Arco'] },
      { w: 'FLAUTA DULCE', f: ['Colegio', 'Plástico', 'Agujeros', 'Soplar'] },
      { w: 'SAXOFÓN', f: ['Dorado', 'Jazz', 'Boquilla', 'Viento'] },
      { w: 'TROMPETA', f: ['Tres pistones', 'Metal', 'Boquilla', 'Sonido fuerte'] },
      { w: 'TROMBÓN', f: ['Vara que se estira', 'Metal', 'Grave', 'Deslizar'] },
      { w: 'ARMÓNICA', f: ['Boca', 'Pequeña', 'Soplar y aspirar', 'Blues'] },
      { w: 'ACORDEÓN', f: ['Fuelle', 'Teclas o botones', 'Abrir y cerrar', 'Música tradicional'] },
      { w: 'ARPA', f: ['Muchas cuerdas', 'Dedos', 'Ángel', 'Grande'] },
      { w: 'UKELELE', f: ['Pequeño', 'Cuatro cuerdas', 'Hawái', 'Guitarra pequeña'] },
      { w: 'CASTAÑUELAS', f: ['Manos', 'Madera', 'Flamenco', 'Chasquido'] },
      { w: 'PANDERETA', f: ['Platillos pequeños', 'Mano', 'Villancicos', 'Navidad'] },
      { w: 'XILÓFONO', f: ['Láminas de madera o metal', 'Mazas', 'Golpear', 'Notas'] },
      { w: 'TRIÁNGULO', f: ['Metal', 'Varilla', 'Tin tin', 'Orquesta'] },
      { w: 'MARACAS', f: ['Agitar', 'Semillas dentro', 'Mango', 'Ritmo latino'] },
      { w: 'MICRÓFONO', f: ['Cantar', 'Voz', 'Soporte', 'Altavoz'] },
      { w: 'PARTITURA', f: ['Pentagrama', 'Notas musicales', 'Papel', 'Atril'] },
      { w: 'BATUTA', f: ['Director de orquesta', 'Varita', 'Marcar compás', 'Mano'] },
      { w: 'ORQUESTA SINFÓNICA', f: ['Músicos', 'Director', 'Instrumentos', 'Teatro'] },
      { w: 'CORO', f: ['Gente cantando', 'Voces', 'Iglesia', 'Director'] },
      { w: 'ROCK AND ROLL', f: ['Guitarra', 'Batería', 'Elvis', 'Rebelde'] },
      { w: 'REGUETÓN', f: ['Perreo', 'Autotune', 'Ritmo', 'Latino'] },
      { w: 'RAP / HIP-HOP', f: ['Rimas', 'Hablar rápido', 'Base rítmica', 'Micrófono'] },
      { w: 'MÚSICA CLÁSICA', f: ['Mozart', 'Beethoven', 'Orquesta', 'Violines'] },
      { w: 'HEAVY METAL', f: ['Guitarras distorsionadas', 'Melena', 'Gritos', 'Negro'] }
    ]
  },
  {
    categoryKey: 'body',
    categoryName: 'Cuerpo Humano',
    idPrefix: 'cue',
    words: [
      { w: 'CABEZA', f: ['Pelo', 'Cerebro', 'Cara', 'Cuello'] },
      { w: 'CEJAS', f: ['Ojos', 'Pelos', 'Frente', 'Depilar'] },
      { w: 'PESTAÑAS', f: ['Ojos', 'Pestañear', 'Rímel', 'Pelitos'] },
      { w: 'NARIZ', f: ['Oler', 'Mocos', 'Respirar', 'Sonarse'] },
      { w: 'OREJAS', f: ['Oír', 'Pendientes', 'Escuchar', 'Lóbulo'] },
      { w: 'LABIOS', f: ['Boca', 'Besar', 'Pintalabios', 'Sonreír'] },
      { w: 'DIENTES', f: ['Masticar', 'Blancos', 'Caries', 'Cepillar'] },
      { w: 'LENGUA', f: ['Sabores', 'Sacar', 'Hablar', 'Boca'] },
      { w: 'BARBILLA / MENTÓN', f: ['Bajo la boca', 'Perilla', 'Cara', 'Mandíbula'] },
      { w: 'CUELLO', f: ['Garganta', 'Cabeza', 'Bufanda', 'Collar'] },
      { w: 'HOMBROS', f: ['Mochila', 'Brazos', 'Encogerse', 'Espalda'] },
      { w: 'CODOS', f: ['Doblar el brazo', 'Articulación', 'Hueso', 'Golpe'] },
      { w: 'MUÑECA', f: ['Reloj', 'Mano', 'Articulación', 'Girar'] },
      { w: 'PULGAR', f: ['Dedo gordo', 'Hacer autostop', 'Aprobar', 'Mano'] },
      { w: 'UÑAS', f: ['Cortar', 'Esmalte', 'Dedos', 'Morderse'] },
      { w: 'PECHO', f: ['Corazón', 'Pulmones', 'Respirar', 'Camiseta'] },
      { w: 'COLUMNA VERTEBRAL', f: ['Espalda', 'Vértebras', 'Huesos', 'Postura'] },
      { w: 'COSTILLAS', f: ['Huesos pecho', 'Proteger pulmones', 'Flotantes', 'Dolor'] },
      { w: 'BARRIGA / ABDOMEN', f: ['Ombligo', 'Gordura', 'Estómago', 'Tripa'] },
      { w: 'OMBLIGO', f: ['Cordón umbilical', 'Barriga', 'Agujero', 'Centro'] },
      { w: 'RODILLAS', f: ['Doblar la pierna', 'Rótula', 'Caerse', 'Articulación'] },
      { w: 'TOBILLO', f: ['Torcedura', 'Pie', 'Esguince', 'Hueso del pie'] },
      { w: 'PIES', f: ['Zapatos', 'Caminar', 'Calcetines', 'Dedos'] },
      { w: 'TALÓN', f: ['Aquiles', 'Parte trasera del pie', 'Zapato', 'Pisar'] },
      { w: 'CORAZÓN', f: ['Latir', 'Sangre', 'Amor', 'Pecho'] },
      { w: 'PULMONES', f: ['Respirar', 'Aire', 'Oxígeno', 'Fumar'] },
      { w: 'ESTÓMAGO', f: ['Hambre', 'Digestión', 'Comida', 'Gases'] },
      { w: 'CEREBRO', f: ['Pensar', 'Cabeza', 'Neuronas', 'Inteligencia'] },
      { w: 'ESQUELETO', f: ['Huesos', 'Calavera', 'Blanco', 'Halloween'] },
      { w: 'MÚSCULOS', f: ['Fuerza', 'Gimnasio', 'Bíceps', 'Agujetas'] }
    ]
  },
  {
    categoryKey: 'clothing',
    categoryName: 'Ropa y Accesorios',
    idPrefix: 'rop',
    words: [
      { w: 'CAMISETA', f: ['Manga corta', 'Cuello redondo', 'Verano', 'Algodón'] },
      { w: 'CAMISA', f: ['Botones', 'Cuello', 'Manga larga', 'Corbata'] },
      { w: 'PANTALÓN VAQUERO / JEANS', f: ['Azul', 'Bolsillos', 'Tela vaquera', 'Cremallera'] },
      { w: 'PANTALONES CORTOS / BERMUDAS', f: ['Verano', 'Calor', 'Piernas al aire', 'Rodillas'] },
      { w: 'FALDA', f: ['Vuelo', 'Piernas', 'Cintura', 'Plisada'] },
      { w: 'VESTIDO', f: ['Una sola pieza', 'Fiesta', 'Boda', 'Mujer'] },
      { w: 'SUDADERA CON CAPUCHA', f: ['Bolsillo canguro', 'Capucha', 'Algodón', 'Chándal'] },
      { w: 'JERSEY / SUÉTER', f: ['Lana', 'Invierno', 'Frío', 'Manga larga'] },
      { w: 'ABRIGO', f: ['Invierno', 'Frío', 'Largo', 'Botones'] },
      { w: 'TRAJE DE CHAQUETA', f: ['Elegante', 'Boda', 'Pantalón y chaqueta', 'Corbata'] },
      { w: 'CORBATA', f: ['Cuello', 'Nudo', 'Camisa', 'Elegante'] },
      { w: 'PAJARITA', f: ['Lazo', 'Cuello', 'Esmoquin', 'Camarero'] },
      { w: 'CINTURÓN', f: ['Hebilla', 'Sujetar pantalones', 'Cuero', 'Agujeros'] },
      { w: 'CALCETINES', f: ['Pies', 'Zapatos', 'Talón', 'Lavadora desparejados'] },
      { w: 'ZAPATILLAS DE DEPORTE', f: ['Cordones', 'Correr', 'Suela de goma', 'Cómodas'] },
      { w: 'ZAPATOS DE TACÓN', f: ['Altos', 'Fiesta', 'Pies', 'Andar difícil'] },
      { w: 'BOTAS DE AGUA', f: ['Lluvia', 'Charcos', 'Goma', 'Pisar agua'] },
      { w: 'CHANCLAS', f: ['Playa', 'Piscina', 'Dedo gordo', 'Verano'] },
      { w: 'PANTUFLAS / ZAPATILLAS DE CASA', f: ['Casa', 'Cómodas', 'Levantarse', 'Calientes'] },
      { w: 'BAÑADOR / BIKINI', f: ['Playa', 'Piscina', 'Nadar', 'Mojarse'] },
      { w: 'PIJAMA', f: ['Dormir', 'Cama', 'Noche', 'Ponerse antes de dormir'] },
      { w: 'ALBORNOZ', f: ['Salir de la ducha', 'Secarse', 'Toalla con mangas', 'Cinturón de tela'] },
      { w: 'BUFANDA', f: ['Cuello', 'Lana', 'Invierno', 'Frío'] },
      { w: 'GUANTES', f: ['Manos', 'Dedos', 'Invierno', 'Frío'] },
      { w: 'GORRO DE LANA', f: ['Cabeza', 'Frío', 'Orejas', 'Pompon'] },
      { w: 'GORRA DE BÉISBOL', f: ['Visera', 'Sol', 'Atrás', 'Cabeza'] },
      { w: 'SOMBRERO', f: ['Ala ancha', 'Cabeza', 'Sol', 'Elegante'] },
      { w: 'COLLAR', f: ['Cuello', 'Colgante', 'Cadena', 'Joya'] },
      { w: 'PULSERA', f: ['Muñeca', 'Brazo', 'Abalorios', 'Joya'] },
      { w: 'PENDIENTES', f: ['Orejas', 'Agujero', 'Lóbulo', 'Aros'] },
      { w: 'ANILLO', f: ['Dedo', 'Boda', 'Compromiso', 'Oro o plata'] },
      { w: 'BOLSO DE MANO', f: ['Asas', 'Llevar cosas', 'Monedero', 'Hombro'] }
    ]
  },
  {
    categoryKey: 'everyday',
    categoryName: 'Conceptos Cotidianos',
    idPrefix: 'cot',
    words: [
      { w: 'ATASCO DE TRÁFICO', f: ['Coches parados', 'Pitar', 'Carretera', 'Tarde'] },
      { w: 'PERDER EL AUTOBÚS', f: ['Correr detrás', 'Parada', 'Cerrar puertas', 'Esperar otro'] },
      { w: 'QUEDARSE SIN BATERÍA', f: ['Cero por ciento', 'Móvil apagado', 'Cargador', 'Drama'] },
      { w: 'OLVIDAR LAS LLAVES', f: ['Fuera de casa', 'Cerrajería', 'Puerta cerrada', 'Bolsillo'] },
      { w: 'COLA DEL SUPERMERCADO', f: ['Esperar turno', 'Cajero', 'Fila', 'Carro'] },
      { w: 'REBAJAS', f: ['Descuento', 'Ropa barata', 'Enero o julio', 'Comprar'] },
      { w: 'EXAMEN SORPRESA', f: ['Profesor', 'Sin estudiar', 'Hoja en blanco', 'Nervios'] },
      { w: 'VACACIONES DE VERANO', f: ['Playa', 'No trabajar', 'Agosto', 'Descanso'] },
      { w: 'RESACA', f: ['Dolor de cabeza', 'Beber alcohol', 'Día siguiente', 'Sed'] },
      { w: 'AMOR A PRIMERA VISTA', f: ['Flechazo', 'Mirarse', 'Corazón', 'Enamorarse'] },
      { w: 'ATAQUE DE HIPO', f: ['Susto', 'Agua al revés', 'Diafragma', 'Ruido'] },
      { w: 'PESADILLA', f: ['Mal sueño', 'Miedo', 'Despertar sudando', 'Noche'] },
      { w: 'INSOMNIO', f: ['No poder dormir', 'Vueltas en la cama', 'Contar ovejas', 'Despierto'] },
      { w: 'FIESTA SORPRESA', f: ['¡Sorpresa!', 'Cumpleaños', 'Apagar luces', 'Esconderse'] },
      { w: 'REGALO DE CUMPLEAÑOS', f: ['Papel de regalo', 'Abrir', 'Sorpresa', 'Felicidades'] },
      { w: 'BROMA TELEFÓNICA', f: ['Llamar', 'Voz rara', 'Risas', 'Número oculto'] },
      { w: 'DÍA DE LLUVIA', f: ['Paraguas', 'Charcos', 'Quedarse en casa', 'Manta y peli'] },
      { w: 'OLA DE CALOR', f: ['Cuarenta grados', 'Aire acondicionado', 'Verano', 'Sudar'] },
      { w: 'CAÍDA DEL WI-FI', f: ['Sin internet', 'Reiniciar router', 'Luces rojas', 'Desconexión'] },
      { w: 'ERROR 404', f: ['Página no encontrada', 'Web', 'Internet', 'Pantalla'] },
      { w: 'SPOILER DE UNA SERIE', f: ['Contar el final', 'Arruinar', 'Secreto', 'Destripar'] },
      { w: 'FOTO DE CARNET', f: ['Serio', 'DNI', 'Fondo blanco', 'Fotomatón'] },
      { w: 'LLAMADA PERDIDA', f: ['Teléfono sonó', 'No contestar', 'Devolver llamada', 'Notificación'] },
      { w: 'SELFIE', f: ['Cámara delantera', 'Palo selfie', 'Foto a uno mismo', 'Sonreír'] },
      { w: 'DÉJÀ VU', f: ['Ya he vivido esto', 'Sensación extraña', 'Recuerdo', 'Repetirse'] },
      { w: 'HACER LA COLA', f: ['Fila', 'Esperar', 'Turno', 'Paciencia'] },
      { w: 'QUEDARSE DORMIDO', f: ['No sonó la alarma', 'Llegar tarde', 'Prisas', 'Cama'] }
    ]
  }
];
