// Expansion 2 to bring Palabra Secreta total above 2,100+ concepts
export const categoryExpansions2 = {
  animals: [
    { w: 'CABRA MONTÉS', f: ['Cuernos curvados', 'Rocas de montaña', 'Gredos', 'Saltar riscos'] },
    { w: 'MUFLÓN', f: ['Carnero salvaje', 'Cuernos en espiral', 'Sierra', 'Macho'] },
    { w: 'REBECO / SARRIO', f: ['Pirineos', 'Ágil en la nieve', 'Cuernos pequeños', 'Montaña'] },
    { w: 'GAMO', f: ['Cuernos anchos de pala', 'Manchas blancas en el lomo', 'Bosque', 'Ciervo'] },
    { w: 'CORZO MACHO', f: ['Ladrido ronco en el bosque', 'Pequeño y ágil', 'Cuernitos', 'Caza'] },
    { w: 'VISÓN EUROPEO', f: ['Mancha blanca en el morro', 'Ríos limpios', 'Piel valiosa', 'Mustélido'] },
    { w: 'VISÓN AMERICANO', f: ['Invasor', 'Granjas de piel', 'Ríos', 'Depredador'] },
    { w: 'ARMIÑO', f: ['Pelaje blanco en invierno', 'Punta de la cola negra', 'Nieve', 'Rey'] },
    { w: 'COMADREJA', f: ['El carnívoro más pequeño', 'Cuerpo alargado y fino', 'Morder el cuello', 'Madriguera'] },
    { w: 'GARDUÑA', f: ['Mancha blanca en el pecho', 'Subir a los desvanes', 'Nocturna', 'Bosque'] },
    { w: 'GINETA', f: ['Cola anillada larga', 'Manchas de leopardo', 'Nocturna en encinas', 'Gato salvaje'] },
    { w: 'MELONCILLO', f: ['Mangosta ibérica', 'Come serpientes venenosas', 'Camina en fila india', 'Cola peluda'] },
    { w: 'DESMÁN DE LOS PIRINEOS', f: ['Trompa móvil sensible', 'Ríos de agua helada', 'Topo de agua', 'Raro'] },
    { w: 'TOPO COMÚN', f: ['Montículos de tierra en el césped', 'Ciego bajo tierra', 'Garras como palas', 'Túneles'] },
    { w: 'MUSARAÑA', f: ['Corazón que late a mil', 'Hocico puntiagudo', 'Venenosa al morder', 'Roedor enano'] },
    { w: 'LIRÓN CARETO', f: ['Antifaz negro en los ojos', 'Dormir todo el invierno', 'Cola con pincel blanco', 'Frutos secos'] },
    { w: 'TOPILLO DE CAMPO', f: ['Plaga en los cultivos de Castilla', 'Roedor diminuto', 'Cereales', 'Galerías'] },
    { w: 'RATA DE ALCANTARILLA', f: ['Cola larga sin pelo', 'Subterráneo oscuro', 'Basura', 'Miedo'] },
    { w: 'RATÓN DE CAMPO', f: ['Ojos negros saltones', 'Comer bellotas y trigo', 'Lechuza lo caza', 'Madriguera'] },
    { w: 'PERRO PASTOR ALEMÁN', f: ['Policía', 'Orejas tiesas', 'Leal y guardián', 'Manto negro y fuego'] },
    { w: 'PERRO LABRADOR', f: ['Guía de ciegos', 'Le gusta nadar en el agua', 'Dorado o negro', 'Noble con niños'] },
    { w: 'PERRO GOLDEN RETRIEVER', f: ['Pelo largo dorado y suave', 'Cobrador de caza', 'Familia cariñosa', 'Pelota'] },
    { w: 'PERRO CHIHUAHUA', f: ['El más pequeño del mundo', 'Tiembla de nervios', 'Ladridos agudos', 'Bolsillo'] },
    { w: 'PERRO BULLDOG', f: ['Arrugas en la cara chata', 'Camina paticorto', 'Ronca al dormir', 'Inglés o francés'] },
    { w: 'PERRO CANICHE', f: ['Pelo rizado de peluquería', 'Pompones cortados', 'Circo y trucos', 'Blanco o negro'] },
    { w: 'PERRO DÁLMATA', f: ['Ciento uno en Disney', 'Manchas negras sobre blanco', 'Bomberos', 'Correr'] },
    { w: 'PERRO HUSKY SIBERIANO', f: ['Ojos azules penetrantes', 'Tirar de trineos en nieve', 'Aúlla como un lobo', 'Pelo espeso'] },
    { w: 'PERRO GALGO ESPAÑOL', f: ['Cuerpo delgadísimo y aerodinámico', 'Carreras de liebres', 'Correr a 60 por hora', 'Sofá'] },
    { w: 'PERRO PODENCO', f: ['Orejas gigantes triangulares', 'Caza de conejos en matorral', 'Rústico y resistente', 'España'] },
    { w: 'GATO PERSA', f: ['Cara chata enfurruñada', 'Pelo larguísimo para cepillar', 'Tranquilo y aristócrata', 'Cojín'] },
    { w: 'GATO SIAMÉS', f: ['Ojos azules claros', 'Orejas y cola oscuras', 'Maullido ruidoso', 'Tailandia'] },
    { w: 'GATO ESFINGE / SPHYNX', f: ['Sin nada de pelo', 'Piel con arrugas caliente', 'Parece de Egipto', 'Abrigar'] },
    { w: 'GATO CALLEJERO / COMÚN', f: ['Rayas atigradas pardas', 'Saltar muros de noche', 'Cazar ratones', 'Siete vidas'] }
  ],
  food: [
    { w: 'GAZPACHUELO MALAGUEÑO', f: ['Sopa caliente con mayonesa', 'Pescado blanco y patata', 'Málaga', 'Limón'] },
    { w: 'PAPAS CON CHOCO', f: ['Guiso de sepia con patatas', 'Huelva y Cádiz', 'Cuchara marinera', 'Laurel'] },
    { w: 'ATÚN EN MANTECA', f: ['Taco de atún rojo cocido', 'Grasa blanca de cerdo', 'Barbate y Cádiz', 'Tapa fría'] },
    { w: 'MOJAMA DE ATÚN', f: ['Jamón del mar', 'Salazón seca en lonchas finas', 'Almendras fritas', 'Aceite de oliva'] },
    { w: 'HUEVAS DE MARUCA', f: ['Salazón que se pega al paladar', 'Bebida con cerveza fría', 'Aperitivo salado', 'Pescado'] },
    { w: 'TORTILLITAS DE CAMARONES', f: ['Masa crujiente de encaje', 'Camarones diminutos enteros', 'Cádiz', 'Fritura de feria'] },
    { w: 'BIENMESABE / CAZÓN EN ADOBO', f: ['Tiburón cazón marinado', 'Orégano pimentón y vinagre', 'Frito crujiente por fuera', 'Andalucía'] },
    { w: 'ESPETO DE SARDINAS', f: ['Barca con arena en la playa', 'Cañas de madera clavadas', 'Fuego de leña de olivo', 'Málaga'] },
    { w: 'CALLOS A LA MADRILEÑA', f: ['Tripas de ternera melosas', 'Chorizo y morcilla picante', 'Salsa con pimentón', 'Mojar pan'] },
    { w: 'OREJA A LA PLANCHA', f: ['Cartílago crujiente de cerdo', 'Salsa brava o ajillo', 'Tapa castiza de bar', 'Madrid'] },
    { w: 'GALLINEJAS Y ENTRESFormatted', f: ['Tripas fritas de cordero', 'Fiestas de San Isidro', 'Olor fuerte en la feria', 'Madrid antiguo'] },
    { w: 'CARACOLES EN SALSA', f: ['Salsa picante con jamón', 'Palillo para sacarlos', 'Primavera en terrazas', 'Chuparse los dedos'] },
    { w: 'GAMBAS ROJAS DE DENIA', f: ['Cabeza llena de sabor', 'Agua de mar hervida', 'Marisco carísimo', 'Alicante'] },
    { w: 'LANGOSTINOS DE SANLÚCAR', f: ['Rayas atigradas en la cola', 'Desembocadura del Guadalquivir', 'Cocidos al punto de sal', 'Fiesta'] },
    { w: 'BOGAVANTE', f: ['Pinzas gigantes desiguales', 'Arroz caldoso marinero', 'Color azul que se vuelve rojo al cocer', 'Marisco'] },
    { w: 'BUEY DE MAR RELLENO', f: ['Caparazón con la carne picada', 'Huevo duro y chorrito de vino', 'Comer con cucharita', 'Marisco'] },
    { w: 'TXIPIRONES EN SU TINTA', f: ['Calamares pequeños rellenos', 'Salsa negra espesa', 'País Vasco', 'Arroz blanco de guarnición'] },
    { w: 'MERLUZA EN SALSA VERDE', f: ['Perejil picado en el caldo', 'Almejas y espárragos blancos', 'Cazuela de barro', 'País Vasco'] },
    { w: 'KOKOTXAS DE BACALAO', f: ['Papada gelatinosa del pescado', 'Salsa pil-pil ligada con vaivén', 'Manjar vasco', 'Cazuela'] },
    { w: 'CHULETÓN DE TOLOSA', f: ['Vaca vieja con grasa amarilla', 'Poco hecho al carbón', 'Sal gorda por encima', 'País Vasco'] },
    { w: 'PERRUNILLAS', f: ['Dulce de convento con manteca', 'Almendra entera en el centro', 'Extremadura', 'Polvorienta'] },
    { w: 'PIONONOS DE SANTA FE', f: ['Bizcocho enrollado borracho', 'Crema tostada por encima', 'Granada', 'Bocado dulce'] },
    { w: 'YEMAS DE SANTA TERESA', f: ['Bolitas naranjas de huevo y almíbar', 'Caja de papelitos blancos', 'Ávila', 'Dulce tradicional'] },
    { w: 'CARBAYONES', f: ['Hojaldre relleno de almendra', 'Glaseado amarillo de yema y azúcar', 'Oviedo y Asturias', 'Pastel'] },
    { w: 'TARTA DE SANTIAGO', f: ['Cruz de la orden con azúcar glas', 'Harina de almendra sin gluten', 'Camino de Santiago', 'Galicia'] },
    { w: 'CREMA DE ORUJO', f: ['Chupito después de cenar', 'Licor gallego con nata', 'Dulce con hielo', 'Digestivo'] },
    { w: 'PACHARÁN NAVARRO', f: ['Endrinas maceradas en anís', 'Color rojo rubí', 'Navarra', 'Chupito frío sin hielo'] },
    { w: 'AGUA DE VALENCIA', f: ['Zumo de naranja natural', 'Cava ginebra y vodka', 'Jarra con hielo', 'Fiesta valenciana'] },
    { w: 'REBUJITO DE FERIA', f: ['Vino manzanilla o fino', 'Refresco de lima-limón Seven Up', 'Hierbabuena fresca y hielo', 'Feria de Abril'] },
    { w: 'VERMUT DE GRIFO', f: ['Vino macerado con hierbas aromáticas', 'Rodaja de naranja y aceituna', 'Sifón para rebajar', 'Aperitivo del domingo'] }
  ],
  objects: [
    { w: 'BOMBILLA VENDIMIA / EDISON', f: ['Filamento naranja a la vista', 'Cristal ámbar decorativo', 'Bares modernos hipster', 'Luz cálida'] },
    { w: 'INTERRUPTOR DE PARED', f: ['Pulsar con el dedo para encender luz', 'Marco blanco de plástico', 'Click al apretar', 'Junto a la puerta'] },
    { w: 'ENCHUFE DE TRES PATAS', f: ['Toma de tierra de seguridad', 'Clavijas metálicas', 'Meter el cargador', 'Pared'] },
    { w: 'LADRÓN DE TRES CLAVIJAS', f: ['Pieza para multiplicar un enchufe', 'Triángulo blanco de plástico', 'Enchufar tres aparatos', 'Corriente'] },
    { w: 'CABLE ALARGADOR CON CARRETE', f: ['Rueda para enrollar 25 metros', 'Cable naranja o negro grueso', 'Obras y jardín', 'Enchufes'] },
    { w: 'TESTER / MULTÍMETRO', f: ['Puntas roja y negra para medir voltios', 'Rueda selectora de corriente', 'Electricista profesional', 'Pantalla digital'] },
    { w: 'SOLDADOR DE ESTAÑO', f: ['Punta caliente que echa humo', 'Hilo plateado que se funde', 'Arreglar circuitos electrónicos', 'Soporte'] },
    { w: 'PISTOLA DE SILICONA CALIENTE', f: ['Barras transparentes que se derriten', 'Gatillo para pegar manualidades', 'Quema si te toca el dedo', 'Pegamento'] },
    { w: 'CUTTER / BISTURÍ DE CARTÓN', f: ['Cuchilla retráctil afiladísima', 'Partir la hoja por la ranura', 'Abrir paquetes de Amazon', 'Bloqueo'] },
    { w: 'NIVEL DE BURBUJA', f: ['Tubito verde con líquido y aire', 'Comprobar que el cuadro está recto', 'Regla de aluminio', 'Burbuja centrada'] },
    { w: 'CALIBRE / PIE DE REY', f: ['Medir milímetros con precisión', 'Mandíbulas de metal que abrazan piezas', 'Mecánico de torno', 'Nonio'] },
    { w: 'LLAVE ALLEN', f: ['Forma de L con punta hexagonal', 'Montar muebles de IKEA', 'Tornillos negros huecos', 'Juego de llaves'] },
    { w: 'LLAVE TORX', f: ['Punta con forma de estrella de seis puntas', 'Tornillos de coches y móviles', 'Herramienta de precisión', 'Girar'] },
    { w: 'TENAZAS RUSAS', f: ['Sacar clavos viejos de la madera', 'Cortar alambres con palanca', 'Boca redonda afilada', 'Construcción'] },
    { w: 'SARGENTO / MORDAZA', f: ['Apretar dos maderas encoladas', 'Tornillo con manivela giratoria', 'Sujetar a la mesa del taller', 'Carpintería'] },
    { w: 'BANCO DE TRABAJO DE CARPINTERO', f: ['Mesa de madera maciza de haya', 'Tornillo de banco para sujetar piezas', 'Bandeja para herramientas', 'Taller'] },
    { w: 'CAJA DE HERRAMIENTAS METÁLICA', f: ['Se abre en acordeón de tres pisos', 'Asa superior pesada', 'Llaves martillo y alicates', 'Garaje'] },
    { w: 'BIDÓN DE GASOLINA HOMOLOGADO', f: ['Plástico rojo con tapón y cánula', 'Llenar cinco litros en la gasolinera', 'Cortacésped o emergencia', 'Combustible'] },
    { w: 'EMBERBUDO DE PLÁSTICO', f: ['Cono ancho con tubo estrecho', 'Echar aceite al coche sin manchar', 'Rellenar botellas', 'Líquido'] },
    { w: 'GATO HIDRÁULICO DE COCHE', f: ['Palanca para levantar dos toneladas', 'Cambiar la rueda pinchada', 'Bajo el chasis', 'Ruedas del coche'] },
    { w: 'TRIÁNGULOS DE EMERGENCIA', f: ['Poner a cincuenta metros en avería', 'Reflectante naranja brillante', 'Plegables en estuche', 'Carretera'] },
    { w: 'CHALECO REFLECTANTE AMARILLO', f: ['Bandas grises que brillan con los faros', 'Obligatorio en la guantera', 'Salir del coche en la autovía', 'Seguridad'] },
    { w: 'RASQUETA DE HIELO PARA CRISTALES', f: ['Quitar la escarcha mañanera del parabrisas', 'Borde de plástico rígido', 'Invierno frío', 'Coche congelado'] },
    { w: 'PARASOL DE COCHE PLEGABLE', f: ['Aluminio brillante plateado', 'Poner en el parabrisas contra el sol', 'El volante no quema al subir', 'Verano'] }
  ],
  places: [
    { w: 'MONASTERIO DE EL ESCORIAL', f: ['Felipe II', 'Piedra de granito gris', 'Patio de los reyes', 'Madrid sierra'] },
    { w: 'ALHAMBRA DE GRANADA', f: ['Palacios nazaríes', 'Patio de los leones', 'Generalife', 'Fuente mágica'] },
    { w: 'MEZQUITA DE CÓRDOBA', f: ['Arcos de herradura bicolores', 'Bosque de columnas de mármol', 'Catedral en medio', 'Patio de los naranjos'] },
    { w: 'SAGRADA FAMILIA DE BARCELONA', f: ['Gaudí', 'Torres apuntando al cielo', 'Vidrieras de colores', 'Templo inacabado'] },
    { w: 'PARQUE GÜELL', f: ['Salamandra de trencadís', 'Bancos ondulados de mosaico', 'Vistas a Barcelona', 'Gaudí'] },
    { w: 'CATEDRAL DE SANTIAGO DE COMPOSTELA', f: ['Plaza del Obradoiro', 'Abrazar al Santo', 'Botafumeiro volando', 'Fin del camino'] },
    { w: 'ACUEDUCTO DE SEGOVIA', f: ['Arcos romanos de granito sin cemento', 'Plaza del Azoguejo', 'Cochinillo al lado', 'Monumento'] },
    { w: 'MURALLAS DE ÁVILA', f: ['Ochenta y ocho torreones redondos', 'Pasear por arriba', 'Ciudad medieval cerrada', 'Piedra iluminada de noche'] },
    { w: 'MUSEO DEL PRADO', f: ['Las Meninas de Velázquez', 'Goya y el dos de mayo', 'El Bosco y las delicias', 'Madrid arte'] },
    { w: 'MUSEO REINA SOFÍA', f: ['Guernica de Picasso', 'Arte moderno', 'Ascensores de cristal exterior', 'Atocha'] },
    { w: 'MUSEO GUGGENHEIM DE BILBAO', f: ['Titanio que refleja la ría', 'Escultura del perro Puppy de flores', 'Frank Gehry', 'Araña Maman'] },
    { w: 'TEATRO ROMANO DE MÉRIDA', f: ['Columnas clásicas corintias', 'Festival de teatro de verano', 'Augusta Emerita', 'Gradas de piedra'] },
    { w: 'CIUDAD DE LAS ARTES Y LAS CIENCIAS', f: ['Edificios blancos futuristas de Calatrava', 'Oceanogràfic con túnel de tiburones', 'Hemisfèric con ojo gigante', 'Valencia'] },
    { w: 'PUERTA DE ALCALÁ', f: ['Mírala mírala', 'Monumento de Carlos III', 'Junto al Parque del Retiro', 'Cinco arcos de granito'] },
    { w: 'ESTANQUE DEL RETIRO', f: ['Barquitas de remos de alquiler', 'Monumento a Alfonso XII', 'Carpa gigante comiendo pan', 'Madrid domingo'] },
    { w: 'PARQUE DE DOÑANA', f: ['Marismas con flamencos', 'Lince ibérico protegido', 'Dunas móviles de arena', 'Huelva y Cádiz'] },
    { w: 'PICOS DE EUROPA', f: ['Naranjo de Bulnes / Urriellu', 'Lagos de Covadonga con vacas', 'Garganta del Cares', 'Asturias y Cantabria'] },
    { w: 'VOLCÁN DEL TEIDE', f: ['Pico más alto de España', 'Tenerife en las Canarias', 'Paisaje lunar de lava negra', 'Teleférico'] },
    { w: 'TIMANFAYA EN LANZAROTE', f: ['Montañas del fuego', 'Cocinar pollo con calor de la tierra', 'Camellos para turistas', 'Tierra volcánica roja'] },
    { w: 'TABLAS DE DAIMIEL', f: ['Pasarelas de madera sobre el agua', 'Patos y aves acuáticas migratorias', 'Humedal de La Mancha', 'Río Guadiana'] }
  ],
  professions: [
    { w: 'FISCAL DE MENORES', f: ['Acusación pública en el juzgado', 'Proteger los derechos del niño', 'Leyes y reformas', 'Toga'] },
    { w: 'PROCURADOR JUDICIAL', f: ['Representar al cliente ante el juzgado', 'Llevar las notificaciones del juez', 'Tribunales', 'Abogado'] },
    { w: 'FORENSE DE AUTOPSIAS', f: ['Examinar el cadáver', 'Determinar la hora y causa de la muerte', 'CSI de laboratorio', 'Bisturí'] },
    { w: 'CRIMINÓLOGO', f: ['Perfil psicológico del asesino', 'Estudiar por qué se comete el delito', 'Pruebas e indicios', 'Investigación'] },
    { w: 'PERITO CALÍGRAFO', f: ['Descubrir si la firma es falsa', 'Comparar letras manuscritas con lupa', 'Juicios por testamento', 'Documentos'] },
    { w: 'TOPÓGRAFO', f: ['Trípode amarillo con teodolito óptico', 'Medir desniveles del terreno', 'Obras de carreteras', 'Chaleco naranja'] },
    { w: 'GEÓLOGO DE MINAS', f: ['Estudiar capas de rocas y minerales', 'Martillo de punta afilada en la mochila', 'Fallas tectónicas', 'Piedras'] },
    { w: 'VULCANÓLOGO', f: ['Traje plateado aluminizado contra el calor', 'Tomar muestras de lava incandescente', 'Gases y ceniza', 'Erupción'] },
    { w: 'METEORÓLOGO DEL TIEMPO', f: ['Mapa con soles y nubes en televisión', 'Explicar borrascas y anticiclones', 'Radar de lluvias', 'Pronóstico'] },
    { w: 'OCEANÓGRAFO', f: ['Barco científico en alta mar', 'Sondas que bajan a miles de metros', 'Corrientes marinas y plancton', 'Océanos'] },
    { w: 'BOTÁNICO DE PLANTAS', f: ['Clasificar especies de flores raras', 'Herbario de hojas prensadas en papel', 'Lupa de bolsillo en el campo', 'Plantas'] },
    { w: 'ZOÓLOGO DE FAUNA', f: ['Estudiar el comportamiento de los animales', 'Cámaras trampa con infrarrojos', 'Selva o sabana', 'Biólogo'] },
    { w: 'GENETISTA DE ADN', f: ['Doble hélice con bases A C G T', 'Secuenciador genético en el laboratorio', 'Herencia de enfermedades', 'Microscopio'] },
    { w: 'BIOQUÍMICO', f: ['Proteínas y enzimas en probetas', 'Investigar medicamentos contra virus', 'Cultivos en placas de Petri', 'Bata'] },
    { w: 'PALEONTÓLOGO DE DINOSAURIOS', f: ['Pincel para limpiar arena de huesos', 'Fósil de T-Rex en la roca', 'Millones de años atrás', 'Excavación'] },
    { w: 'RESTAURADOR DE ARTE', f: ['Limpiar barniz viejo de cuadros', 'Quitar el tizne sin dañar la pintura', 'Museo con lupa y disolvente', 'Obras clásicas'] },
    { w: 'CONSERVADOR DE MUSEO', f: ['Decidir qué cuadros se exponen en las salas', 'Controlar humedad y temperatura de vitrinas', 'Historiador del arte', 'Catálogo'] },
    { w: 'LUTHIER DE GUITARRAS', f: ['Construir instrumentos de madera a mano', 'Ajustar el puente y el mástil al milímetro', 'Barniz de gomalaca', 'Taller artesano'] },
    { w: 'TAXIDERMISTA', f: ['Disecar animales para cazadores', 'Ojos de cristal en cabeza de ciervo', 'Piel cosida sobre molde de yeso', 'Taller'] },
    { w: 'SOMMELIER / CATADOR DE VINOS', f: ['Hacer girar la copa y oler los aromas', 'Escupir en el catavinos tras probar', 'Carta de vinos del restaurante caro', 'Maridaje'] }
  ],
  sports: [
    { w: 'LUCHA GRECORROMANA', f: ['Tatamí circular', 'Mallas ceñidas roja o azul', 'Derribar sin agarrar por las piernas', 'Olímpico'] },
    { w: 'JIU-JITSU BRASILEÑO', f: ['Llaves de sumisión en el suelo', 'Ahogamiento y palancas de brazo', 'Kimono gi resistente', 'Cinturón'] },
    { w: 'MUAY THAI / BOXEO TAILANDÉS', f: ['Arte de las ocho extremidades', 'Golpes de codo y rodilla permitidos', 'Música tradicional durante el combate', 'Ring'] },
    { w: 'KENDO JAPONÉS', f: ['Espada de bambú shinai', 'Armadura con máscara de reja men', 'Gritos al golpear en la cabeza', 'Artes marciales'] },
    { w: 'CAPOEIRA BRASILEÑA', f: ['Danza marcial al ritmo de berimbau', 'Rueda de gente cantando y aplaudiendo', 'Patadas giratorias sin parar', 'Brasil'] },
    { w: 'PARKOUR URBANO', f: ['Saltar muros y barandillas de la ciudad', 'Trepar fachadas con las manos', 'Caída rodando para no romperse nada', 'Zapatillas'] },
    { w: 'CALISTENIA EN EL PARQUE', f: ['Dominadas en barras de metal al aire libre', 'Hacer la bandera horizontal con el cuerpo', 'Fuerza sin pesas', 'Músculos'] },
    { w: 'HALTEROFILIA EN DOS TIEMPOS', f: ['Arrancada y dos tiempos', 'Magnesio blanco en las manos', 'Cinturón de cuero lumbar', 'Dejar caer la barra'] },
    { w: 'PULLOVER / PRESS DE BANCA', f: ['Tumbarse en el banco plano', 'Bajar la barra con discos al pecho', 'Empujar con fuerza hacia arriba', 'Pecho'] },
    { w: 'SENTADILLA CON BARRA', f: ['Barra pesada apoyada en los trapecios', 'Flexionar rodillas como sentarse', 'Culo al suelo', 'Piernas fuertes'] },
    { w: 'PESO MUERTO', f: ['Levantar la barra desde el suelo recto', 'Espalda lumbar y glúteos fuertes', 'Discos rebotando en el suelo', 'Gimnasio'] },
    { w: 'SPINNING / CICLISMO INDOOR', f: ['Bici estática con volante de inercia pesado', 'Música discotequera con luces apagadas', 'Monitor gritando ¡arriba del sillín!', 'Sudar a mares'] },
    { w: 'AQUAGYM EN PISCINA', f: ['Moverse en el agua al ritmo de música', 'Churros flotantes de espuma', 'Gimnasia suave para jubilados', 'Cloro'] },
    { w: 'MARCHA ATLÉTICA', f: ['Mover las caderas sin despegar ambos pies del suelo', 'Tarjetas rojas de los jueces por volar', 'Veinte o cincuenta kilómetros', 'Pista'] },
    { w: 'ULTRAMARATÓN DE MONTAÑA', f: ['Cien kilómetros por senderos de noche', 'Frontal de luz en la cabeza', 'Bastones de trail y mochila con agua', 'Llegar a meta'] },
    { w: 'DUATLÓN', f: ['Correr en zapatillas', 'Coger la bici de carretera', 'Volver a correr a pie hasta la meta', 'Transición rápida'] },
    { w: 'ORIENTACIÓN EN EL BOSQUE', f: ['Mapa topográfico con balizas escondidas', 'Pinza para marcar la tarjeta de control', 'Brújula en el dedo gordo', 'Correr por árboles'] },
    { w: 'TIRO CON PISTOLA DE PRECISIÓN', f: ['Un solo brazo extendido de lado', 'Gafas con parche en el ojo izquierdo', 'Diana a diez o cincuenta metros', 'Paciencia'] },
    { w: 'SKEET DE TIRO AL VUELO', f: ['Dos casetas que lanzan platos cruzados', 'Seguimiento rápido con la escopeta', 'Romper ambos platos en el aire', 'Puntería'] },
    { w: 'PENTATLÓN MODERNO', f: ['Esgrima natación salto a caballo carrera y tiro', 'Cinco deportes combinados en un día', 'Atleta completo', 'Medalla'] }
  ],
  actions: [
    { w: 'PERDER EL TIEMPO EN EL MÓVIL', f: ['Hacer scroll infinito en TikTok', 'Pasar horas sin darse cuenta', 'Dedo pulgar rozando pantalla', 'Procrastinar'] },
    { w: 'DEJAR EN VISTO / DOBLE CHECK AZUL', f: ['Leer el mensaje de WhatsApp y no responder', 'Indiferencia o despiste', 'Dos palomitas azules', 'Enfado del otro'] },
    { w: 'MANDAR UN AUDIO DE DIEZ MINUTOS', f: ['Podcast en vez de mensaje de voz', 'Hablar solo por la calle', 'Botón de micrófono mantenido', 'Poner a 2x de velocidad'] },
    { w: 'SILENCIAR EL GRUPO DE WHATSAPP', f: ['Cien mensajes por minuto', 'Poner en silencio durante un año', 'Quitar notificaciones', 'Familia o amigos'] },
    { w: 'BORRAR EL HISTORIAL DEL NAVEGADOR', f: ['Eliminar cookies y páginas visitadas', 'Modo incógnito que olvidaste poner', 'Ctrl más Shift más Supr', 'Secreto'] },
    { w: 'DESENREDAR EL CABLE DE LOS AURICULARES', f: ['Nudo imposible salido del bolsillo', 'Tirar con paciencia de los extremos', 'Diez minutos antes de escuchar música', 'Cable'] },
    { w: 'LIMPIAR LA PANTALLA CON LA CAMISETA', f: ['Quitar huellas de dedos grasientos', 'Echar vaho con la boca antes', 'Dobladillo del algodón', 'Queda reluciente'] },
    { w: 'PROBARSE TRES VECES LA MISMA ROPA', f: ['Delante del espejo del probador', 'No saber qué ponerse para la fiesta', 'Pedir opinión a la amiga', 'Duda'] },
    { w: 'BUSCAR APARCAMIENTO DANDO VUELTAS', f: ['Quince vueltas a la misma manzana', 'Seguir a un peatón con llaves en la mano', 'Desesperación al volante', 'Hueco libre'] },
    { w: 'APARCAR EN LÍNEA A LA PRIMERA', f: ['Maniobra perfecta marcha atrás', 'Sin tocar los bordillos', 'Meter el coche en un hueco justo', 'Orgullo de conductor'] },
    { w: 'DARLE UN GOLPE AL RETROVISOR', f: ['Calle estrechísima con coches a los dos lados', 'Sonido clack de plástico contra plástico', 'Mirar por el espejo con el corazón a mil', 'Poco espacio'] },
    { w: 'FRENAR EN SECO EN EL ÁMBAR', f: ['Chirrido de neumáticos en el cruce', 'Miedo a la foto del radar de semáforo', 'Las cosas del asiento del copiloto se caen', 'Susto'] },
    { w: 'CEDER EL ASIENTO A UNA ABUELA', f: ['Autobús o metro lleno', 'Levantarse educadamente', 'Muchísimas gracias hijo', 'Barra de agarre'] },
    { w: 'AGUANTARSE LAS GANAS DE IR AL BAÑO', f: ['Mover las piernas en el sitio nervioso', 'Buscar un bar desesperado para pedir café', 'Alivio infinito al entrar', 'Vejiga llena'] },
    { w: 'COLARSE SIN QUERER EN UNA FOTO AJENA', f: ['Turistas posando delante de un monumento', 'Pasar por detrás mirando el móvil', 'Fotobomb involuntario', 'Disculparse'] },
    { w: 'SALUDAR A ALGUIEN QUE NO ERA', f: ['Confundir a un desconocido por la espalda', 'Disimular tocándose el pelo como si nada', 'Tierra trágame de vergüenza', 'Mano levantada'] },
    { w: 'TROPEZARSE Y DISIMULAR CORRIENDO', f: ['Engancharse con una baldosa suelta', 'Dar dos zancadas rápidas fingiendo prisa', 'Mirar al suelo culpando a la calle', 'Risa de los demás'] },
    { w: 'CANTAR LA LETRA INVENTADA EN INGLÉS', f: ['Wachuwachu en el coche a grito pelado', 'No saberse la letra de la canción pop', 'Balbucear palabras que riman', 'Radio puesta'] },
    { w: 'QUEDARSE PEGADO A LAS SÁBANAS', f: ['Cinco minutos más por favor', 'Apagar tres alarmas seguidas', 'Calorcito rico del nórdico en invierno', 'Llegar tarde'] },
    { w: 'VOLVER A CASA DESCALZO TRAS LA FIESTA', f: ['Tacones en la mano con dolor de pies', 'Seis de la mañana en la acera fría', 'Esperar el primer metro', 'Pies negros'] }
  ],
  nature: [
    { w: 'GELIDAS AGUAS DE CASCADA', f: ['Zambullirse en verano', 'Respiración cortada del frío', 'Piedras resbaladizas con musgo', 'Pozas de montaña'] },
    { w: 'BORRASCA FILOMENA', f: ['Nieve histórica en Madrid', 'Árboles caídos por el peso del hielo', 'Esquiar por la Gran Vía', 'Enero de 2021'] },
    { w: 'GOTA FRÍA / DANA', f: ['Lluvias torrenciales de otoño', 'Ramblas secas desbordadas', 'Levante mediterráneo', 'Inundación'] },
    { w: 'CALIMA DEL SAHARA', f: ['Cielo naranja con polvo en suspensión', 'Lluvia de barro en los coches', 'Viento cálido del sur', 'Canarias'] },
    { w: 'VIENTO TRAMONTANA', f: ['Sopla fuerte en el norte de Cataluña', 'Viento frío y seco que vuelve loca a la gente', 'Costa Brava y Pirineos', 'Cielo despejado'] },
    { w: 'VIENTO DE LEVANTE', f: ['Tarifa y Cádiz', 'Viento constante que no deja poner la sombrilla', 'Kitesurf y cometas', 'Caluroso y pesado'] },
    { w: 'VIENTO CIERZO', f: ['Valle del Ebro en Zaragoza', 'Viento helado del noroeste que cala los huesos', 'Boina y bufanda apretada', 'Aragón'] },
    { w: 'BRISA MARINA / VIRAZÓN', f: ['Viento suave que entra del mar por la tarde', 'Alivio del calor sofocante en la playa', 'Mover las hojas de las palmeras', 'Olor a salitre'] },
    { w: 'HELADA MATINAL / ESCARCHA', f: ['Hierba del campo blanca y quebradiza', 'Cristales de hielo fino al amanecer', 'Bajo cero grados', 'Pisar crujiendo'] },
    { w: 'CENCINICIENTA / CENCIMIENTA / CENCENCERRADA', f: ['Niebla helada que congela las ramas', 'Árboles cubiertos de púas de hielo blanco', 'Invierno en la meseta', 'Frío siberiano'] },
    { w: 'CHUBASCO PASAJERO', f: ['Lluvia fuerte que dura diez minutos', 'Sale el sol enseguida después', 'Arcoíris en el horizonte', 'Gotas gordas'] },
    { w: 'CHIRIIMIRI / CALABOBOS', f: ['Lluvia finísima que apenas se ve pero empapa', 'Típica del norte en Bilbao o San Sebastián', 'Caminar sin paraguas confiado', 'Húmedo'] },
    { w: 'CHARCO DE BARRO', f: ['Niños con botas de agua saltando dentro', 'Salpicar los pantalones', 'Tierra mojada tras la tormenta', 'Agua marrón'] },
    { w: 'ARROYO DE MONTAÑA', f: ['Río diminuto que baja saltando piedras', 'Sonido relajante de agua corriendo', 'Bebedero de vacas salvajes', 'Trigo'] },
    { w: 'GOLONDRINAS VOLANDO BAJO', f: ['Presagio tradicional de lluvia inminente', 'Cazan insectos que bajan por la humedad', 'Cielo gris de tormenta', 'Pájaros'] },
    { w: 'OLOR A TIERRA MOJADA / PETRICOR', f: ['Primeras gotas de lluvia de verano en el asfalto', 'Aroma inconfundible y fresco', 'Tierra seca que bebe agua', 'Tormenta'] },
    { w: 'CANTO DE LAS CHICHARRAS', f: ['Sonido ensordecedor a las tres de la tarde', 'Sol de justicia en agosto', 'Encaramadas a los troncos de los pinos', 'Calor'] },
    { w: 'MIGRACIÓN DE CIGÜEÑAS', f: ['Campanarios con nidos gigantes de ramas', 'Por San Blas la cigüeña verás', 'Vuelo en uve en el cielo azul', 'Parejas'] },
    { w: 'DESHOJE DE OTOÑO', f: ['Alfombra crujiente de hojas marrones', 'Pasear por el parque pisando hojas secas', 'Árboles desnudos', 'Viento fresco'] },
    { w: 'FLORACIÓN DE LOS CEREZOS DEL JERTE', f: ['Valle de Cáceres teñido de blanco como nieve', 'Primavera en abril', 'Millones de flores blancas', 'Fotografías'] }
  ],
  moviesTv: [
    { w: 'EL LABERINTO DEL FAUNO', f: ['Guillermo del Toro', 'Monstruo con ojos en las palmas de las manos', 'Niña Ofelia', 'Guerra civil'] },
    { w: 'VOLVER (ALMODÓVAR)', f: ['Penélope Cruz cantando tango', 'Viento solano de La Mancha', 'Cadáver en el congelador', 'Cine español'] },
    { w: 'TODO SOBRE MI MADRE', f: ['Premio Óscar de Almodóvar', 'Agrada a Manuela', 'Actrices de teatro', 'Barcelona'] },
    { w: 'MAR ADENTRO', f: ['Ramón Sampedro en la cama', 'Javier Bardem tetrapléjico', 'Volar hacia el mar', 'Eutanasia'] },
    { w: 'OCHO APELLIDOS VASCOS', f: ['Rafa de Sevilla fingiendo ser vasco', 'Amaia en el pueblo', 'Bromas de tópicos', 'Película más taquillera'] },
    { w: 'LA ISLA MÍNIMA', f: ['Dos policías investigando en las marismas', 'Coches en caminos de arrozal', 'Fotografía aérea cenital', 'Crimen'] },
    { w: 'TORRENTE EL BRAZO TONTO DE LA LEY', f: ['Policía corrupto del Atlético de Madrid', 'Santiago Segura comiendo pipas', 'Coche clásico cutre', 'Comedia gamberra'] },
    { w: 'CELDA 211', f: ['Malamadre al mando del motín carcelario', 'Funcionario novato fingiendo ser preso', 'Cárcel amotinada', 'Acción española'] },
    { w: 'EL DÍA DE LA BESTIA', f: ['El anticristo nacerá en Madrid en Nochebuena', 'Cura bajando por el cartel de Schweppes', 'Heavy metal', 'Álex de la Iglesia'] },
    { w: 'AMANECE QUE NO ES POCO', f: ['Pueblo surrealista donde nacen hombres de la tierra', 'Todos somos contingentes pero tú eres necesario', 'Cine de culto', 'Humor absurdo'] },
    { w: 'CUÉNTAME CÓMO PASÓ', f: ['Familia Alcántara a lo largo de las décadas', 'Antonio y Mercedes en San Genaro', 'Voz de Carlos recordando', 'Serie más larga'] },
    { w: 'AQUÍ NO HAY QUIEN VIVA', f: ['Desengaño 21', 'Tres vecinos en la portería con Emilio', 'Junta urgente en el rellano', 'Radio patio'] },
    { w: 'LOS SERRANO', f: ['Taberna de jamones con Diego y Santiago', 'Al final todo era un sueño', 'Uno más uno son siete', 'Escobilla'] },
    { w: 'FÍSICA O QUÍMICA', f: ['Colegio Zurbarán con romances de alumnos', 'Medicina con amor', 'Profesores y estudiantes liados', 'Serie adolescente'] },
    { w: 'EL INTERNADO', f: ['Laguna Negra en medio del bosque misterioso', 'Monstruo en el desván y pasadizos', 'Paula y Marcos buscando a sus padres', 'Nazis'] },
    { w: 'EL MINISTERIO DEL TIEMPO', f: ['Puertas secretas para viajar al pasado', 'Patrulla con Velázquez Lope y soldados', 'Proteger la historia de España', 'Ciencia ficción'] },
    { w: 'PAQUITA SALAS', f: ['Representante de actores venida a menos', 'Magdalenas de Lardero y gin tonic', 'Brais Efe con peluca', 'Humor de los Javis'] },
    { w: 'VENENO (SERIE)', f: ['Cristina Ortiz en el Mississippi de Pepe Navarro', 'Digo veneno', 'Parque del Oeste', 'Biopic dramático'] },
    { w: 'ÉLITE (SERIE)', f: ['Colegio de ricos Las Encinas', 'Un asesinato por temporada', 'Uniformes con chaqueta roja', 'Fiestas locas de Netflix'] },
    { w: 'MACHOS ALFA', f: ['Cuatro amigos deconstruyendo su masculinidad', 'Curso para no ser machistas', 'Crisis de los cuarenta', 'Comedia actual'] }
  ],
  videogames: [
    { w: 'DARK SOULS', f: ['Has muerto en letras rojas gigantes', 'Hogueras para descansar que resucitan bichos', 'Frascos de estus dorado', 'Dificultad infernal'] },
    { w: 'BLOODBORNE', f: ['Ciudad gótica victoriana Yharnam', 'Cazadores con abrigo largo y sombrero', 'Armas con truco que se transforman', 'Pesadilla de bestias'] },
    { w: 'SEKIRO SHADOWS DIE TWICE', f: ['Ninja con brazo protésico de madera', 'Desviar katanas con el botón de parry', 'Sonido de choque de metales tin', 'Japón feudal'] },
    { w: 'SPIDER-MAN (PS5)', f: ['Balancearse entre rascacielos de Manhattan', 'Lanzar telarañas con los gatillos hápticos', 'Peter Parker y Miles Morales', 'PlayStation'] },
    { w: 'HORIZON ZERO DAWN', f: ['Aloy con arco contra dinosaurios robot', 'Mundo postapocalíptico reconquistado por la naturaleza', 'Ojo focus en la oreja', 'Cables'] },
    { w: 'GHOST OF TSUSHIMA', f: ['Samurái Jin Sakai defendiendo la isla', 'Viento que te guía soplando hojas doradas', 'Duelos a muerte con katanas', 'Zorro en el templo'] },
    { w: 'UNCHARTED (SERIE)', f: ['Nathan Drake buscando ciudades perdidas de oro', 'Cornisas que se rompen al saltar', 'Sully con su puro y avioneta', 'Aventuras'] },
    { w: 'THE LAST OF US PARTE II', f: ['Venganza de Ellie con guitarra acústica', 'Abby con sus músculos y palo de golf', 'Seattle bajo la lluvia torrencial', 'Perros rastreadores'] },
    { w: 'RATCHET & CLANK', f: ['Lombax peludo con llave inglesa gigante', 'Robot pequeño que viaja a la espalda', 'Armas disparatadas que pixelan enemigos', 'Viajes en portales'] },
    { w: 'JAK AND DAXTER', f: ['Elfo mudo y comadreja naranja graciosa', 'Orbes precursores y eco azul', 'Mundo abierto de plataformas', 'Naughty Dog'] },
    { w: 'SLY COOPER', f: ['Mapache ladrón de guante blanco con bastón', 'Tortuga Bentley en silla de ruedas y rinoceronte Murray', 'Robar cajas fuertes', 'Sigilo'] },
    { w: 'MEDIEVIL', f: ['Sir Daniel Fortesque el esqueleto sin mandíbula', 'Espada mágica y escudo en el cementerio', 'Ojo que se quita para poner en una mano', 'Gallowmere'] },
    { w: 'GRAN TURISMO', f: ['El simulador de conducción real', 'Sacarse los carnets de conducir A y B', 'Repeticiones con música de jazz suave', 'Coches pulidos'] },
    { w: 'DEATH STRANDING', f: ['Sam Porter cargando cajas a la espalda', 'Bebé BB en cápsula transparente en el pecho', 'Caminar por parajes rocosos de Islandia', 'Hideo Kojima'] },
    { w: 'DETROIT BECOME HUMAN', f: ['Androides que cobran conciencia humana', 'Elegir decisiones contrarreloj en el mando', 'Círculo de luz azul en la sien', 'Árbol narrativo'] },
    { w: 'UNTIL DAWN', f: ['Adolescentes en una cabaña nevada perseguidos', 'Efecto mariposa donde cualquiera puede morir', 'No muevas el mando para no respirar', 'Wendigo'] },
    { w: 'CUPHEAD', f: ['Dibujos animados clásicos de los años 30', 'Jefes dificilísimos de dos disparos', 'Taza y tetera disparando con los dedos', 'Música big band'] },
    { w: 'UNDERTALE', f: ['Niño que cae al subsuelo de los monstruos', 'Esqueleto Sans contando chistes malos', 'Perdonar a los enemigos en vez de luchar', 'Megalovania'] },
    { w: 'STARDEW VALLEY', f: ['Heredar la granja del abuelo en el pueblo', 'Plantar tomates y cuidar vacas felices', 'Bajar a la mina a por minerales', 'Casarse con un vecino'] },
    { w: 'CELESTE', f: ['Subir la montaña nevada con saltos y dashes', 'Fresas voladoras como desafío difícil', 'Ansiedad y superación personal', 'Plataformas píxel'] }
  ],
  characters: [
    { w: 'AQUÍLES', f: ['Talón vulnerable donde le clavaron la flecha', 'Héroe de la Ilíada en la guerra de Troya', 'Madre Tetis lo sumergió en la laguna', 'Guerrero'] },
    { w: 'HÉRCULES / HERACLES', f: ['Los doce trabajos mitológicos imposibles', 'Piel del león de Nemea sobre los hombros', 'Fuerza descomunal semidiós', 'Maza'] },
    { w: 'ULISES / ODISEO', f: ['La Odisea tardando diez años en volver a Ítaca', 'El caballo de madera de Troya', 'Penélope tejiendo esperando', 'Cíclope'] },
    { w: 'MEDUSA LA GORGONE', f: ['Pelo formado por serpientes venenosas vivas', 'Mirada que convierte en piedra', 'Perseo le corta la cabeza con un espejo', 'Mitología'] },
    { w: 'MINOTAURO DEL LABERINTO', f: ['Cuerpo de hombre con cabeza de toro bravo', 'Laberinto de Creta construido por Dédalo', 'Teseo lo mata con el hilo de Ariadna', 'Monstruo'] },
    { w: 'ÍCARO', f: ['Alas de plumas pegadas con cera de abeja', 'Volar demasiado cerca del sol caliente', 'La cera se derrite y cae al mar', 'Desobedecer al padre'] },
    { w: 'REY MIDAS', f: ['Todo lo que tocaba con la mano se convertía en oro', 'No poder ni comer pan ni besar a su hija', 'Orejas de burro como castigo', 'Ambición'] },
    { w: 'PANDORA Y SU CAJA', f: ['Abrir la vasija prohibida por curiosidad', 'Salieron todos los males del mundo fuera', 'Al fondo sólo quedó la esperanza', 'Mitología'] },
    { w: 'ZEUS / JÚPITER', f: ['Dios del rayo y rey del monte Olimpo', 'Águila y barba blanca imponente', 'Lanza truenos desde las nubes', 'Grecia'] },
    { w: 'POSEIDÓN / NEPTUNO', f: ['Tridente de tres puntas para calmar o agitar olas', 'Dios de los mares y los terremotos', 'Caballos marinos tirando de su carro', 'Océano'] },
    { w: 'HADES / PLUTÓN', f: ['Dios del inframundo y los muertos bajo tierra', 'Perro Cerbero de tres cabezas vigilando', 'Casco de invisibilidad', 'Río Estigia'] },
    { w: 'AFRODITA / VENUS', f: ['Diosa del amor de la belleza y la pasión', 'Nacida de la espuma del mar en una concha', 'Madre de Cupido con sus flechas', 'Estatua'] },
    { w: 'ATENEA / MINERVA', f: ['Diosa de la sabiduría y de la estrategia militar', 'Casco lanza escudo con la cabeza de Medusa', 'Búho sabio en el hombro', 'Atenas'] },
    { w: 'ARES / MARTE', f: ['Dios de la guerra sangrienta y la violencia', 'Lanza escudo y sed de batalla', 'Amante secreto de Afrodita', 'Olimpo'] },
    { w: 'APOLO', f: ['Dios de la música del sol y de la profecía', 'Lira de oro en las manos y arco de plata', 'Oráculo de Delfos', 'Hermano gemelo de Artemisa'] },
    { w: 'ARTEMISA / DIANA', f: ['Diosa virgen de la caza y de la luna llena', 'Arco de plata cazando ciervos en el bosque', 'Protectora de los animales salvajes', 'Fiebre'] },
    { w: 'HERMES / MERCURIO', f: ['Sandalias con alas y casco con alitas', 'Mensajero rápido de los dioses olímpicos', 'Caduceo con dos serpientes enrolladas', 'Comercio'] },
    { w: 'DIONISO / BACO', f: ['Dios del vino de las fiestas y del éxtasis', 'Corona de hojas de parra y racimos de uvas', 'Copas de vino y teatro', 'Desmadre'] },
    { w: 'CUPIDO / EROS', f: ['Niño alado gordito con pañal', 'Flechas de oro que hacen enamorarse de golpe', 'San Valentín', 'Disparar al corazón'] },
    { w: 'PEGASO EL CABALLO ALADO', f: ['Caballo blanco inmaculado con alas de pluma', 'Volar por el cielo azul de los dioses', 'Belerofonte montando para cazar a la Quimera', 'Mitología'] }
  ],
  technology: [
    { w: 'CONEXIÓN NFC', f: ['Pagar apoyando el móvil en el datáfono', 'Tarjeta del bonobús en el torno', 'Sin contacto a un centímetro', 'Chip'] },
    { w: 'MODO AVIÓN', f: ['Desconectar todas las antenas del móvil', 'No entrar llamadas ni internet', 'Obligatorio al despegar el vuelo', 'Ahorrar batería'] },
    { w: 'DESBLOQUEO POR HUELLA DACTILAR', f: ['Sensor bajo la pantalla o en el botón', 'Poner la yema del pulgar', 'Seguridad biométrica', 'Abrir móvil'] },
    { w: 'RECONOCIMIENTO FACIAL / FACE ID', f: ['Cámara que escanea los rasgos de la cara', 'Mirar la pantalla para que se abra el candado', 'No funciona con mascarilla o a oscuras', 'Móvil'] },
    { w: 'ASISTENTE DE VOZ SIRI', f: ['Oye Siri pon una alarma a las siete', 'Voz femenina que responde en el iPhone', 'Apple', 'Comandos'] },
    { w: 'PANTALLA OLED', f: ['Negros puros apagando los píxeles', 'Colores brillantes con mucho contraste', 'Pantallas de móviles de gama alta', 'Televisión'] },
    { w: 'TASA DE REFRESCO DE 120 HZ', f: ['Animaciones y scroll ultrasuaves', 'Gamer competitivo sin tirones', 'Hercios por segundo', 'Fluidez'] },
    { w: 'CARGA RÁPIDA DE 65 VATIOS', f: ['Batería llena en solo media hora', 'Cargador pesado con cable gordo', 'Calienta el móvil al chufar', 'Porcentaje'] },
    { w: 'CARGA INALÁMBRICA QI', f: ['Apoyar el móvil sobre una base plana redonda', 'Sin meter ningún cable en la clavija', 'Inducción magnética lenta', 'Mesita'] },
    { w: 'MEMORIA RAM DE 16 GIGAS', f: ['Tener veinte aplicaciones abiertas a la vez', 'Velocidad de trabajo sin que se cierre nada', 'DDR5 en el ordenador', 'Memoria volátil'] },
    { w: 'PROCESADOR OCTA-CORE', f: ['Ocho núcleos trabajando en paralelo', 'Cerebro de silicio del smartphone', 'Snapdragon o Apple Silicon', 'Nanómetros'] },
    { w: 'CÁMARA CON GRAN ANGULAR', f: ['Foto donde cabe toda la plaza o la familia', 'Efecto ojo de pez que curva las esquinas', '0.5x en el móvil', 'Lente'] },
    { w: 'CÁMARA CON TELEOBJETIVO 5X', f: ['Zoom óptico que acerca sin perder calidad', 'Ver la luna o pájaros a lo lejos', 'Lente de periscopio alargada', 'Móvil'] },
    { w: 'MODO NOCHE DE LA CÁMARA', f: ['Sujetar el móvil tres segundos quieto', 'Aclarar fotos oscuras como si fuera de día', 'Inteligencia artificial que quita grano', 'Noche'] },
    { w: 'GRABACIÓN DE VÍDEO EN 4K', f: ['Resolución altísima de cine', 'Ocupa gigas y gigas de memoria en minutos', 'Sesenta fotogramas por segundo', 'Ultra HD'] },
    { w: 'CANCELACIÓN ACTIVA DE RUIDO (ANC)', f: ['Micrófonos exteriores que anulan el motor del avión', 'Sensación de estar sumergido en silencio', 'Auriculares modernos', 'Viajar'] },
    { w: 'MODO AMBIENTE / TRANSPARENCIA', f: ['Los auriculares dejan pasar las voces de la gente', 'Poder cruzar la calle escuchando los coches', 'Sin quitarse el auricular de la oreja', 'Micrófono'] },
    { w: 'SMART TV CON ANDROID', f: ['Descargar Netflix YouTube y Spotify en la tele', 'Mando con botón directo a las aplicaciones', 'Conectar por Wi-Fi al router', 'Salón'] },
    { w: 'BARRA DE SONIDO CON SUBWOOFER', f: ['Altavoz alargado negro debajo de la televisión', 'Cajón en el suelo que retumba con explosiones', 'Bajos potentes de cine en casa', 'Audio'] },
    { w: 'ROBOT DE COCINA THERMOMIX', f: ['Picar triturar pesar y calentar en el mismo vaso', 'Pantalla con recetas guiadas paso a paso', 'Cuchillas de acero inoxidable que giran', 'Cocinilla'] }
  ],
  transport: [
    { w: 'COCHE DESCAPOTABLE', f: ['Techo de lona o duro que se esconde en el maletero', 'Melena al viento en verano', 'Gafas de sol conduciendo en la costa', 'Dos plazas'] },
    { w: 'COCHE TODOTERRENO 4X4', f: ['Tracción a las cuatro ruedas con reductora', 'Ruedas de barro y suspensión altísima', 'Subir trialeras de rocas imposibles', 'Snorkel'] },
    { w: 'COCHE DE ÉPOCA CLÁSICO', f: ['Matrícula histórica de más de treinta años', 'Faros redondos cromados y salpicadero de madera', 'Paseo de domingo con boina', 'Cuidado con mimo'] },
    { w: 'LIMUSINA BLANCA', f: ['Coche larguísimo con cristales tintados oscuros', 'Luces de neón sofás de cuero y cava dentro', 'Despedidas de soltera y bodas', 'Chofer con gorra'] },
    { w: 'COCHE FÚNEBRE', f: ['Carrocería alargada negra y solemne', 'Ataúd visible a través de los cristales traseros', 'Corona de flores encima', 'Cementerio'] },
    { w: 'COCHE DE AUTOESCUELA', f: ['Doble pedalera para que frene el profesor', 'Cartel azul con la L en el techo', 'Alumno nervioso calando el motor', 'Aprender'] },
    { w: 'COCHE DE CARRERAS DE RALLYES', f: ['Barras antivuelco tubulares dentro', 'Asientos baquet con arnés de cuatro puntos', 'Pegatinas de patrocinadores', 'Ruido de escape'] },
    { w: 'MOTO VESPA CLÁSICA', f: ['Chapa redondeada con escudo para las piernas', 'Ruedas pequeñas y cambio en el puño izquierdo', 'Paseo por Roma con casco retro', 'Scooter'] },
    { w: 'MOTO SCOOTER DE CIUDAD', f: ['Hueco bajo el asiento para meter dos cascos', 'Cambio automático sin marchas', 'Ágil esquivando atascos entre coches', 'Trabajar'] },
    { w: 'MOTO CUSTOM / CHOPPER', f: ['Manillar altísimo cuelgamonos', 'Chaqueta de cuero negro con flecos y casco huevo', 'Tubos de escape libres ruidosos', 'Harley'] },
    { w: 'MOTO DE TRIAL', f: ['Sin asiento para ir siempre de pie', 'Saltar sobre rocas gigantes de río', 'Ruedas con poquísima presión de aire', 'Equilibrio'] },
    { w: 'CAMIÓN HORMIGONERA', f: ['Cuba gigante que no para de girar', 'Canaleta para verter el cemento fresco', 'Obra de cimientos de un edificio', 'Ruedas gordas'] },
    { w: 'CAMIÓN VOLQUETE', f: ['Caja trasera que se levanta con pistón hidráulico', 'Descargar toneladas de grava o arena de golpe', 'Cantera de áridos', 'Tierra'] },
    { w: 'GRÚA MUNICIPAL DE COCHES', f: ['Llevarse el coche mal aparcado en carga y descarga', 'Cepillo y enganche para las ruedas delanteras', 'Multa y retirada al depósito', 'Sirena'] },
    { w: 'BARRENDERA MECÁNICA DE CALLES', f: ['Cepillos redondos que giran en la acera', 'Chorro de agua para no levantar polvo', 'Depósito de aspiración ruidoso', 'Cinco de la mañana'] },
    { w: 'QUITANIEVES DE CARRETERA', f: ['Pala gigante de metal delante del camión', 'Apartar la nieve hacia la cuneta a toda velocidad', 'Esparcir sal gruesa con la tolva trasera', 'Puerto de montaña'] },
    { w: 'MÁQUINA ASFALTADORA', f: ['Olor fuerte a alquitrán negro caliente', 'Apisonadora con rodillo de acero alisando', 'Carretera en obras', 'Humo'] },
    { w: 'BARCO DE VAPOR DE PALETAS', f: ['Rueda gigante con maderas girando en popa', 'Chimenea echando humo de carbón', 'Río Misisipi en la época de Tom Sawyer', 'Campana'] },
    { w: 'BARCO PESQUERO DE ARRASTRE', f: ['Redes gigantes que bajan hasta el fondo marino', 'Gaviotas persiguiendo la popa a cientos', 'Cajas de pescado con hielo', 'Faenar'] },
    { w: 'TRANSATLÁNTICO DE PASAJEROS', f: ['Ruta histórica entre Europa y Nueva York', 'Varias chimeneas y salones de baile de época', 'Titanic o Queen Mary', 'Travesía'] }
  ],
  home: [
    { w: 'TAPÓN DE CORCHO DE BOTELLA', f: ['Sacar haciendo pop', 'Árbol alcornoque', 'Oler para ver si el vino está picado', 'Tapa'] },
    { w: 'ABRIDOR DE CERVEZA / CHAPA', f: ['Hacer palanca con el metal', 'Chapa que sale disparada al suelo', 'Llavero en el bolsillo', 'Caña'] },
    { w: 'POSAVASOS DE CORCHO O CARTÓN', f: ['Poner debajo del vaso frío', 'No manchar de cerco de agua la mesa de madera', 'Coleccionar de bares', 'Mesa'] },
    { w: 'MANTELES INDIVIDUALES', f: ['Rectángulos de plástico o bambú para un plato', 'Cena rápida sin poner el mantel grande', 'Fáciles de limpiar con una bayeta', 'Mesa'] },
    { w: 'SERVILLETTERO DE BAR', f: ['Caja de acero inoxidable con muelle', 'Sacar servilletas de papel que no limpian nada', 'Palillos en el lateral', 'Barra'] },
    { w: 'SALERO Y PIMENTERO A JUEGO', f: ['Uno con tres agujeritos y el otro con uno', 'Echar sal y pimienta a la ensalada', 'Pareja de cerámica en el centro de la mesa', 'Condimentos'] },
    { w: 'ACEITERA ANTIGOTEO MARQUINA', f: ['Cristal transparente con pico vertedor fino', 'La gota resbala y vuelve a entrar dentro', 'No manchar el mantel de aceite', 'Diseño'] },
    { w: 'TABLA DE CORTAR DE MADERA', f: ['Madera de bambú con ranura para jugos', 'Picar verduras y filetear carne con el cuchillo', 'Lavar a mano sin lavavajillas', 'Cocina'] },
    { w: 'MOLINILLO DE PIMIENTA DE MANIVELA', f: ['Girar la cabeza de madera', 'Muelas que trituran los granos negros', 'Pimienta recién molida sobre la carne', 'Restaurante'] },
    { w: 'COLADOR DE MALLA METÁLICA', f: ['Escurrir los espaguetis en el fregadero', 'Quitar los grumos a la harina', 'Mango con gancho para apoyar en el borde', 'Agujeritos'] },
    { w: 'CENTRIFUGADORA DE LECHUGA', f: ['Manivela que gira la cesta a toda velocidad', 'Quitar el agua a las hojas verdes', 'Ensalada seca y crujiente', 'Plástico'] },
    { w: 'MOLDE DESMONTABLE DE TARTA', f: ['Aro metálico con palanca que se abre', 'Base redonda con papel de horno', 'Sacar la tarta de queso sin romperla', 'Horno'] },
    { w: 'PINZAS DE COCINA METÁLICAS', f: ['Dar la vuelta a los filetes en la sartén', 'Servir ensalada o pasta sin pinchar', 'Hacer chas chas dos veces antes de usarlas', 'Cocinar'] },
    { w: 'ESPÁTULA DE SILICONA / LENGUA', f: ['Rebañar hasta la última gota de masa del bol', 'Silicona flexible que no raya la sartén', 'Pastelería y repostería', 'Cocina'] },
    { w: 'BROCHA DE REPOSTERÍA', f: ['Pintar el hojaldre con huevo batido', 'Poner mantequilla derretida en el molde', 'Pelos de silicona que no se caen', 'Cocina'] },
    { w: 'TIJERAS DE COCINA DESMONTABLES', f: ['Cortar pollo abrir briks de leche y partir pescado', 'Mango de plástico ancho', 'Muesca para romper huesos o abrir botellas', 'Cajón'] },
    { w: 'PELADOR DE VERDURAS EN FORMA DE Y', f: ['Cuchilla basculante afilada', 'Quitar la piel a la patata o zanahoria fino', 'Punta para sacar los ojos negros', 'Pelar'] },
    { w: 'DESCORAZONADOR DE MANZANAS', f: ['Tubo de metal afilado que se clava en el centro', 'Sacar el tronco con las pepitas de un golpe', 'Hacer manzana asada al horno', 'Fruta'] },
    { w: 'RALLADOR DE CUATRO CARAS', f: ['Torre de acero inoxidable con mango', 'Rallar queso grueso fino o en láminas', 'Ojo con no rallarse los nudillos', 'Zumo de limón'] },
    { w: 'PRENSA DE AJOS', f: ['Meter el diente de ajo pelado en el hueco', 'Apretar con las dos manos con fuerza', 'Sale el puré de ajo por los agujeros', 'Cocina'] }
  ],
  leisure: [
    { w: 'JUEGO DEL POKÉMON GO', f: ['Caminar por la calle mirando el móvil', 'Lanzar Pokéballs con el dedo a bichos virtuales', 'Gimnasios y pokeparadas en monumentos', 'Verano de 2016'] },
    { w: 'GEOCACHING', f: ['Buscar tesoros escondidos con coordenadas GPS', 'Cajita de plástico con libreta para firmar', 'Escondido bajo una piedra o en un árbol', 'Juego al aire libre'] },
    { w: 'JUEGO DEL HOTEL', f: ['Comprar entradas de hoteles en 3D de cartón', 'Construir edificios como el Boomerang o el Safari', 'Cobrar por noche a los que caigan', 'Juego de mesa'] },
    { w: 'JUEGO DEL TABÚ', f: ['Adivinar la palabra sin decir las prohibidas', 'Bocina que pita si haces trampa', 'Compañeros de equipo adivinando', 'Palabra secreta'] },
    { w: 'JUEGO DEL PICTIONARY', f: ['Dibujar en un bloc de notas sin hablar ni letras', 'Reloj de arena corriendo', 'El equipo gritando cosas absurdas', 'Adivinar el dibujo'] },
    { w: 'JUEGO DEL SCATTERGORIES', f: ['Dado gigante de veinte caras con letras', 'Pensar cosas que empiecen por la letra F', 'Rellenar doce categorías contrarreloj', 'Tirar del boli'] },
    { w: 'JUEGO DE LA RAYUELA', f: ['Tiza dibujada en el suelo de la acera', 'Piedra que se tira a las casillas numeradas', 'Pata coja saltando sin pisar la raya', 'Cielo'] },
    { w: 'SALTAR A LA COMBA', f: ['Cuerda girando sobre la cabeza', 'Canciones infantiles al ritmo del salto', 'Comba doble / doble Dutch', 'Recreo de colegio'] },
    { w: 'JUGAR A LAS CHAPAS', f: ['Chapas de botellines con foto de ciclistas dentro', 'Circuito de tiza en el suelo con curvas', 'Tirar con el dedo índice y pulgar', 'No salirse de la pista'] },
    { w: 'JUGAR AL ESCONDITE INGLÉS', f: ['Uno dos tres al escondite inglés sin mover las manos ni los pies', 'Girar la cabeza de golpe', 'Si te pillan moviéndote vuelves al principio', 'Pared'] },
    { w: 'JUGAR AL PILLA-PILLA', f: ['El que la lleva corre detrás de los demás', 'Tocar con la mano y gritar ¡la llevas tú!', 'Casa para estar a salvo', 'Patio'] },
    { w: 'JUGAR A POLIS Y CACOS', f: ['Dos equipos divididos en ladrones y policías', 'Perseguir y meter en la cárcel vigilada', 'Los cacos pueden salvar a sus amigos tocando la mano', 'Juego de correr'] },
    { w: 'JUGAR A LA GALLINITA CIEGA', f: ['Pañuelo atado tapando los ojos', 'Dar tres vueltas para marearse en el centro', 'Tocar a alguien con las manos y adivinar quién es', 'Juego tradicional'] },
    { w: 'JUGAR AL BALÓN PRISIONERO', f: ['Dos campos divididos por una línea', 'Lanzar el balón a dar a los contrarios', 'Si te da vas al cementerio detrás', 'Esquivar la pelota'] },
    { w: 'JUGAR A LA GOMA ELÁSTICA', f: ['Goma larga sujeta entre los tobillos de dos personas', 'Saltar pisar y enredarse siguiendo una cancioncilla', 'Subir la altura a rodillas cintura y axilas', 'Recreo'] },
    { w: 'HACER PAPIROFLEXIA / ORIGAMI', f: ['Plegar papel cuadrado sin usar tijeras ni pegamento', 'Hacer una grulla un barco o una pajarita', 'Arte tradicional japonés', 'Doblar esquinas'] },
    { w: 'ARMAR UN PUZZLE DE MIL PIEZAS', f: ['Separar primero las piezas de las esquinas y bordes', 'Mesa del salón ocupada durante tres semanas', 'La angustia de que falte la última pieza', 'Encajar'] },
    { w: 'PINTAR POR NÚMEROS', f: ['Lienzo con zonas numeradas pequeñas', 'Botes de acrílico con el número correspondiente', 'Pincel fino para no salirse de la raya', 'Relajante'] },
    { w: 'HACER GANCHILLO / CROCHET', f: ['Aguja con gancho en la punta', 'Ovillos de lana de colores', 'Tejer bufandas mantas o muñecos amigurumi', 'Puntos y vueltas'] },
    { w: 'HACER PUNTO DE CRUZ', f: ['Tela de cañamazo con agujeros cuadrados', 'Aguja sin punta e hilos mouliné', 'Crucecitas bordadas que forman un dibujo', 'Cuadro de bebé'] }
  ],
  culture: [
    { w: 'CONCURSO DE CASTILLOS DE ARENA', f: ['Cubos y palas en la playa', 'Murallas almenas y conchas pegadas', 'Esperar a que la marea alta lo destruya', 'Verano'] },
    { w: 'ENCIERRO DE SAN FERMÍN', f: ['Ocho de la mañana en la cuesta de Santo Domingo', 'Seis toros bravos y cabestros corriendo', 'Corredores con periódico enrollado', 'Pamplona'] },
    { w: 'TXUPINAZO DE SAN FERMÍN', f: ['Seis de julio a las doce en punto', 'Cohete que da inicio a la fiesta', 'Pañuelos rojos en alto en la plaza del ayuntamiento', 'Pamplona'] },
    { w: 'PLAZA DE TOROS DE LAS VENTAS', f: ['Feria de San Isidro en mayo', 'Tendidos del siete exigentes', 'Ladrillo mudéjar neomudéjar', 'Madrid'] },
    { w: 'CABEZUDOS Y GIGANTES', f: ['Figuras enormes de cartón piedra que bailan', 'Cabezudos persiguiendo a los niños con vejigas', 'Dulzaina y tamboril', 'Fiestas de pueblo'] },
    { w: 'BATALLA DE FLORES DE VALENCIA', f: ['Carrozas engalanadas con miles de flores', 'Raquetas para defenderse de los claveles lanzados', 'Paseo de la Alameda en julio', 'Colores y aroma'] },
    { w: 'ENTIERRO DE LA SARDINA', f: ['Miércoles de ceniza fin del Carnaval', 'Procesión fúnebre de mentira llorando de risa', 'Quemar una sardina gigante de cartón', 'Luto divertido'] },
    { w: 'CONCURSO DEL COAC EN EL FALLA', f: ['Teatro Falla de Cádiz', 'Coros comparsas chirigotas y cuartetos', 'Letras satíricas con humor gaditano', 'Carnaval'] },
    { w: 'TABLAO FLAMENCO', f: ['Escenario de madera que resuena con los tacones', 'Guitarras cantaores y palmas', 'Bailaora con bata de cola', 'Arte jondo'] },
    { w: 'ROMERÍA CAMPESINA', f: ['Subir a la ermita del monte en carrozas decoradas', 'Comida en el campo con familia y peña', 'Misa rociera', 'Vino y cantes'] },
    { w: 'BENDICIÓN DE ANIMALES POR SAN ANTÓN', f: ['Diecisiete de enero ante la iglesia', 'Llevar al perro gato o periquito para bendecir', 'Panecillos de San Antón', 'Protector de animales'] },
    { w: 'CORPUS CHRISTI DE TOLEDO', f: ['Calles cubiertas con toldos de lona antiguos', 'Suelo lleno de tomillo y romero aromático', 'Custodia de plata de Arfe procesionando', 'Toledo'] },
    { w: 'MISTERI D\'ELX', f: ['Drama cantado medieval en la basílica de Santa María', 'Aparato aéreo llamado Magrana que baja del techo', 'Virgen María', 'Elche en agosto'] },
    { w: 'PATIOS DE CÓRDOBA EN MAYO', f: ['Paredes blancas cubiertas de macetas azules con gitanillas', 'Concurso de patios de vecinos abiertos', 'Pozos antiguos y olor a jazmín', 'Córdoba'] },
    { w: 'CARRERAS DE CABALLOS DE SANLÚCAR', f: ['Caballos galopando por la playa mojada en bajamar', 'Desembocadura del río con Doñana enfrente', 'Apuestas de los niños en casetas de cartón', 'Agosto'] },
    { w: 'FIESTA DE LOS JUDÍOS DE ALCAÑIZ', f: ['Tamborileros tocando sin parar durante días', 'Túnicas azules y caperuzas', 'Ruta del tambor del Bajo Aragón', 'Semana Santa'] },
    { w: 'LA DANZA DE LOS ZANCOS DE ANGUIANO', f: ['Bajar la cuesta empedrada girando sobre zancos de madera', 'Faldas amarillas que vuelan', 'La Rioja en julio', 'Tradición arriesgada'] },
    { w: 'FIESTA DE MOROS Y CRISTIANOS DE ALCOY', f: ['Desfiles con trajes espectaculares de terciopelo', 'Trabuquetes disparando pólvora en las calles', 'Castillo de madera asaltado y reconquistado', 'San Jorge'] },
    { w: 'PASO DEL FUEGO DE SAN PEDRO MANRIQUE', f: ['Cruzar descalzo una alfombra de ascuas de roble ardiendo', 'Noche de San Juan en Soria', 'Llevar a alguien a hombros', 'Sin quemarse'] },
    { w: 'FIESTA DE LA VENDIMIA DE JEREZ', f: ['Pisa de la uva en el lagar ante la catedral', 'Bendición del primer mosto', 'Bodegas de vino fino y oloroso', 'Septiembre'] }
  ],
  music: [
    { w: 'SINTETIZADOR ANALÓGICO', f: ['Teclado con decenas de potenciómetros y cables jack', 'Crear ondas de sonido cuadradas y sierra', 'Música electrónica de los ochenta', 'Moog'] },
    { w: 'MESA DE MEZCLAS DE DJ', f: ['Crossfader central para pasar de una pista a otra', 'Ecualizador de graves medios y agudos', 'Auriculares con una sola oreja puesta', 'Discoteca'] },
    { w: 'PLATO TOCADISCOS DE VINILO', f: ['Aguja de diamante surcando el microsurco negro', 'Treinta y tres o cuarenta y cinco revoluciones', 'Sonido cálido con crepitar de fondo', 'Technics'] },
    { w: 'CONTROLADOR MIDI DE PADS', f: ['Cuadrícula de dieciséis botones de goma con luces', 'Lanzar samples de batería con los dedos', 'Hacer bases de hip hop en el ordenador', 'Beats'] },
    { w: 'TARJETA DE AUDIO EXTERNA', f: ['Caja roja Scarlett con entradas combinadas XLR', 'Conectar el micro y la guitarra al PC por USB', 'Ruedas de ganancia y volumen directo', 'Estudio'] },
    { w: 'AMPLIFICADOR DE VÁLVULAS', f: ['Tubos de cristal brillantes que calientan el sonido', 'Pesadísimo de transportar a los conciertos', 'Sonido rock puro y crujiente', 'Marshall o Fender'] },
    { w: 'PANTALLA DE CUATRO ALTAVOCES DE GUITARRA', f: ['Caja acústica negra 4x12 enorme', 'Colocar el cabezal del amplificador encima', 'Mueve los pantalones con el volumen', 'Escenario'] },
    { w: 'AMPLIFICADOR DE BAJO', f: ['Altavoz gigante de quince pulgadas para notas graves', 'Hacer temblar el suelo del local de ensayo', 'Bajo eléctrico', 'Bucle de efectos'] },
    { w: 'MICRÓFONO DINÁMICO SHURE SM58', f: ['Rejilla redonda plateada indestructible', 'El micro de directo más famoso del mundo', 'Sujetar con la mano en el escenario', 'Voz'] },
    { w: 'SISTEMA IN-EAR DE MONITORIZACIÓN', f: ['Auriculares moldeados a la oreja del cantante', 'Petaca inalámbrica enganchada al cinturón', 'Escuchar la mezcla sin el ruido del escenario', 'Concierto'] },
    { w: 'FADER DE VOLUMEN DE MESA', f: ['Palanca deslizante vertical que sube y baja decibelios', 'Motorizado en mesas de estudio digitales', 'Hacer un fade out al final de la canción', 'Mezcla'] },
    { w: 'COMPRESOR DE AUDIO', f: ['Reducir el rango dinámico de la voz', 'Controlar picos de volumen para que no sature', 'Ataque y release en milisegundos', 'Productor musical'] },
    { w: 'REVERB DE MUELLES', f: ['Efecto de eco espacial como una catedral', 'Muelle metálico que vibra dentro del ampli', 'Sonido surfero de guitarra de los sesenta', 'Ambiente'] },
    { w: 'DELAY / EFECTO DE ECO', f: ['Repite lo que tocas medio segundo después', 'Crear una atmósfera psicodélica y rítmica', 'Tap tempo con el pie', 'Repeticiones'] },
    { w: 'PEDALERA MULTIEFECTOS DIGITAL', f: ['Pantalla con simulaciones de cien amplificadores', 'Pulsadores de metal en el suelo para cambiar preset', 'Salir directo a mesa sin cargar bafles', 'Guitarrista'] },
    { w: 'CEJILLA DE PLÁSTICO', f: ['Afinación rápida', 'Tocar acordes abiertos en cualquier traste', 'Goma elástica o muelle fuerte', 'Guitarra'] },
    { w: 'CORREA DE GUITARRA BORDADA', f: ['Colgarse el instrumento al hombro de pie', 'Dibujos psicodélicos o cuero negro', 'Enganches de seguridad en los botones', 'Tocar en directo'] },
    { w: 'CLAVIJERO DE AFINACIÓN', f: ['Seis palomillas de metal en la pala', 'Apretar la cuerda para subir el tono', 'Engranaje de tornillo sin fin', 'Guitarra'] },
    { w: 'PUENTE DE GUITARRA FLOTANTE', f: ['Palanca de vibrato para hacer dive bombs', 'Bajar el tono imitando un motor de avión', 'Floyd Rose con bloqueo de cuerdas', 'Solos heavies'] },
    { w: 'JACK DE CABLE DE INSTRUMENTO', f: ['Clavija gruesa de 6.3 milímetros dorada', 'Ruido de zumbido si tocas la punta con el dedo', 'Conectar la guitarra al pedal o ampli', 'Mono'] }
  ],
  body: [
    { w: 'LUNAR DE LA PIEL', f: ['Mancha marrón o negra congénita', 'Vigilar si cambia de forma o tamaño con el sol', 'Diócesis de dermatología', 'Cara o cuerpo'] },
    { w: 'PECA EN LA NARIZ', f: ['Puntitos marrones en personas pelirrojas', 'Salen más en verano con el sol', 'Mejillas y hombros', 'Piel clara'] },
    { w: 'VERRUGA DE LA MANO', f: ['Bultito áspero en la piel por virus', 'Quemar con nitrógeno líquido helado', 'Dermatología', 'Dedo'] },
    { w: 'CICATRIZ DE OPERACIÓN', f: ['Marca blanca o rosa que queda tras un corte', 'Puntos de sutura que se retiraron', 'Herida curada para siempre', 'Piel'] },
    { w: 'ESTRÍAS DE LA PIEL', f: ['Líneas blancas por estiramiento rápido', 'Crecimiento o cambios bruscos de peso', 'Barriga muslos o brazos', 'Piel'] },
    { w: 'CELULITIS EN LOS MUSLOS', f: ['Piel de naranja con hoyitos', 'Acúmulo de grasa bajo la piel', 'Piernas y glúteos', 'Cremas reductoras'] },
    { w: 'OJERAS BAJO LOS OJOS', f: ['Bolsas oscuras moradas por no dormir', 'Cansancio acumulado tras una noche en vela', 'Ponerse rodajas de pepino frío o corrector', 'Cara'] },
    { w: 'PATA DE GALLO', f: ['Arrugas que salen al sonreír junto al ojo', 'Paso de los años', 'Líneas de expresión en las sienes', 'Botox'] },
    { w: 'PAPADA BAJO LA BARBILLA', f: ['Pliegue de grasa y piel que cuelga del cuello', 'Al bajar la cabeza mirando el móvil', 'Doble mentón', 'Foto desde abajo'] },
    { w: 'CEÑOHURTADO / ENTRECEJO', f: ['Arrugar la frente al enfadarse o concentrarse', 'Pelo continuo de unicejo / Frida Kahlo', 'Entre las dos cejas', 'Gesto'] },
    { w: 'HOYUELOS DE LAS MEJILLAS', f: ['Huequitos adorables que se hunden al sonreír', 'Genético en las mejillas', 'Cara simpática', 'Risa'] },
    { w: 'DIENTE DE JUICIO / CORDAL', f: ['Cuatro muelas del fondo que salen a los veinte años', 'Dolor tremendo al empujar las demás', 'Sacar con el dentista en quirófano', 'Mandíbula'] },
    { w: 'INCISIVOS PALETAS', f: ['Dos dientes centrales superiores delanteros', 'Morder la manzana crujiente', 'Sonrisa de conejo', 'Boca'] },
    { w: 'COLMILLOS CANINOS', f: ['Dientes puntiagudos para desgarrar comida', 'Vampiro de Drácula', 'Al lado de los incisivos', 'Boca'] },
    { w: 'FRENILLO DE LA LENGUA', f: ['Telilla debajo de la lengua que la une al suelo', 'Cortar a los bebés si no pueden mamar bien', 'Boca', 'Lengua'] },
    { w: 'CANAL DE LA ESPALDA', f: ['Surco central a lo largo de la columna vertebral', 'Bajar una gota de sudor por la espalda', 'Entre los dos omóplatos', 'Músculos'] },
    { w: 'OMÓPLATO / PALETILLA', f: ['Hueso plano triangular en la parte alta de la espalda', 'Mover los brazos y sentir que sobresale como un ala', 'Espalda', 'Hueso'] },
    { w: 'GEMELOS DE LA PIERNA', f: ['Músculo con dos cabezas detrás de la pantorrilla', 'Subir cuestas empinadas en zapatillas', 'Se sube el gemelo con un dolor horrible de noche', 'Pierna'] },
    { w: 'ESPINILLA DE LA PIERNA', f: ['Hueso de la tibia por delante sin grasa protectora', 'Golpearse con la mesa de centro y ver las estrellas', 'Espinilleras de fútbol para proteger', 'Pierna'] },
    { w: 'TENDÓN DE AQUILES', f: ['Tendón más grueso y fuerte del cuerpo', 'Une el gemelo al talón por detrás', 'Vulnerabilidad mítica de Aquiles', 'Tobillo'] }
  ],
  clothing: [
    { w: 'TRAJE DE FLAMENCA / GITANA', f: ['Volantes almidonados con lunares de colores', 'Feria de Abril y romerías', 'Flor grande en lo alto de la cabeza', 'Mantoncillo'] },
    { w: 'PARPUSA DE CHULAPO', f: ['Gorra clásica madrileña de cuadros pequeños', 'Fiesta de la Paloma y San Isidro', 'Clavel rojo en la solapa', 'Castizo'] },
    { w: 'MONTERA DE TORERO', f: ['Gorro negro de terciopelo con dos borlas laterales', 'Lanzar a la arena para brindar el toro', 'Cabeza del matador', 'Plaza'] },
    { w: 'PEINETA ESPAÑOLA', f: ['Carey o nácar alto calado con dibujos', 'Sujetar la mantilla negra de Semana Santa', 'Moño alto de pelo', 'Tradicional'] },
    { w: 'MANTILLA NEGRA', f: ['Encaje de blonda sobre la peineta alta', 'Luto solemne del Jueves y Viernes Santo', 'Semana Santa andaluza y madrileña', 'Elegante'] },
    { w: 'BOINA VASCA / TXAPELA', f: ['Gorro plano de lana negra sin visera', 'Rabillo fino en el centro', 'Típico del País Vasco y abuelos del campo', 'Cabeza'] },
    { w: 'ZAPATILLAS DE ESPARTO / ALPARGATAS', f: ['Suela de cuerda trenzada y lona fresca', 'Cintas largas para atar al tobillo', 'Verano mediterráneo artesano', 'Pies frescos'] },
    { w: 'MENORQUINAS / AVARCAS', f: ['Tira de cuero en el empeine y goma de rueda reciclada', 'Menorca e Islas Baleares', 'Calzado cómodo de verano', 'Piel rústica'] },
    { w: 'BOTAS DE CAZA / CAMPERAS', f: ['Cuero engrasado con caña alta marrón', 'Cremallera exterior con borla de flecos', 'Andalucía y campo', 'Montar a caballo'] },
    { w: 'CHALECO DE PUNTO DE ABUELO', f: ['Botones delanteros y cuello de pico', 'Lana fina sobre camisa de cuadros', 'Partida de dominó en el bar', 'Bolsillos pequeños'] },
    { w: 'BATÍN DE ANDAR POR CASA', f: ['Terciopelo o franela con solapas de cuadros', 'Cinturón de cuerda con borlas', 'Pipas y zapatillas en el sillón', 'Señor mayor'] },
    { w: 'BATITA DE COLEGIO', f: ['Baby a cuadros azules o rosas con botones', 'Bolsillo delantero para el pañuelo', 'Niños pequeños para no mancharse de témpera', 'Guardería'] },
    { w: 'FALDA DE TUBO ESTRECHA', f: ['Pegada a las caderas hasta debajo de la rodilla', 'Abertura trasera para poder dar pasos', 'Elegante de oficina o secretaria retro', 'Tacones'] },
    { w: 'FALDA DE TABLAS ESCOLAR', f: ['Pliegues verticales planchados a cuadros escoceses', 'Uniforme de colegio privado o de monjas', 'Cintura alta', 'Calcetines altos'] },
    { w: 'MINIFALDA VAQUERA', f: ['Corta por encima de la rodilla', 'Bolsillos traseros como un vaquero', 'Moda de verano con zapatillas', 'Piernas'] },
    { w: 'PANTALONES DE CAMPANA', f: ['Muy estrechos en el muslo y anchos a partir de la rodilla', 'Moda hippy de los setenta que vuelve', 'Tapar los zapatos al caminar', 'Vaqueros'] },
    { w: 'PANTALONES PITILLO', f: ['Pegadísimos al tobillo como una segunda piel', 'Cuesta sacárselos al desvestirse', 'Moda de los dos mil con cremallera al tobillo', 'Apretados'] },
    { w: 'PANTALONES CARGO CON BOLSILLOS', f: ['Bolsillos gigantes con solapa a los lados de los muslos', 'Tela militar resistente y ancha', 'Meter las llaves móvil y cartera sin apretar', 'Comodidad'] },
    { w: 'PANTALÓN DE PINZAS', f: ['Raya vertical planchada al medio de cada pierna', 'Pantalón formal de vestir para traje', 'Bolsillos laterales oblicuos', 'Oficina'] },
    { w: 'PANTALONES PIRATAS / CAPRI', f: ['Largo por debajo de la rodilla hasta media pantorrilla', 'Verano fresco para cuando hace calor', 'Dobladillo con botón', 'Ropa informal'] }
  ],
  everyday: [
    { w: 'SE ME HA IDO EL SANTO AL CIELO', f: ['Olvidar de repente lo que ibas a decir o hacer', 'Mente en blanco en mitad de una frase', 'Despiste momentáneo', 'Refrán'] },
    { w: 'ESTAR HASTA EN LA SOPA', f: ['Ver a la misma persona o famoso en todas partes', 'Anuncios repetitivos imposibles de evitar', 'Cansino y omnipresente', 'No parar de salir'] },
    { w: 'COGER EL TORO POR LOS CUERNOS', f: ['Afrontar un problema difícil de frente con valentía', 'Dejar de posponer una conversación incómoda', 'Tomar una decisión valiente', 'Refrán'] },
    { w: 'COGERSE UNA BORRACHERA', f: ['Beber más de la cuenta de copas el sábado noche', 'Risas descontroladas cantando abrazados', 'Ganas de vomitar y resaca al despertar', 'Alcohol'] },
    { w: 'SALIR POR PETENERAS', f: ['Cambiar de tema para esquivar una pregunta comprometida', 'Contestar algo que no tiene nada que ver', 'Escaquearse de dar explicaciones', 'Despistar'] },
    { w: 'ECHAR UNA MANO', f: ['Ayudar a un amigo desinteresadamente', 'Cargar con cajas en una mudanza de piso', 'Dar apoyo en un momento de apuro', 'Solidaridad'] },
    { w: 'IRSE A LA CAMA CON LAS GALLINAS', f: ['Acostarse tempranísimo cuando todavía hay luz', 'Cansancio brutal de haber madrugado', 'Nueve de la noche dormido', 'Abuelos'] },
    { w: 'LEVANTARSE CON EL PIE IZQUIERDO', f: ['Tener un día torcido donde todo sale mal desde que abres los ojos', 'Mala suerte y mal humor continuo', 'Tropezar y que se caiga el café', 'Superstición'] },
    { w: 'SER UÑA Y CARNE', f: ['Dos amigos inseparables que van juntos a todas partes', 'Hermandad y lealtad total', 'Conocerse desde niños', 'Siempre juntos'] },
    { w: 'PONERSE LAS BOTAS', f: ['Comer muchísimo y delicioso en una comilona', 'Banquete de boda o comida de Navidad', 'Desabrocharse el botón del pantalón de lleno', 'Hinchazón'] },
    { w: 'ESTAR COMO UNA CABRA', f: ['Hacer locuras divertidas e impredecibles', 'Tener ideas absurdas que nadie comprende', 'Estar un poco chalado', 'Risas'] },
    { w: 'NO DAR PIE CON BOLA', f: ['Equivocarse en todo lo que intentas en un partido o trabajo', 'Día torpe donde nada encaja', 'Fallo tras fallo', 'Desesperación'] },
    { w: 'QUEDARSE DE PIEDRA', f: ['Quedarse paralizado y sin palabras por una noticia bomba', 'Sorpresa monumental', 'Boca abierta de asombro', 'Inmóvil'] },
    { w: 'DAR LA CARA', f: ['Aceptar la culpa y asumir las consecuencias de un error', 'No esconderse cobardemente detrás de otros', 'Valentía y honestidad', 'Frente'] },
    { w: 'HACER DE TRIPAS CORAZÓN', f: ['Sacar fuerzas de donde no las hay para aguantar', 'Tragar saliva y seguir adelante con la tarea', 'Superar el asco o el miedo', 'Esfuerzo'] },
    { w: 'VERLE LAS OREJAS AL LOBO', f: ['Darse cuenta del peligro inminente justo a tiempo', 'Ponerse a estudiar el día antes del examen final', 'Susto que te hace reaccionar', 'Peligro'] },
    { w: 'SER UN PEDAZO DE PAN', f: ['Persona bondadosa generosa y sin ninguna maldad', 'Incapaz de hacer daño a una mosca', 'Buen corazón', 'Amable'] },
    { w: 'BUSCARLE TRES PIES AL GATO', f: ['Complicar las cosas sencillas buscando problemas donde no los hay', 'Comerse la cabeza con paranoias', 'Darle vueltas a lo evidente', 'Refrán'] },
    { w: 'TENER SANGRE FRÍA', f: ['Mantener la calma total en medio de una emergencia grave', 'No perder los nervios cuando todos gritan', 'Decisiones calculadas bajo presión', 'Control'] },
    { w: 'ANDARSE CON OJO', f: ['Tener muchísima precaución y cuidado por si acaso', 'Vigilar la cartera en el metro abarrotado', 'Estar alerta ante posibles timos', 'Atención'] }
  ]
};
