// Expansion 3: Adds ~200 more high-quality words to bring total comfortably above 2,050 concepts
export const categoryExpansions3 = {
  animals: [
    { w: 'LEMUR DE COLA ANILLADA', f: ['Madagascar', 'Ojos saltones amarillos', 'Cola a rayas blancas y negras', 'Rey Julien'] },
    { w: 'SURICATA', f: ['De pie vigilando en dos patas', 'Timón', 'Desierto del Kalahari', 'Madrigueras subterráneas'] },
    { w: 'AXOLOTE / AJOLOTE', f: ['Salamandra rosa con branquias exteriores', 'Regenerar extremidades', 'México', 'Sonriente'] },
    { w: 'PESTAÑERO / PÁJARO BOBO', f: ['Picos y patas azules', 'Islas Galápagos', 'Danza nupcial levantando patas', 'Ave marina'] },
    { w: 'PULPO DUMBO', f: ['Aletas con forma de orejas de elefante', 'Abismo marino profundo', 'Flotar en la oscuridad', 'Tentáculos'] },
    { w: 'CALAMAR GIGANTE / KRAKEN', f: ['Ojos del tamaño de platos', 'Monstruo mitológico que hunde barcos', 'Lucha con cachalotes', 'Fosas marinas'] },
    { w: 'DRAGÓN DE KOMODO', f: ['Lagarto más grande del mundo', 'Saliva con bacterias venenosas', 'Indonesia', 'Lengua bífida amarilla'] },
    { w: 'DIABLO ESPINOSO', f: ['Espinas en todo el cuerpo', 'Beber agua por la piel', 'Desierto australiano', 'Lagarto'] },
    { w: 'MONA DE GIBRALTAR / MACACO', f: ['Sin cola en el peñón', 'Robar comida a los turistas', 'Gibraltar', 'Único primate salvaje en Europa'] },
    { w: 'LINCE BOREAL / EUROPEO', f: ['Pinceles negros en las orejas', 'Mucho más grande que el ibérico', 'Bosques nevados de Escandinavia', 'Garras anchas'] }
  ],
  food: [
    { w: 'CARQUIÑOLIS', f: ['Pastas secas y duras con almendra entera', 'Mojar en vino dulce moscatel o café', 'Cataluña', 'Crujiente'] },
    { w: 'NEULAS / BARQUILLOS', f: ['Tubo fino crujiente de galleta', 'Comer en Navidad con cava', 'Cilindro hueco', 'Dulce'] },
    { w: 'PICARONES / ROSQUILLAS DE SAN ISIDRO', f: ['Tontas listas y de Santa Clara', 'Glaseado de limón o merengue blanco', 'Fiestas de Madrid en mayo', 'Masa frita'] },
    { w: 'TEJAS Y CIGARRILLOS DE TOLOSA', f: ['Almendra tostada con forma curva', 'Mantequilla y azúcar', 'País Vasco', 'Caja de regalo'] },
    { w: 'PANELLETS DE PIÑONES', f: ['Bolitas de mazapán cubiertas de piñones', 'Castañada y Todos los Santos', 'Horno doradito', 'Cataluña'] },
    { w: 'CASADIELLAS ASTURIANAS', f: ['Empanadilla frita de hojaldre', 'Relleno de nueces picadas anís y azúcar', 'Espolvoreada de azúcar glas', 'Asturias'] },
    { w: 'BORRACHUELOS MALAGUEÑOS', f: ['Empanadillas dulces bañadas en miel', 'Masa con vino blanco y anís', 'Rellenos de cabello de ángel', 'Navidad en Málaga'] },
    { w: 'FLORES MANCHEGAS', f: ['Molde de hierro en forma de cruz', 'Masa frita crujiente con azúcar y canela', 'Carnaval en La Mancha', 'Fritura de sartén'] },
    { w: 'GACHAS DULCES CON PICATOSTES', f: ['Harina tostada con leche canela y matalahúva', 'Dados de pan frito crujiente', 'Día de los Santos', 'Cuchara'] },
    { w: 'PAPARAJOTES MURCIANOS', f: ['Hoja de limonero rebozada y frita', 'No se come la hoja interior verde', 'Rebozado en azúcar y canela', 'Murcia'] }
  ],
  objects: [
    { w: 'BOTELLERO DE PARED', f: ['Soporte para guardar botellas tumbadas', 'Madera o hierro forjado', 'Vinos para envejecer en bodega', 'Cocina'] },
    { w: 'DISPENSADOR DE JABÓN DE SENSOR', f: ['Poner la mano debajo sin tocar', 'Chorro automático de espuma', 'Baño higiénico', 'Pilas'] },
    { w: 'PURIFICADOR DE AIRE CON FILTRO HEPA', f: ['Retener ácaros y polen de primavera', 'Ventilador silencioso en la habitación', 'Luz que indica la calidad del aire', 'Alergias'] },
    { w: 'VAPORIZADOR DE PRENDAS VERTICAL', f: ['Planchar la camisa colgada en la percha', 'Chorro de vapor caliente continuo', 'Quitar arrugas sin tabla', 'Rápido'] },
    { w: 'RELOJ DE ARENA DE TRES MINUTOS', f: ['Huevos pasados por agua', 'Granos que caen por el cuello estrecho', 'Cristal transparente clásico', 'Tiempo'] },
    { w: 'TENDEDERO TIPO PARAGUAS DE JARDÍN', f: ['Palo central clavado en el césped', 'Brazos que se abren con cuerdas', 'Gira con el viento para secar ropa', 'Exterior'] },
    { w: 'MANGUERA EXTENSIBLE DE RIEGO', f: ['Se hincha al abrir el grifo con presión', 'Pistola con ocho modos de chorro', 'Se encoge sola al vaciar el agua', 'Jardín'] },
    { w: 'ASPIRADOR DE CENIZAS', f: ['Depósito metálico para limpiar la chimenea', 'Filtro especial ignífugo', 'No levantar polvo negro en el salón', 'Invierno'] },
    { w: 'HIDROLIMPIADORA KÄRCHER', f: ['Chorro de agua a altísima presión', 'Limpiar el suelo de baldosas o el coche', 'Quitar el verdín de las piedras', 'Ruido de motor'] },
    { w: 'MOTOSIERRA DE GASOLINA', f: ['Cadena con dientes que gira a toda velocidad', 'Talar troncos de leña en el monte', 'Tirar de la cuerda para arrancar', 'Casco y protección'] }
  ],
  places: [
    { w: 'CABO DE GATA', f: ['Almería', 'Playas vírgenes de arena volcánica', 'Arrecife de las Sirenas', 'Faro blanco en el acantilado'] },
    { w: 'PLAYA DE LAS CATEDRALES', f: ['Arcos de roca gigantes tallados por el mar', 'Ribadeo en Galicia', 'Pasear por la arena solo en marea baja', 'Cantábrico'] },
    { w: 'CAÑÓN DEL RÍO SIL', f: ['Ribeira Sacra con viñedos en laderas verticales', 'Catamarán navegando entre gargantas', 'Monasterios románicos ocultos', 'Galicia'] },
    { w: 'BÁRDENAS REALES', f: ['Desierto de arcilla con formas lunares', 'Castildetierra con chimenea de hadas', 'Navarra', 'Películas del oeste'] },
    { w: 'GORBEIA', f: ['Cruz metálica en la cumbre más alta', 'Hayedo de Otzarreta con ramas al cielo', 'Niebla mágica vasca', 'Bizkaia y Álava'] },
    { w: 'MONTE PERDIDO', f: ['Valle de Ordesa con cascadas de cola de caballo', 'Macizo calcáreo en los Pirineos', 'Aragón', 'Fauna alpina y rebecos'] },
    { w: 'TORCAL DE ANTEQUERA', f: ['Rocas kársticas con formas de platos apilados', 'El Tornillo de piedra caliza', 'Málaga', 'Fósiles marinos prehistóricos'] },
    { w: 'SELVA DE IRATI', f: ['Segundo hayedo más grande de Europa', 'Hojas doradas cubriendo los caminos en otoño', 'Navarra y Pirineos', 'Río y embalse'] },
    { w: 'SIERRA NEVADA', f: ['Mulhacén el pico más alto de la península', 'Estación de esquí de Pradollano', 'Granada con sol y nieve a la vez', 'Tapas al bajar'] },
    { w: 'BARRIO DE SANTA CRUZ EN SEVILLA', f: ['Callejones estrechos encalados con flores', 'Plaza de Doña Elvira y patio de Banderas', 'Leyenda de Susona', 'Junto a la Giralda'] }
  ],
  professions: [
    { w: 'CRÍTICO GASTRONÓMICO', f: ['Comer gratis en los mejores restaurantes', 'Estrella Michelin en la guía roja', 'Escribir reseñas exigentes de platos', 'Paladar fino'] },
    { w: 'CATADOR DE CHOCOLATES', f: ['Probar cacao de diferentes porcentajes y orígenes', 'Crujido de la tableta al romperla / snap', 'Fundición suave en la lengua', 'Sabores'] },
    { w: 'MAESTRO QUESERO', f: ['Cuajar la leche en cubas de acero', 'Prensado en moldes de esparto', 'Maduración en cuevas con moho', 'Corteza y ojos del queso'] },
    { w: 'CORTADOR DE JAMÓN PROFESIONAL', f: ['Soporte jamonero giratorio y cuchillo fino flexible', 'Lonchas casi transparentes que caben de un bocado', 'Banquete de boda o evento', 'Tocino blanco'] },
    { w: 'MAESTRO CERVECERO', f: ['Lúpulo cebada malteada y levadura', 'Calderas de cobre en la fábrica artesana', 'Grados de alcohol y amargor IBU', 'Espuma consistente'] },
    { w: 'BARISTA DE CAFÉ DE ESPECIALIDAD', f: ['Dibujar un corazón o tulipa con la leche / latte art', 'Molinillo calibrado al gramo exacto', 'Cafetera espresso de palanca brillante', 'Granos de origen'] },
    { w: 'COCTELERO / FLAIR BARTENDER', f: ['Lanzar botellas y cocteleras por el aire', 'Hielo seco con humo misterioso', 'Copas decoradas con piel de naranja flameada', 'Bar nocturno'] },
    { w: 'CAMPANERO TRADICIONAL', f: ['Tocar a muerto repique de fiesta o aviso de fuego', 'Cuerdas o volteo manual arriesgado en la torre', 'Patrimonio inmaterial de la UNESCO', 'Bronce'] },
    { w: 'ALFARERO DE TORNO', f: ['Girar el plato con el pie o motor', 'Barro húmedo que sube entre las manos mojadas', 'Crear botijos jarrones y platos de arcilla', 'Horno de cocción'] },
    { w: 'SOPLADOR DE VIDRIO', f: ['Caña de hierro con bola incandescente al rojo vivo', 'Soplar por el tubo girando sin parar', 'Moldear con pinzas de madera mojadas', 'Taller de vidrio'] }
  ],
  sports: [
    { w: 'PELOTA VASCA CON CESTA PUNTA', f: ['Cesta de mimbre curvada atada a la muñeca', 'Frontón con la pelota más rápida del mundo', 'Chocar a más de 300 kilómetros por hora', 'Casco protector'] },
    { w: 'PELOTA MANO EN FRONTÓN', f: ['Tacos de esparadrapo protegiendo la palma', 'Dar a la pelota dura contra la pared de piedra', 'Ecos ensordecedores en la cancha', 'Frontis'] },
    { w: 'REMO DE TRAINERAS', f: ['Trece remeros y un patrón al timón', 'Olas del mar Cantábrico en la regata de la Concha', 'Bandera de San Sebastián', 'Proa al agua'] },
    { w: 'BOLO PALMA CÁNTABRO', f: ['Bolo mayor y nueve bolos en la caja', 'Tirar las bolas de madera de roble', 'Bolera de arena fina', 'Cantabria tradicional'] },
    { w: 'LUCHA LEONESA / ALUCHE', f: ['Cinturón de cuero agarrado por los rivales', 'Tirar al adversario de espaldas a la hierba', 'Mañas y caídas limpias', 'Fiestas de León'] },
    { w: 'LEVANTAMIENTO DE PIEDRA / HARRIJASOTZAILE', f: ['Piedras cilíndricas o cúbicas de 200 kilos', 'Subir la roca hasta el hombro con chaleco de cuero', 'Plaza vasca animando', 'Fuerza bruta'] },
    { w: 'CORTE DE TRONCOS / AIZKOLARI', f: ['Hacha afiladísima sobre troncos de haya verde', 'Subido encima de la madera cortando a dos pies', 'Virutas volando a toda velocidad', 'Deporte rural'] },
    { w: 'ARRASTRE DE PIEDRA CON BUEYES', f: ['Par de bueyes tirando de losa de granito pesadísima', 'Probar metros recorridos en media hora', 'Gritos del boyero con la vara', 'Tradición'] },
    { w: 'TIRO CON BALLESTA DEPORTIVA', f: ['Arco montado sobre culata de rifle', 'Gatillo mecánico con visor telescópico', 'Diana fija con flecha corta / saeta', 'Puntería militar'] },
    { w: 'SQUASH EN PISTA CERRADA', f: ['Cuatro paredes con línea de chapa metálica baja', 'Pelotita de goma negra que no bota casi nada', 'Raqueta rápida y sudor sin parar', 'Caja de cristal'] }
  ],
  actions: [
    { w: 'AGUANTAR LA RISA EN UN FUNERAL', f: ['Mirarse con un amigo en el momento más serio', 'Morderse los labios hasta que duelan', 'Toser disimulando para no soltar la carcajada', 'Pecado social'] },
    { w: 'CANTAR BAJO LA DUCHA', f: ['Efecto de eco perfecto en los azulejos mojados', 'Micrófono con la alcachofa de la ducha', 'Concierto privado desafinando a gusto', 'Agua caliente'] },
    { w: 'MORDERSE LA LENGUA', f: ['Ganas enormes de soltar una verdad incómoda', 'Callarse por educación o para no crear pelea', 'Tragar saliva en silencio', 'Contenerse'] },
    { w: 'HACER CASTILLOS EN EL AIRE', f: ['Fantasear con planes grandiosos e imposibles', 'Soñar despierto con hacerse millonario', 'Ilusión sin base real', 'Pensar despierto'] },
    { w: 'TOCAR MADERA', f: ['Gesto supersticioso para no tentar a la mala suerte', 'Buscar corriendo una mesa o silla para tocar', 'Decir no vaya a ser que pase', 'Suerte'] },
    { w: 'CRUZAR LOS DEDOS', f: ['Dedo corazón montado sobre el índice', 'Desear con todas las fuerzas que algo salga bien', 'Esperar la nota del examen', 'Suerte'] },
    { w: 'ECHARSE A TEMBLAR', f: ['Miedo repentino ante una mala noticia que viene', 'Ver al jefe llamando a su despacho', 'Nervios en el estómago', 'Temblor'] },
    { w: 'PONERSE ROJO COMO UN TOMATE', f: ['Vergüenza monumental delante de todos', 'Calor que sube a las mejillas de golpe', 'Te pillan en una mentira o te piropean', 'Cara roja'] },
    { w: 'CAER EN LA CUENTA', f: ['Entender por fin algo que no cuadraba', 'Encajar las piezas del puzzle en la cabeza', '¡Ah claro ahora lo veo!', 'Darse cuenta'] },
    { w: 'QUEDARSE BOQUIABIERTO', f: ['Sorpresa extrema donde se descuelga la mandíbula', 'Presenciar un truco de magia imposible', 'Incapaz de articular palabra', 'Asombro'] }
  ],
  nature: [
    { w: 'BOSQUE ANIMADO / ROBLEDAL', f: ['Robles centenarios con ramas retorcidas', 'Hojas lobuladas y bellotas en el suelo', 'Humedad verde con musgo en la corteza', 'Sombra misteriosa'] },
    { w: 'PINAR DE PINO PIÑONERO', f: ['Copas anchas como sombrillas verdes gigantes', 'Piñas que caen y se abren con piñones dentro', 'Suelo cubierto de pinocha seca aromática', 'Playa o dunas'] },
    { w: 'BOSQUE DE CASTAÑOS CENTENARIOS', f: ['Troncos huecos gigantes donde cabe una persona', 'Erizos verdes con pinchos en el suelo', 'Castañas dulces en noviembre', 'Otoño norteño'] },
    { w: 'CORNISA CANTÁBRICA', f: ['Prados verdes que terminan en acantilados sobre el mar', 'Vacas pastando junto a olas gigantes bravas', 'Lluvia frecuente y verde intenso', 'Norte'] },
    { w: 'RÍA GALLEGA', f: ['Brazo de mar que entra en la tierra entre montañas', 'Bateas flotantes llenas de cuerdas de mejillones', 'Pueblos marineros con barquitas', 'Galicia'] },
    { w: 'CABO DE FINISTERRE', f: ['El fin del mundo conocido por los romanos', 'Faro sobre rocas azotadas por temporales', 'Puesta de sol donde el sol se ahoga en el mar', 'Final del Camino'] },
    { w: 'ISLAS CÍES', f: ['Playa de Rodas elegida la mejor del mundo', 'Agua de color turquesa caribeña pero congelada', 'Gaviotas patiamarillas anidando', 'Ría de Vigo'] },
    { w: 'DUNAS DE MASPALOMAS', f: ['Desierto de arena dorada junto al mar azul', 'Olas de arena modeladas por el viento alisio', 'Oasis de palmeras al fondo', 'Gran Canaria'] },
    { w: 'LAGO DE SANABRIA', f: ['Mayor lago de origen glaciar de la península', 'Leyenda del pueblo sumergido de Valverde', 'Campanadas que suenan en la noche de San Juan', 'Zamora'] },
    { w: 'GOLFO DE VIZCAYA', f: ['Mar fiero con olas de diez metros en invierno', 'Pesca del bonito del norte a cacea', 'Océano salvaje', 'Navegación difícil'] }
  ],
  moviesTv: [
    { w: 'LA CASA DE PAPEL', f: ['Máscara de Dalí y monos rojos', 'Atraco a la Fábrica Nacional de Moneda y Timbre', 'El Profesor con pizarra y gafas', 'Bella Ciao cantada'] },
    { w: 'VIS A VIS', f: ['Monos amarillos en la cárcel Cruz del Sur', 'Macarena Ferreiro y Zulema Zahir', 'Peleas de presas en el patio', 'Thriller español'] },
    { w: 'EL TIEMPO ENTRE COSTURAS', f: ['Sira Quiroga modista en Tetuán y Tánger', 'Patrones de costura con mensajes secretos de espías', 'Guerra mundial y amor', 'Novela adaptada'] },
    { w: 'LOS HOMBRES DE PACO', f: ['Comisaría de San Antonio con casos disparatados', 'Paco Mariano y don Lorenzo / Mis santos cojones', 'Sara y Lucas historia de amor', 'Antena 3'] },
    { w: 'AÍDA (SERIE)', f: ['Barrio obrero de Esperanza Sur', 'El Luisma y sus despistes de ex drogadicto', 'Mauricio Colmenero en el bar Reinols', 'Machu Picchu'] },
    { w: 'CAMERA CAFÉ', f: ['Plano fijo delante de la máquina de café de la oficina', 'Jesús Quesada escaqueándose de trabajar', 'Arturo Cañas el jefe facha enfadado', 'Capítulos de cinco minutos'] },
    { w: 'UN PASO ADELANTE (UPA DANCE)', f: ['Escuela de artes escénicas de Carmen Arranz', 'Calentadores y mallas bailando en clase de Lola', 'Grupo musical que triunfó en España y Francia', 'Coreografías'] },
    { w: 'COMPAÑEROS (SERIE)', f: ['Colegio Azcona con Quimi y Valle', 'No te fallaré canción de cabecera', 'Pandi de adolescentes rebeldes', 'Años noventa'] },
    { w: 'FARMACIA DE GUARDIA', f: ['Lourdes Cano atendiendo detrás del mostrador', 'Adolfo Segura ex marido caradura con chistes', 'Guille y Quique los hijos', 'Crónicas de un barrio'] },
    { w: 'MÉDICO DE FAMILIA', f: ['Nacho Martín viudo con tres hijos', 'La Juani criada andaluza diciendo ¡Señor Nacho!', 'Chechu y el abuelo Manolo', 'Cenas multitudinarias en la cocina'] }
  ],
  videogames: [
    { w: 'POKÉMON ROJO Y AZUL', f: ['Pueblo Paleta eligiendo entre Charmander Squirtle y Bulbasaur', 'Game Boy gris clásica con cartuchos de color', 'Capturar a los 151 bichos originales', 'Profesor Oak'] },
    { w: 'SUPER MARIO 64', f: ['Saltar dentro de los cuadros del castillo de Peach', 'Mover a Mario con el joystick por primera vez en 3D', 'Coger a Bowser por la cola y lanzarlo a las bombas', '120 estrellas'] },
    { w: 'THE LEGEND OF ZELDA: OCARINA OF TIME', f: ['Tocar melodías con la flauta ocarina de doce agujeros', 'Link niño y Link adulto sacando la Espada Maestra', 'Yegua Epona cruzando la llanura de Hyrule', 'Templo del Agua'] },
    { w: 'TETRIS', f: ['Música tradicional rusa korobeiniki que no sale de la cabeza', 'Piezas geométricas tetrominós cayendo desde arriba', 'Hacer una línea recta de cuatro con la barra larga', 'Juego adictivo'] },
    { w: 'PAC-MAN / COMECIENTAS', f: ['Comer puntos amarillos en el laberinto azul', 'Cuatro fantasmas Blinky Pinky Inky y Clyde', 'Cerezas de bonus y bola grande de poder', 'Recreativas'] },
    { w: 'SPACE INVADERS', f: ['Naves alienígenas pixeladas bajando fila por fila', 'Aceleran el ritmo al quedar pocas', 'Cañón terrestre disparando tras cuatro parapetos', 'Clásico de los setenta'] },
    { w: 'STREET FIGHTER II', f: ['Ryu lanzando Hadouken y Ken con Shoryuken', 'Romper un coche a patadas en la fase de bonus', 'Elegir a Blanka Chun-Li o Guile', 'Recreativas con botones'] },
    { w: 'DONKEY KONG', f: ['Gorila gigante lanzando barriles de madera por rampas', 'Jumpman / Mario con martillo saltando fuegos', 'Subir escaleras para rescatar a Pauline en el andamio', 'Arcade original'] },
    { w: 'SONIC THE HEDGEHOG', f: ['Erizo azul supersónico rodando en forma de bola', 'Recoger anillos dorados que saltan por el aire si te golpean', 'Loopings en Green Hill Zone', 'Doctor Eggman'] },
    { w: 'CRASH BANDICOOT', f: ['Marsupial loco de pantalones azules rompiendo cajas de fruta Wumpa', 'Máscara de madera Aku Aku protegiéndole / ¡Ugadaga!', 'Huir corriendo de una roca gigante hacia la pantalla', 'PlayStation'] }
  ],
  characters: [
    { w: 'MANOLITO GAFOTAS', f: ['Niño de Carabanchel Alto', 'Abuelo Nicolás con pantalones de pana', 'El Imbécil su hermano pequeño', 'Collejas de su madre Catalina'] },
    { w: 'ZAPATILLA Y ZIPELÍN / ZIPI Y ZAPE', f: ['Gemelos traviesos uno rubio y otro moreno', 'Padre don Pantuflo Zapatilla con zapatillas en la mano', 'Cero en la cartilla escolar y cuartel de castigo', 'Tebeos de Bruguera'] },
    { w: 'PEPE GOTERA Y OTILIO', f: ['Chapuzas a domicilio que destrozan casas', 'Otilio comiéndose un bocadillo gigante de elefante', 'Pepe mandando con bombín en la cabeza', 'Bocadillos imposibles'] },
    { w: 'ROMPETECHOS', f: ['Hombrecillo bajito miope como un topo', 'Confunde carteles personas y animales con cosas absurdas', 'Gafas redondas de culo de vaso', 'Ibáñez'] },
    { w: 'EL BOTONES SACARINO', f: ['Chaval ingenuo con uniforme de botones de hotel', 'Hace estallar cafeteras o causa incendios sin querer', 'Director enfadado persiguiéndole con un bate', 'Tebeo'] },
    { w: 'ANACLETO AGENTE SECRETO', f: ['Espía cutre con traje negro pajarita y pitillo en la boca', 'Sillón con catapulta para misiones de la agencia', 'Villano Vázquez con parche en el ojo', 'Tebeos'] },
    { w: 'SUPERLÓPEZ', f: ['Superhéroe español con bigote y capa amarilla', 'Oficinista Juan López comiendo cruasanes en la mesa', 'Villa Soledad en el espacio', 'Parodia de Superman'] },
    { w: 'MAFALDA', f: ['Niña argentina que odia con toda su alma la sopa', 'Preocupada por la paz mundial y la política internacional', 'Manolito Susanita Felipe y Guille', 'Tiras cómicas de Quino'] },
    { w: 'AQUELARRE / LAS TRES MELLIZAS', f: ['Ana Teresa y Elena idénticas vestidas de colores', 'La Bruja Aburrida que las castiga enviándolas a cuentos clásicos', 'Búho parlanchín que acompaña a la bruja', 'Dibujos animados'] },
    { w: 'DAVID EL GNOMO', f: ['Siete veces más fuerte que tú veloz y siempre de buen humor', 'Gorro rojo puntiagudo y barba blanca', 'Lisa su mujer y Swift el zorro que le lleva volando', 'Médico del bosque'] }
  ],
  technology: [
    { w: 'CONVERTIDOR DE VÍDEO A HDMI', f: ['Caja adaptadora con clavijas de colores RCA rojo amarillo y blanco', 'Conectar la consola PlayStation 2 vieja a la tele moderna', 'Alimentado por cable USB', 'Señal analógica a digital'] },
    { w: 'LIMPIADOR DE AIRE COMPRIMIDO EN SPRAY', f: ['Bote metálico que expulsa chorro de aire a presión helado', 'Quitar migas y polvo entre las teclas del ordenador', 'Pajita roja fina en la boquilla', 'Frío'] },
    { w: 'PASTA TÉRMICA GRIS', f: ['Jeringa con pasta conductora de calor', 'Poner una gota del tamaño de un guisante sobre la CPU', 'Pegar el disipador metálico al procesador', 'Informática'] },
    { w: 'PULSERA ANTIESTÁTICA', f: ['Banda elástica en la muñeca con cable rizado a tierra', 'Pinza de cocodrilo enganchada a la chapa metálica', 'Evitar que una chispa queme la placa base', 'Montar PC'] },
    { w: 'CABLE ÓPTICO TOSLINK', f: ['Emite un haz de luz roja por la punta transparente', 'Sonido envolvente 5.1 directo a la barra de sonido', 'Fibra plástica que no se debe doblar en ángulo recto', 'Audio digital'] },
    { w: 'TARJETA DE SONIDO SOUND BLASTER', f: ['Placa interna con chips de procesamiento de audio', 'Conectores dorados mini jack detrás de la torre', 'Efectos envolventes para auriculares gaming', 'Ranura PCIe'] },
    { w: 'CAPTURADORA DE VÍDEO ELGATO', f: ['Cajita que graba la señal HDMI de la consola', 'Hacer streamings en Twitch desde el ordenador', 'Puerto USB 3.0 al PC sin retardo', 'Creadores de contenido'] },
    { w: 'STREAM DECK DE MACROS', f: ['Botonera con quince pantallas LCD cuadradas en miniatura', 'Poner efectos de sonido cambiar de escena y silenciar micro', 'Streamers con iconos personalizados', 'USB'] },
    { w: 'CABLE USB TIPO C REVERSIBLE', f: ['Entra en cualquier posición sin mirar cuál es el derecho', 'Carga súper rápida y transmisión de datos a gigabits', 'Conector universal obligatorio en Europa', 'Móvil'] },
    { w: 'BASE REFRIGERADORA DE PORTÁTIL', f: ['Plataforma inclinada con dos ventiladores gigantes silenciosos', 'Luces LED azules por debajo', 'Evitar que el portátil arda jugando en verano', 'Malla metálica'] }
  ],
  transport: [
    { w: 'MOTO CON SIDECAR', f: ['Pequeña bañera con tercera rueda acoplada al lateral', 'Pasajero con gafas de aviador y casco retro dentro', 'Películas antiguas de guerra o de época', 'Viajar dos personas'] },
    { w: 'TRICICLO DE REPARTO DE CARGA', f: ['Bici con caja de madera gigante delantera entre dos ruedas', 'Llevar paquetes o niños sentados con cinturón', 'Transporte ecológico urbano', 'Pedaleo asistido'] },
    { w: 'BARCO DE VELA LATINA', f: ['Vela triangular tradicional mediterránea', 'Navegar en albuferas o costas tranquilas', 'Mástil corto inclinado', 'Tradición marinera'] },
    { w: 'PATERA / EMBARCACIÓN PRECARIA', f: ['Barca de madera pequeña sin medidas de seguridad', 'Cruzar el estrecho de Gibraltar o marismas', 'Riesgo humanitario extremo', 'Mar'] },
    { w: 'BOTE SALVAVIDAS NARANJA', f: ['Cápsula cerrada insumergible colgada de pescantes', 'Raciones de agua dulce y bengalas de emergencia dentro', 'Abandonar el barco en naufragio', 'Titánic'] },
    { w: 'AVIONETA FUMIGADORA', f: ['Volar a dos metros sobre los campos de arroz o trigo', 'Soltar nube blanca de tratamiento contra plagas', 'Vuelo rasante acrobático arriesgado', 'Piloto agrícola'] },
    { w: 'HIDROAVIÓN DE BOMBEROS / APAGA FUEGOS', f: ['Flotadores en la panza para cargar agua en embalses a la carrera', 'Soltar miles de litros sobre incendios forestales', 'Color amarillo del ejército', 'Humo'] },
    { w: 'DIRIGIBLE CEPELLÍN', f: ['Globo gigante alargado con helio no inflamable', 'Góndola pequeña colgada debajo con motores de hélice', 'Publicidad flotando sobre estadios de fútbol', 'Lento en el cielo'] },
    { w: 'TRINEO MOTORIZADO DE NIEVE', f: ['Oruga de goma trasera que tracciona en nieve profunda', 'Dos esquís delanteros que giran con manillar de moto', 'Rescates en pistas de esquí y expediciones polares', 'Rápido'] },
    { w: 'CARRETILLA ELEVADORA / TORO MECÁNICO', f: ['Dos uñas de acero frontales para coger palés de mercancía', 'Giro con las ruedas traseras en pasillos de almacén', 'Contrapeso pesadísimo en la parte trasera', 'Logística'] }
  ],
  home: [
    { w: 'ZAPATILLERO DE TELA DE DETRÁS DE LA PUERTA', f: ['Bolsillos transparentes para meter veinte pares de zapatos', 'Colgado de ganchos metálicos en la parte superior', 'Ahorrar espacio en dormitorios pequeños', 'Zapatillas'] },
    { w: 'ORGANIZADOR DE CORBATAS Y CINTURONES', f: ['Percha con decenas de ganchos pequeños a los dos lados', 'Colgar en el armario sin que se arruguen', 'Tener todas las correas a la vista', 'Ropero'] },
    { w: 'PERCHAS ATERCIOPELADAS FINAS', f: ['Superficie antideslizante para que los vestidos no caigan', 'Perfil ultrafino que ahorra la mitad de espacio en la barra', 'Color negro o gris elegante', 'Armario'] },
    { w: 'CAJAS DE ALMACENAJE DE PLÁSTICO CON RUEDAS', f: ['Meter la ropa de verano durante el invierno bajo la cama', 'Tapa con cierres de clip herméticos', 'Plástico transparente para ver lo que hay dentro', 'Cambio de armario'] },
    { w: 'BOLSAS DE VACÍO PARA ROPA', f: ['Enchufar la aspiradora en la válvula redonda', 'La bolsa se comprime hasta quedar plana como una tabla', 'Guardar edredones y abrigos gigantes', 'Reducir volumen'] },
    { w: 'SAQUITOS DE LAVANDA ANTI POLILLAS', f: ['Flores secas aromáticas de lavanda', 'Colgar en las barras del armario entre los jerséis de lana', 'Evitar agujeritos en la ropa', 'Olor fresco a limpio'] },
    { w: 'CALZADOR DE ZAPATOS CON MANGO LARGO', f: ['Metal curvado para deslizar el talón sin agacharse', 'Ponerse los zapatos duros sin pisar el contrafuerte', 'Ideal para personas mayores', 'Entrada'] },
    { w: 'PARAGÜERO DE CERÁMICA', f: ['Tubo alto decorativo junto a la puerta de entrada', 'Dejar los paraguas mojados goteando al fondo', 'No mojar el parquet del pasillo', 'Días de lluvia'] },
    { w: 'BÁSCULA DE BAÑO DIGITAL', f: ['Cristal templado que se enciende al subirse con los pies descalzos', 'Dígitos en kilos con dos decimales', 'Pesarse en ayunas por la mañana', 'Dieta'] },
    { w: 'DOSIFICADOR DE DISCOS DE ALGODÓN', f: ['Tubo de metacrilato transparente con ranura abajo', 'Sacar un disco para desmaquillarse la cara con agua micelar', 'Tapa superior para rellenar', 'Lavabo'] }
  ],
  leisure: [
    { w: 'HACER MARATÓN DE PELÍCULAS DE HARRY POTTER', f: ['Ocho películas seguidas con mantita y palomitas', 'Veinte horas encerrado en casa el fin de semana', 'Magia varitas y Hogwarts', 'Plan de sofá'] },
    { w: 'HACER UN MARATÓN DE EL SEÑOR DE LOS ANILLOS', f: ['Versiones extendidas que duran doce horas en total', 'La Comunidad las Dos Torres y el Retorno del Rey', 'Viaje a Mordor comiendo pizzas', 'Cine épico'] },
    { w: 'JUGAR AL AMIGO INVISIBLE', f: ['Papelitos doblados con el nombre en un sombrero', 'Presupuesto máximo de diez o veinte euros', 'Regalo tonto o divertido en la cena de Navidad', 'Secreto'] },
    { w: 'HACER UNA FIESTA DE DISFRACES TEMÁTICA', f: ['Temática de los ochenta personajes de terror o dibujos', 'Decorar la casa con luces y música a juego', 'Concurso con premio al mejor disfraz de la noche', 'Fiesta'] },
    { w: 'IR A UNA BOLERA CON AMIGOS', f: ['Ponerse zapatos especiales bicolores usados', 'Elegir bola con el peso y agujeros adecuados', 'Hacer un pleno / strike derribando los diez bolos', 'Nachos con queso'] },
    { w: 'JUGAR A LOS DARDOS EN LA DIANA DE CORCHO', f: ['Puntas de acero afiladas tiradas a dos metros', 'Sumar puntos hasta cerrar el 501 o jugar al cricket', 'Diana con aro de doble y triple diana central roja', 'Pub inglés'] },
    { w: 'JUGAR AL BILLAR AMERICANO', f: ['Quince bolas lisas y rayadas con la negra número ocho', 'Tiza azul en la suela del taco de madera', 'Meter la blanca por error y penalización', 'Mesa de tapete verde'] },
    { w: 'IR A PATINAR SOBRE HIELO EN NAVIDAD', f: ['Pista de hielo instalada en la plaza del ayuntamiento', 'Ponerse guantes obligatorios y patines con cuchilla', 'Agarrarse a la barandilla de madera para no caer de culo', 'Frío'] },
    { w: 'HACER UNA RUTA DE SENDERISMO CON BOCATA', f: ['Mochila con cantimplora bastones y bocadillo de tortilla', 'Seguir marcas blancas y rojas de sendero GR', 'Llegar a la cima con vistas increíbles', 'Aire libre'] },
    { w: 'HACER UNA SESIÓN DE YOGA AL AIRE LIBRE', f: ['Esterilla desenrollada sobre el césped del parque', 'Postura del perro boca abajo y del guerrero', 'Respiración consciente y meditación al amanecer', 'Paz mental'] }
  ],
  culture: [
    { w: 'LA LEYENDA DEL BARRANCO DE LA MUJER MUERTA', f: ['Perfil de la montaña que parece una silueta femenina acostada', 'Sierra de Guadarrama en Madrid y Segovia', 'Cumbres nevadas con leyendas de amor', 'Naturaleza'] },
    { w: 'EL MILAGRO DEL GALLO Y LA GALLINA DE SANTO DOMINGO', f: ['Donde cantó la gallina después de asada', 'Gallinero con aves vivas dentro de la catedral', 'Camino de Santiago en La Rioja', 'Santo Domingo de la Calzada'] },
    { w: 'LA LEYENDA DE LOS AMANTES DE TERUEL', f: ['Isabel de Segura y Diego de Marcilla', 'Amor imposible que mueren de pena sin tocarse', 'Mausoleo con esculturas con manos casi unidas', 'Teruel'] },
    { w: 'EL MISTERIO DE LAS CARAS DE BÉLMEZ', f: ['Manchas que forman rostros humanos en el suelo de la cocina', 'Fenómeno paranormal de los años setenta en Jaén', 'Iker Jiménez y psicofonías', 'Casa misteriosa'] },
    { w: 'LA LEYENDA DE LA CRUZ DEL DIABLO', f: ['Hierro forjado con garras en el bosque de Cuenca', 'Leyenda gótica de Gustavo Adolfo Bécquer', 'Pacto satánico en noche de tormenta', 'Literatura'] },
    { w: 'LA LEYENDA DEL BOTAFUMEIRO DESPRENDIDO', f: ['Incensario gigante de plata volando por la catedral', 'Cuerdas de cáñamo que se rompieron saliendo por la ventana', 'Santiago de Compostela', 'Milagro'] },
    { w: 'EL RATÓN PÉREZ DE LA CALLE ARENAL', f: ['Casita en una caja de galletas de la confitería Prast', 'Dientes de leche de los niños bajo la almohada', 'Moneda a cambio de la pieza caída', 'Madrid'] },
    { w: 'LA TRADICIÓN DE LAS DOCE UVAS', f: ['Excedente de uva de Alicante en 1909', 'Comer una con cada campanada del reloj sin atragantarse', 'Ropa interior roja para atraer la suerte', 'Nochevieja'] },
    { w: 'EL ENTIERRO DE LA SARDINA DE GOYA', f: ['Cuadro famoso de máscaras bailando en corro', 'Fiesta popular madrileña a orillas del Manzanares', 'Miércoles de ceniza', 'Museo de la Academia'] },
    { w: 'LOS CARNAVALES DE SANTA CRUZ DE TENERIFE', f: ['Reina del Carnaval con traje de cientos de kilos con ruedas', 'Comparsas plumas brillantes y ritmo latino de tambores', 'Mogollón en las calles toda la noche', 'Canarias'] }
  ],
  music: [
    { w: 'COMPÁS DE BULERÍA FLAMENCA', f: ['Ritmo acelerado de doce tiempos con acentos en el 3 6 8 10 y 12', 'Palmas sordas y secas marcando el ritmo', 'Remate y jaleos ¡ole y toma que toma!', 'Fiesta gitana'] },
    { w: 'COMPÁS DE TIENTOS Y TANGOS', f: ['Ritmo binario de cuatro tiempos bailable', 'De lento y quejumbroso a alegre y rítmico', 'Guitarra flamenca y cajón marcando el golpe', 'Flamenco'] },
    { w: 'ACORDE DE CEJILLA CON DEDO TIESO', f: ['Dedo índice extendido aplastando las seis cuerdas', 'Dolor en el pulgar por apretar con fuerza el mástil', 'Hacer el acorde de Fa mayor que cuesta a principiantes', 'Guitarra'] },
    { w: 'ESCALA PENTATÓNICA MENOR', f: ['Cinco notas mágicas para improvisar solos de blues y rock', 'Cajas del mástil que todo guitarrista se aprende de memoria', 'Bendings y vibrato estirando la tercera cuerda', 'Música'] },
    { w: 'SOLO DE GUITARRA CON SLIDE / BOTTLE NECK', f: ['Tubo de cristal o metal puesto en el dedo meñique', 'Deslizar sobre las cuerdas sin pisar los trastes', 'Sonido quejumbroso y llorón del blues del Misisipi', 'Resonador'] },
    { w: 'TÉCNICA DE SLAP EN EL BAJO ELÉCTRICO', f: ['Golpear la cuerda gruesa con el hueso del pulgar', 'Tirar de la cuerda fina con el índice para que chasquee', 'Funk de Red Hot Chili Peppers / Flea', 'Sonido percusivo'] },
    { w: 'TÉCNICA DEL DOUBLE BASS EN BATERÍA', f: ['Doble pedal de bombo tocado a toda velocidad con los dos pies', 'Metralleta de golpes graves continuos en death metal', 'Baterista sudando a mares', 'Ritmo veloz'] },
    { w: 'CAMBIO DE CUERDAS DE LA GUITARRA', f: ['Aflojar y cortar las cuerdas viejas oxidadas', 'Pasar la cuerda nueva por el puente y el clavijero', 'Afinar tres veces seguidas porque se desafina al estirarse', 'Mantenimiento'] },
    { w: 'LIMPIEZA DEL DIAPASÓN CON ACEITE DE LIMÓN', f: ['Quitar la roña acumulada en la madera de palisandro', 'Frotar con un paño de microfibra limpio', 'La madera queda hidratada y oscura reluciente', 'Guitarra'] },
    { w: 'AJUSTE DEL ALMA DEL MÁSTIL', f: ['Barra metálica interior que contrarresta la tensión de las cuerdas', 'Llave allen en la pala o en la base del mástil', 'Dejar el mástil recto para que las cuerdas no trasteen', 'Luthier'] }
  ],
  body: [
    { w: 'HUESO ISQUIÓN DE LA PELVIS', f: ['Huesos donde nos apoyamos al sentarnos en una silla dura', 'Dolor en las posaderas tras horas de estudio', 'Pelvis', 'Cuerpo'] },
    { w: 'ARTICULACIÓN DE LA CADERA', f: ['Bola del fémur encajada en el hueso coxal', 'Ponerse una prótesis de titanio en personas mayores', 'Girar la pierna', 'Caminar'] },
    { w: 'LIGAMENTO CRUZADO ANTERIOR', f: ['Ruptura típica de futbolistas y esquiadores', 'Chasquido en la rodilla al girar el cuerpo en seco', 'Operación de quirófano y seis meses de baja', 'Rodilla'] },
    { w: 'MENISCO DE LA RODILLA', f: ['Almohadilla de cartílago que amortigua impactos', 'Rotura al levantarse agachado con dolor agudo', 'Artroscopia para limpiar el borde', 'Pierna'] },
    { w: 'TÚNEL CARPIANO DE LA MUÑECA', f: ['Nervio mediano comprimido por usar demasiado el ratón', 'Hormigueo y pérdida de fuerza en los tres primeros dedos', 'Muñequera rígida para dormir', 'Mano'] },
    { w: 'MANGUITO ROTADOR DEL HOMBRO', f: ['Grupo de tendones que sujetan la cabeza del húmero', 'Dolor al levantar el brazo para coger algo de un estante alto', 'Hombro', 'Tendinitis'] },
    { w: 'VÉRTEBRA LUMBAR L5-S1', f: ['Zona baja de la espalda donde más hernias discales salen', 'Cargar cajas pesadas con la espalda doblada sin flexionar rodillas', 'Lumbago y ciática', 'Dolor'] },
    { w: 'NERVIO CIÁTICO', f: ['Nervio más largo del cuerpo que baja desde la nalga hasta el pie', 'Dolor punzante eléctrico por toda la parte trasera de la pierna', 'No poder apoyar el talón en el suelo', 'Espalda'] },
    { w: 'CARTÍLAGO DE LA NARIZ', f: ['Parte flexible de la punta de la nariz', 'Tabique nasal desviado que no deja respirar bien', 'Operación de rinoplastia', 'Cara'] },
    { w: 'CUERDAS VOCALES', f: ['Pliegues en la laringe que vibran al pasar el aire', 'Nódulos por gritar demasiado en conciertos', 'Quedarse afónico sin voz', 'Cantar'] }
  ],
  clothing: [
    { w: 'GUANTES DE CUERO DE CONDUCIR', f: ['Agujeros en los nudillos y cierre con botón en la muñeca', 'Mejor agarre del volante de madera clásico', 'Elegante y retro', 'Manos'] },
    { w: 'BUFANDA DE CACHEMIR', f: ['Lana ultrasuave y caliente que no pica nada el cuello', 'Lujo invernal con flecos en los extremos', 'Colores lisos camel gris o azul marino', 'Invierno'] },
    { w: 'PASAMONTAÑAS / BALACLAVA', f: ['Cubre toda la cabeza y el cuello dejando solo los ojos a la vista', 'Esquí con ventisca helada o atracadores de bancos', 'Lana o tejido térmico negro', 'Frío'] },
    { w: 'OREJERAS ACOLCHADAS', f: ['Diadema sobre la cabeza con dos círculos de pelo en las orejas', 'Proteger del viento helado sin despeinar el peinado', 'Invierno infantil o juvenil', 'Frío'] },
    { w: 'MITONES SIN DEDOS', f: ['Guantes con los dedos cortados por la primera falange', 'Poder teclear en el móvil o tocar la guitarra con frío', 'Lana o cuero negro motero', 'Manos'] },
    { w: 'CHUBASQUERO AMARILLO DE PESCADOR', f: ['Impermeable de hule brillante con capucha grande', 'Capitán de barco bajo lluvia torrencial', 'Botones de presión que no se oxidan', 'Agua'] },
    { w: 'PONCHO ANDINO DE LANA', f: ['Manta cuadrada con agujero central para meter la cabeza', 'Colores y grecas geométricas tradicionales', 'Andes de Perú y Bolivia', 'Abrigo caliente'] },
    { w: 'FAJA DE CASTELLERS O BASTONEROS', f: ['Tira larguísima de tela negra apretada a la cintura', 'Sujetar los riñones al hacer fuerza en la piña', 'Apoyar los pies al trepar', 'Torres humanas'] },
    { w: 'LIGAS DE BODA', f: ['Cinta elástica de encaje azul o blanco en el muslo', 'Tradición de cortar a trocitos para subastar entre amigos', 'Novia el día del casamiento', 'Pierna'] },
    { w: 'MEDIAS DE REJILLA', f: ['Malla con agujeritos romboidales negros', 'Estilo rockero cabaret o noche de fiesta', 'Poner bajo falda corta o vaqueros rotos', 'Piernas'] }
  ],
  everyday: [
    { w: 'HACERLE LA CAMA A ALGUIEN', f: ['Conspirar en secreto para quitarle el puesto a un compañero', 'Jugar sucio en la oficina para que le despidan', 'Traición calculada', 'Trabajo'] },
    { w: 'MORDERSE LA COLA EL PEZ', f: ['Círculo vicioso donde una cosa causa la otra sin solución', 'Piden experiencia para trabajar pero nadie te da trabajo', 'Bucle infinito', 'Problema'] },
    { w: 'DESCUBRIR LA PÓLVORA', f: ['Creer que has inventado algo que todo el mundo ya sabía', 'Decir una obviedad con aires de genio', 'Sarcasmo de los demás ¡has descubierto la pólvora!', 'Ironía'] },
    { w: 'DARSE DE BRUCES CON LA REALIDAD', f: ['Despertar de golpe de una ilusión infantil', 'La cruda realidad golpeando con fuerza', 'Desengaño doloroso pero necesario', 'Madurar'] },
    { w: 'PONERLE EL CASCABEL AL GATO', f: ['Quién se atreve a hacer la tarea más peligrosa de todas', 'Fábula de los ratones que querían saber cuándo viene el gato', 'Nadie da el paso adelante', 'Valentía'] },
    { w: 'SALIR CON LA SUYA', f: ['Conseguir exactamente lo que quería a base de insistir', 'Niño que patalea hasta que le compran el juguete', 'Triunfo de la cabezonería', 'Victoria'] },
    { w: 'ESTAR CON EL AGUA AL CUELLO', f: ['Deudas y problemas económicos asfixiantes', 'Llegar a final de mes con la cuenta en números rojos', 'Estrés tremendo por pagar facturas', 'Apuro'] },
    { w: 'DORMIRSE EN LOS LAURELES OTRA VEZ', f: ['Perder un cliente por confiarse demasiado', 'No actualizarse y que la competencia te adelante', 'Falsa sensación de seguridad', 'Pereza'] },
    { w: 'TIRAR LA CASA POR LA VENTANA', f: ['Gastar dinero sin reparar en gastos por una celebración', 'Comprar el mejor marisco y vino para la cena de Navidad', 'Banquete por todo lo alto', 'Derroche'] },
    { w: 'ESTAR DE RODILLAS PIDIENDO PERDÓN', f: ['Suplicar clemencia tras una metedura de pata imperdonable', 'Disculpas desesperadas a la pareja o familia', 'Arrepentimiento total', 'Humildad'] }
  ]
};
